#!/bin/sh
#
# Startup script for the Apache Web Server
#
# chkconfig: 345 85 15
# description: Apache is a World Wide Web server.  It is used to serve \
#	       HTML files and CGI.
# processname: httpd
# pidfile: /var/run/httpd.pid
# config: /etc/httpd/conf/access.conf
# config: /etc/httpd/conf/httpd.conf
# config: /etc/httpd/conf/srm.conf


# Source function library.
. /etc/rc.d/init.d/functions
SLEEP=12

HTTPD=/usr/local/apache/bin/httpd
# HTTPD8000=/usr/local/apache/bin/httpd-ap-1.3.19+ssl-1.42+p-5.6.1+mp-1.25
# HTTPD8000=/usr/local/apache/bin/httpd-ap-1.3.24+ssl-1.48+p-5.7.3@17165+mp1.27
# HTTPD8000=/usr/local/apache/bin/httpd-ap-1.3.24+ssl-1.48+p-5.7.3@17273+mp1.27
# HTTPD8000=/usr/local/apache/bin/httpd-ap-1.3.26+ssl-1.48+p-5.8.0rc2+mp1.27
# HTTPD8000=/usr/local/apache/bin/httpd-ap-1.3.26+ssl-1.48+p-5.8.0rc3+mp1.27
# HTTPD8000=/usr/local/apache/bin/httpd-ap-1.3.26+ssl-1.48+p-5.6.1-2+mp-1.27
HTTPD8000=/usr/local/apache/bin/httpd-ap-1.3.26+ssl-1.48+p-5.6.1-2+ssl-0.9.6e+mp1.27

# See how we were called.
case "$1" in
  start)
	echo -n "Starting httpd: "
        : limit coredumpsize 30m -- commend not known
	/bin/nice -11 $HTTPD -f /usr/local/apache/conf/httpsd.conf.pause
	echo
	touch /var/lock/subsys/httpd
	;;
  start8000)
	echo -n "Starting httpd8000 ($HTTPD8000): "
	/bin/nice -11 $HTTPD8000 -f /usr/local/apache/conf/httpsd.conf.pause -DSWITCH8000
	echo
        touch /var/lock/subsys/httpd8000
	;;
  Xstart)
	echo -n "Starting httpd under gdb ($HTTPD): "
        echo -e "set args -f /usr/local/apache/conf/httpsd.conf.pause -X -DONE_PROCESS\nhandle SIGPIPE pass\nhandle SIGPIPE nostop\nrun" > xstart.$$.args
	gdb $HTTPD -x xstart.$$.args
        rm xstart.$$.args
	echo
	;;
  Xstart8000)
	echo -n "Starting httpd8000 under gdb ($HTTPD8000): "
        echo -e "set args -f /usr/local/apache/conf/httpsd.conf.pause -DSWITCH8000 -X -DONE_PROCESS\nhandle SIGPIPE pass\nhandle SIGPIPE nostop\nrun" > xstart8000.$$.args
	gdb $HTTPD8000 -x xstart8000.$$.args
        rm xstart8000.$$.args
	echo
	;;
  stop)
	echo -n "Shutting down http: "
	PIDFILE=/usr/local/apache/logs/httpd.pid
	[ -f "$PIDFILE" ] && {
	    kill `cat $PIDFILE`
	    echo -n httpd
	}
	echo
	rm -f /var/lock/subsys/httpd
	rm -f /var/run/httpd.pid
	;;
  stop8000)
	echo -n "Shutting down http8000: "
	PIDFILE=/usr/local/apache/logs/httpd.pid.8000
	[ -f "$PIDFILE" ] && {
	    kill `cat $PIDFILE`
	    echo -n httpd8000
	}
	echo
	rm -f /var/lock/subsys/httpd8000
	rm -f /var/run/httpd.pid.8000
	;;
  status)
	status httpd
	;;
  restart)
	$0 stop
	echo Sleeping $SLEEP seconds
	sleep $SLEEP
	$0 start
	;;
  reload)
	echo -n "Reloading httpd: "
	[ -f /var/run/httpd.pid ] && {
	    kill -HUP `cat /var/run/httpd.pid`
	    echo -n httpd
	}
	echo
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload|status|start8000|stop8000|Xstart8000}"
	exit 1
esac

exit 0
