#!/bin/sh
#
# Startup script for the Apache Web Server
#
# chkconfig: 345 85 15
# description: Apache is a World Wide Web server.  It is used to serve \
#	       HTML files and CGI.

# Source function library.
. /etc/rc.d/init.d/functions
SLEEP=12

HTTPD=/home/SVN/local/subversion/bin/httpd
HTTPDCONF=/home/SVN/local/subversion/conf/httpd.conf
PIDFILE=/home/SVN/local/subversion/logs/httpd.pid

# See how we were called.
case "$1" in
  start)
	echo -n "Starting httpd: "
        : limit coredumpsize 30m -- commend not known
	/bin/nice -11 $HTTPD -DSSL -f $HTTPDCONF
	echo
	touch /var/lock/subsys/httpd2
	;;
  stop)
	echo -n "Shutting down http: "
	[ -f "$PIDFILE" ] && {
	    kill `cat $PIDFILE`
	    echo -n httpd
	}
	echo
	rm -f /var/lock/subsys/httpd2
	;;
  status)
	status httpd2
	;;
  restart)
	$0 stop
	echo Sleeping $SLEEP seconds
	sleep $SLEEP
	$0 start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
esac

exit 0
