requires 'Apache::Session::Counted';
requires 'BSD::Resource';
requires 'CPAN::Checksums', '1.050';
requires 'CPAN::DistnameInfo';
requires 'CPAN::Indexer::Mirror';
requires 'Class::Singleton';
requires 'Crypt::Eksblowfish::Bcrypt';
requires 'DB_File';
requires 'DBI';
requires 'DBD::mysql';
requires 'DBD::SQLite';
requires 'Digest::SHA1';
requires 'Email::Address';
requires 'Email::MIME';
requires 'Email::Sender::Simple';
requires 'EV';
requires 'File::Which';
requires 'File::pushd';
requires 'Git::Wrapper';
requires 'HTML::Entities';
requires 'HTTP::Date';
requires 'HTTP::Status';
requires 'HTTP::Tiny', '0.059';
requires 'IO::Socket::SSL', '1.56';
requires 'IPC::Run3';
requires 'JSON';
requires 'JSON::XS';
requires 'LWP';
requires 'List::MoreUtils';
requires 'Log::Dispatch::Config';
requires 'Log::Dispatchouli';
requires 'Mail::Send';
requires 'Module::Signature';
requires 'MojoX::Log::Dispatch::Simple';
requires 'Mojolicious';
requires 'Mojolicious::Plugin::WithCSRFProtection';
requires 'Net::SSLeay', '1.49';
requires 'Parse::CPAN::Packages';
requires 'Parse::CPAN::Perms';
requires 'Path::Class';
requires 'Path::Tiny';
requires 'Plack::Request';
requires 'Plack::App::Directory::Apaxy';
requires 'Plack::Middleware::ReverseProxy';
requires 'Plack::Middleware::ServerStatus::Tiny';
requires 'Process::Status';
requires 'Set::Crontab';
requires 'String::Random';
requires 'Text::Format';
requires 'Text::Markdown::Hoedown';
requires 'Text::Metaphone';
requires 'Text::Soundex';
requires 'Text::Unidecode';
requires 'Time::Duration';
requires 'URI::Escape';
requires 'Unicode::String';
requires 'XML::LibXML::SAX';
requires 'XML::Parser';
requires 'XML::SAX::Base';
requires 'XML::SAX::ParserFactory';
requires 'XML::SAX::Writer';
requires 'YAML::Syck';
requires 'perl', '5.005';

on test => sub {
    requires 'DBI';
    requires 'DBIx::RunSQL';
    requires 'Email::Sender::Transport::Test';
    requires 'File::Copy::Recursive';
    requires 'File::Rsync::Mirror::Recentfile';
    requires 'File::Which';
    requires 'File::pushd';
    requires 'HTTP::Status';
    requires 'LWP::UserAgent';
    requires 'Module::Faker::Dist', '0.21';
    requires 'Mojo::Base';
    requires 'Moose';
    requires 'MooseX::StrictConstructor';
    requires 'Path::Class';
    requires 'Path::Tiny';
    requires 'SQL::Maker';
    requires 'Test::Class::Load';
    requires 'Test::FITesque';
    requires 'Test::MockObject';
    requires 'Test::WWW::Mechanize::PSGI';
    requires 'Test::mysqld';
    requires 'WWW::Mechanize::Boilerplate';
    requires 'YAML::Syck';
    requires 'YAML::XS';
    requires 'namespace::autoclean';
    requires 'perl', 'v5.10.1';
};
