upstream psgi {
	server pause:5000;
}

server {
    listen       8080;
    listen  [::]:8080;
    server_name  pause.localhost;

    root /var/www/html;

    location ~ /pause/.*\.(js|css|jpg|gif|png) {
        expires 7d;
        break;
    }

	location /incoming/ {
		root /home/ftp;
		autoindex on;
		autoindex_exact_size off;
		autoindex_localtime on;
	}

	location /pub/ {
		root /home/ftp;
		autoindex on;
		autoindex_exact_size off;
		autoindex_localtime on;
	}

    location / {
        proxy_pass http://psgi;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass_request_headers on;
        proxy_no_cache $cookie_nocache  $arg_nocache$arg_comment;
        proxy_no_cache $http_pragma     $http_authorization;
        proxy_cache_bypass $cookie_nocache $arg_nocache $arg_comment;
        proxy_cache_bypass $http_pragma $http_authorization;
        proxy_pass_header Authorization;
    }
}
