#!/usr/local/bin/perl -w

use strict;
use lib "/home/k/PAUSE/lib";
use PAUSE::mldistwatch ();
use Getopt::Long ();
sub Usage () { "FIXME Usage: $0 [options]" }
MAIN: {
    umask 0002;
    $|=1;

    my %Opt;
    Getopt::Long::GetOptions(
                             \%Opt,
                             "debug_mem!",
                             "skip-locking!",
                             "logfile=s",
                             "pick=s@",
                             "rewrite!",
                             "sleep=i",
                            ) or die Usage;
    my $mldw = PAUSE::mldistwatch->new(\%Opt);
    if ($Opt{rewrite}) {
        $mldw->work2;
    } else {
        $mldw->work;
    }
}

exit;
#Local Variables:
#mode: cperl
#cperl-indent-level: 4
#End:
