#!/usr/bin/perl

# scheduled for demise as soon as the pause2.develooper.com has taken over

use strict;
our $D;
{
  my @m=gmtime;
  $m[5]+=1900;
  $m[4]++;
  $D = sprintf "%04d%02d%02d", @m[5,4,3];
}
our $LOGDIR = "/usr/local/apache/logs";
our $BZIP2  = "/bin/bzip2";

# abstract the filename away (httpd/httpsd/etc.)
0 == system "/etc/init.d/PAUSE-httpd", "stop" or die "error stopping httpd";

rename "$LOGDIR/access_log", "$LOGDIR/access_log.$D";
rename "$LOGDIR/error_log",  "$LOGDIR/error_log.$D";
rename "$LOGDIR/ssl_log",    "$LOGDIR/ssl_log~";

# even sleep 20 was not enough on 2001-04-01
sleep 30;

0 == system "/etc/init.d/PAUSE-httpd", "start" or die "error starting httpd";

opendir my $dh, $LOGDIR or die "Couldn't opendir $LOGDIR: $!";
for my $dirent (readdir $dh) {
  next unless $dirent =~ /_log/;
  my $f = "$LOGDIR/$dirent";
  if ($dirent =~ /\.bz2$/) {
    unlink $f if -M $f > 183;
  } else {
    system $BZIP2, "--best", $f if -M $f > 1;
  }
}
