#!/usr/bin/perl

# use 5.010;
use strict;
use warnings;

=head1 NAME



=head1 SYNOPSIS



=head1 OPTIONS

=over 8

=cut

my @opt = <<'=back' =~ /B<--(\S+)>/g;

=item B<--dry-run|n!>

Run the from-mods-to-primeur.pl with the --dry-run option.

=item B<--help|h!>

This help

=back

=head1 DESCRIPTION

As in the previous batchfile, converting-m-to-f-20160312.pl, Neil
Bowers sent me the data and I wrapped them into the script.

=cut


use FindBin;
use lib "$FindBin::Bin/../lib";
BEGIN {
    push @INC, qw(       );
}

use Dumpvalue;
use File::Basename qw(dirname);
use File::Path qw(mkpath);
use File::Spec;
use File::Temp;
use Getopt::Long;
use Pod::Usage;
use Hash::Util qw(lock_keys);

our %Opt;
lock_keys %Opt, map { /([^=|!]+)/ } @opt;
GetOptions(\%Opt,
           @opt,
          ) or pod2usage(1);
if ($Opt{help}) {
    pod2usage(0);
}
$Opt{"dry-run"} //= 0;
my @dry_run;
push @dry_run, "--dry-run" if $Opt{"dry-run"};
use Time::HiRes qw(sleep);

my $i = 0;
while (<DATA>) {
    chomp;
    my $csv = $_;
    my($m,$a,$type) = split /,/, $csv;
    die "illegal type" unless $type eq "m";
    my $t = scalar localtime;
    $i++;
    warn sprintf "(%d) %s: %s\n", $i, $t, $m;
    0 == system "/opt/perl/current/bin/perl", "-Iprivatelib", "-Ilib", "bin/from-mods-to-primeur.pl", @dry_run, $m or die "Alert: $t: Problem while running from-mods-to-primeur for '$m'";
    sleep 0.08;
}

# Local Variables:
# mode: cperl
# cperl-indent-level: 4
# End:

__END__
AFS,NOG,m
AI::ExpertSystem::Simple,PETERHI,m
AI::FuzzyEngine,JMUECK,m
AI::Gene::Sequence,AJGOUGH,m
AI::Gene::Simple,AJGOUGH,m
AI::Genetic::Pro,STRZELEC,m
AI::MicroStructure,SANTEX,m
AI::Nerl,ZPMORGAN,m
AI::NeuralNet::Kohonen,LGODDARD,m
AI::Pathfinding::AStar,ACDALTON,m
AI::Pathfinding::SMAstar,MBEEBE,m
AMQP,DGOEHRIG,m
ARS,JMURPHY,m
ASP,TIMMY,m
Ace,LDS,m
Acme::Archive::Mbox,IANK,m
Acme::Chef,SMUELLER,m
Acme::Lou,TOMITA,m
Acme::PM::Barcelona,ALEXM,m
Acme::PM::Barcelona::Meeting,ALEXM,m
Acpi::Class,MIMOSINET,m
Algorithm::AhoCorasick,VBAR,m
Algorithm::AhoCorasick::SearchMachine,VBAR,m
Algorithm::Cluster::Thresh,CADAVIS,m
Algorithm::LUHN,TAYERS,m
Algorithm::Munkres,ANAGHAKK,m
Algorithm::Numerical::Sample,ABIGAIL,m
Algorithm::Permute,EDPRATOMO,m
Algorithm::SkipList,RRWO,m
Algorithm::TrunkClassifier,WOLFTOWER,m
Alien::SeleniumRC,LUKEC,m
Alien::Tidyp,KMX,m
Alter,ANNO,m
Alvis::Convert,WBUNTINE,m
Alzabo,DROLSKY,m
Amazon::S3::FastUploader,DQNEO,m
Ambrosia,KNM,m
AnyData,REHSACK,m
AnyEvent::Curl::Multi,OTTERLEY,m
AnyEvent::Handle::ZeroMQ,CINDY,m
AnyEvent::MySQL,CINDY,m
AnyEvent::Net::Curl::Queued,SYP,m
AnyEvent::Redis::RipeRedis,IPH,m
AnyEvent::STOMP,OTTERLEY,m
AnyEvent::STOMP::Client,RAPHI,m
AnyEvent::STOMP::Client::All,RAPHI,m
AnyEvent::STOMP::Client::Any,RAPHI,m
Apache::ACEProxy,MIYAGAWA,m
Apache::ASP,CHAMAS,m
Apache::AntiSpam,MIYAGAWA,m
Apache::AuthenNIS,SPEEVES,m
Apache::AuthenPasswd,SPEEVES,m
Apache::AuthenSmb,PARKER,m
Apache::AuthenURL,JGROENVEL,m
Apache::AuthzNIS,SPEEVES,m
Apache::AuthzPasswd,SPEEVES,m
Apache::CVS,BARBEE,m
Apache::Clickable,MIYAGAWA,m
Apache::Dir,DWHEELER,m
Apache::DnsZone,THOMAS,m
Apache::ExtDirect,TOKAREV,m
Apache::FastForward,JWACH,m
Apache::Filter,KWILLIAMS,m
Apache::GzipChain,ANDK,m
Apache::PassFile,ANDK,m
Apache::HTMLView,BJORNARDO,m
Apache::Hendrix,ZEDORIAH,m
Apache::Icon,DOUGM,m
Apache::Language,GOZER,m
Apache::LogFile,APML,m
Apache::Logmonster,MSIMERSON,m
Apache::Mmap,FLETCH,m
Apache::OutputChain,JANPAZ,m
Apache::SSIChain,JANPAZ,m
Apache::PrettyPerl,RA,m
Apache::Reload,APML,m
Apache::Request::I18N,FBRIERE,m
Apache::Upload::I18N,FBRIERE,m
Apache::SSI,KWILLIAMS,m
Apache::SWIT,BOSU,m
Apache::Scoreboard,MJH,m
Apache::SdnFw,CJS,m
Apache::Session::Browseable,GUIMARD,m
Apache::Session::LDAP,GUIMARD,m
Apache::SiteControl,AWKAY,m
Apache::SubProcess,APML,m
Apache::Sybase::CTlib,MDOWNING,m
Apache::Template,ABW,m
Apache::Test,APML,m
Apache::Test,APML,m
Apache::Throttle,DONS,m
Apache::UploadMeter,ISAAC,m
Apache::UploadSvr,ANDK,m
Apache::Voodoo,MAVERICK,m
Apache::iNcom,FRAJULAC,m
Apache2::ASP,JOHND,m
Apache2::AuthZSympa,DOUMBZH,m
Apache2::AuthenNTLM,SPEEVES,m
Apache2::AuthzCaps,MGV,m
Apache2::BalanceLogic,MIKI,m
Apache2::Controller,MARKLE,m
Apache2::DebugFilter,PGOLLUCCI,m
Apache2::FileHash,BPMEDLEY,m
Apache2::Filter::HTTPHeadersFixup,PGOLLUCCI,m
Apache2::PageKit,BORISZ,m
Apache2::REST,JETEVE,m
Apache2::WebApp::Plugin::CGI,MBROOKS,m
Apache2::WebApp::Plugin::Cookie,MBROOKS,m
Apache2::WebApp::Plugin::DBI,MBROOKS,m
Apache2::WebApp::Plugin::DateTime,MBROOKS,m
Apache2::WebApp::Plugin::File,MBROOKS,m
Apache2::WebApp::Plugin::Filters,MBROOKS,m
Apache2::WebApp::Plugin::Mail,MBROOKS,m
Apache2::WebApp::Plugin::Session,MBROOKS,m
Apache2::WebApp::Plugin::Session::File,MBROOKS,m
Apache2::WebApp::Plugin::Session::MySQL,MBROOKS,m
Apache2::WebApp::Plugin::Validate,MBROOKS,m
App::Alice,LEEDO,m
App::BackupPlan,GCHIAIA,m
App::Basis,MOODFARM,m
App::Booklist,GENEHACK,m
App::CCSV,GARGAMEL,m
App::CLI::Extension,HOLLY,m
App::ClusterSSH,DUNCS,m
App::CmdDirs,DINOMITE,m
App::FonBot::Daemon,MGV,m
App::Framework,SDPRICE,m
App::Getconf,DOZZIE,m
App::GitGot,GENEHACK,m
App::Gitc,GSG,m
App::HTTP_Proxy_IMP,SULLR,m
App::Info,DWHEELER,m
App::MaMGal,PORRIDGE,m
App::Midgen,BOWTIE,m
App::Modular,BCEVC,m
App::Music::PlayTab,JV,m
App::Office::CMS,RSAVAGE,m
App::Office::Contacts,RSAVAGE,m
App::Office::Contacts::Donations,RSAVAGE,m
App::Office::Contacts::Import::vCards,RSAVAGE,m
App::Open,ERIKH,m
App::PM::Website,SPAZM,m
App::Prove::Plugin::TraceUse,TORBJORN,m
App::Services,SBLANTON,m
App::SnerpVortex,RCAPUTO,m
App::Sv,GVL,m
App::XUL,KITOMER,m
App::Zapzi,RUPERTL,m
AppleII::Disk,CJM,m
AppleII::ProDOS,CJM,m
Gtk2::Ex::FileLocator,HOOO,m
ArangoDB,HIDEAKIO,m
Archive::Ar,JAYBONCI,m
Archive::BagIt,RJESCHMI,m
Archive::Cpio,PIXEL,m
Archive::Har,DDICK,m
Archive::Zip::Parser,HAGGAI,m
Argv,DSB,m
Array::Heap,MLEHMANN,m
Array::IntSpan,DDUMONT,m
Array::OrdHash,WOWASURIN,m
Array::Tour,JGAMBLE,m
Arriba,ODYNIEC,m
AsciiDB::TagFile,JOSERODR,m
Asm::Preproc,PSCUST,m
Aspect::Loader,HAOSAN,m
Mac::AssistantFrames,GBAUER,m
Asterisk::AMI,GREENBEAN,m
Asterisk::FastAGI,JAYWHY,m
Astro::Coord,CPHIL,m
Astro::Misc,CPHIL,m
Astro::Time,CPHIL,m
Astro::Constants,DUFFEE,m
Astro::SIMBAD::Client,WYANT,m
Astro::SkyCat,TJENNESS,m
Astro::SkyX,RWOODARD,m
Astro::Sunrise,RKHILL,m
Async::Selector,TOSHIOITO,m
Asynchat,SEBA,m
Asyncore,SEBA,m
AtExit,NEILB,m
Attribute::Overload,MARCEL,m
Attribute::Signature,CHORNY,m
Attribute::TieClasses,MARCEL,m
Attribute::Types,DCONWAY,m
Audio::Analyzer,TRIDDLE,m
Audio::DB,TWH,m
Audio::File,FLORA,m
Audio::MPD,JQUELIN,m
Audio::MPD::Common,JQUELIN,m
Audio::MPEG,PTIMOF,m
Audio::MikMod,DANIEL,m
Audio::Moosic,FLORA,m
Audio::SoundFile,TAIY,m
Audio::TagLib::Shell,DONGXU,m
AudioCD,SDERLE,m
AudioCD::Mac,AJFRY,m
Authen::ACE4,MIKEM,m
Authen::CAS::Client,PRAVUS,m
Authen::Credential,LCONS,m
Authen::Krb5::KDB,DKS,m
Authen::PAM,NIKIP,m
Authen::Passphrase,ZEFRAM,m
Authen::PluggableCaptcha,JVANASCO,m
Authen::SASL,GBARR,m
Authen::SASL::Cyrus,ADAMSON,m
Authen::TacacsPlus,MSHOYHER,m
Authen::Ticket,JSMITH,m
Autocache,WIGGLY,m
AxKit::XSP::BasicSession,KJETILK,m
AxKit::XSP::Sendmail,MSERGEANT,m
B::Debugger,RURBAN,m
B::Deobfuscate,JJORE,m
B::Keywords,JJORE,m
B::LexInfo,DOUGM,m
B::Size,DOUGM,m
B::TerseSize,DOUGM,m
BBCode::Parser,DLKING,m
BBDB::Export,VVU,m
BBS::DiscuzX2,ABBYPAN,m
BPM::Engine,SITETECH,m
BSD::Ipfwgen,MUIR,m
BSON,MONGODB,m
BTRIEVE::SAVE,DLANE,m
BackPAN::Version::Discover,SSCAFFIDI,m
Badger,ABW,m
BankAccount::Validator::UK,MANWAR,m
Barcode::ZBar,SPADIX,m
Baseball::Sabermetrics,VICTOR,m
Benchmark::Featureset::LocaleCountry,RSAVAGE,m
Benchmark::Featureset::SetOps,RSAVAGE,m
Benchmark::Featureset::StopwordLists,RSAVAGE,m
Benchmark::Timer,DCOPPIT,m
BerkeleyDB,PMQS,m
BerkeleyDB::Lite,TQISJIM,m
BibTeX::Parser,GERHARD,m
Biblio::Citation::Parser,MJEWELL,m
Biblio::Document::Parser,MJEWELL,m
Biblio::Refbase,HMA,m
BigIP::iControl,LTP,m
Bigtop,PHILCROW,m
Bio::ASN1::EntrezGene,BIOPERLML,m
Bio::BioStudio,NOTDOCTOR,m
Bio::Cellucidate,BKANEY,m
Bio::Chado::Schema,RBUELS,m
Bio::Community,FANGLY,m
Bio::DB::USeq,TJPARNELL,m
Bio::Das::ProServer,RPETTETT,m
Bio::GMOD,TWH,m
Bio::GeneDesign,NOTDOCTOR,m
Bio::Gonzales,JWB,m
Bio::Grid::Run::SGE,JWB,m
Bio::Homology::InterologWalk,GGALLONE,m
Bio::KBase,RDO,m
Bio::MAGE,JASONS,m
Bio::MAGETAB,TFRAYNER,m
Bio::Data::Plasmid::CloningVector,SLENK,m
Bio::MCPrimers,SLENK,m
Bio::Phylo,RVOSA,m
Bio::SeqReader,JAC,m
Bio::Taxonomy::GlobalNames,DGKONTOP,m
Bit::Vector,STBEY,m
Blatte,BOBG,m
Blatte::Builtins,BOBG,m
Blatte::Compiler,BOBG,m
Blatte::Parser,BOBG,m
Blatte::Syntax,BOBG,m
Blatte::Ws,BOBG,m
Blatte::HTML,BOBG,m
Blitz,BKLAAS,m
Bloom::Filter,MCEGLOWS,m
Blosxom::Plugin,ANAZAWA,m
Bot::Jabbot,ISAGE,m
Bot::Pastebot,RCAPUTO,m
Brick,BDFOY,m
Bricklayer::Templater,ZAPHAR,m
Bundle::BDFOY,BDFOY,m
Bundle::Compress::Zlib,PMQS,m
Bundle::KohaSupport,KOHA,m
Bundle::Perl6,MARCEL,m
Bundle::W3C::Validator,SCOP,m
Burpsuite::Parser,JABRA,m
Business::CA::GST,OALDERS,m
Business::Cart::Generic,RSAVAGE,m
Business::CreditCard,IVAN,m
Business::CyberSource::Report,AUBERTG,m
Business::EDI,JOEATZ,m
Business::FedEx::DirectConnect,JPOWERS,m
Business::GestPayCrypt,GAZERRO,m
Business::ISBN,BDFOY,m
Business::ISMN,BDFOY,m
Business::OnlinePayment::InternetSecure,FBRIERE,m
Business::OnlinePayment::Iridium,WREIS,m
Business::OnlinePayment::Ogone,ESSELENS,m
Business::PayPal::SDK,LINNIN,m
Business::RU,GERMANS,m
Business::WebMoney,AML,m
Business::WorldPay::Junior,CLIFFORDJ,m
Bytes::Random::Secure,DAVIDO,m
C::DynaLib,RURBAN,m
C::Include,AMICHAUER,m
C::Scan,ILYAZ,m
C::sparse,EISELEKD,m
CA::AutoSys,SINI,m
CAD::Drawing,EWILHELM,m
CAD::Firemen,LANGENJO,m
CAD::ProEngineer,MMETTES,m
CAM::PDF::Annot,DONATOAZ,m
CDB_File,MSERGEANT,m
CDB_File::BiIndex,MIKEDLR,m
CDB_File::BiIndex::Generator,MIKEDLR,m
CDDB::Fake,JV,m
CGI::Ajax,BCT,m
CGI::Apache2::Wrapper,ADOPTME,m
CGI::Application,JERLBAUM,m
CGI::Application::Bouquet::Rose,RSAVAGE,m
CGI::Application::Demo::Basic,RSAVAGE,m
CGI::Application::Demo::Dispatch,RSAVAGE,m
CGI::Application::Muto,ULIZAMA,m
CGI::Application::PhotoGallery,BRICAS,m
CGI::Application::Plugin::ActionDispatch,JAYWHY,m
CGI::Application::Plugin::DevPopup,RHESA,m
CGI::Application::Plugin::I18N,COSMICNET,m
CGI::Application::Plugin::PageLookup,SILASMONK,m
CGI::Application::Plugin::ValidateQuery,MARKSTOS,m
CGI::Application::Structured,VANAMBURG,m
CGI::Application::Structured::Tools,VANAMBURG,m
CGI::Application::Util::Diff,RSAVAGE,m
CGI::Cache,DCOPPIT,m
CGI::Carp::DebugScreen,ISHIGAKI,m
CGI::ContactForm,GUNNAR,m
CGI::Ex,RHANDOM,m
CGI::FormBuilder,NWIGER,m
CGI::IDS,HINNERK,m
CGI::Imagemap,MIKEH,m
Apache2::JSONRPC,CRAKRJACK,m
CGI::JSONRPC,CRAKRJACK,m
CGI::Kwiki,INGY,m
CGI::Lazy,VAYDE,m
CGI::Lite,HOUSTON,m
CGI::Mungo,DUMB,m
CGI::MxScreen,PURDY,m
CGI::Out,MUIR,m
CGI::Panel,RSYMES,m
CGI::Portable,DUNCAND,m
CGI::SSI,JAMES,m
CGI::Screen,ULPFR,m
CGI::Snapp::Demo::Four,RSAVAGE,m
CGI::Snapp::Dispatch,RSAVAGE,m
CGI::SpeedyCGI,HORROCKS,m
CGI::URI2param,DOMM,m
CGI::Untaint::Filenames,DHUDES,m
CGI::WML,AWOOD,m
CGI::WebToolkit,KITOMER,m
CGI::Wiki::Store::Mediawiki,DPRICE,m
CGI::XMLForm,MSERGEANT,m
CGI_Lite,SHGUN,m
CHI::Driver::SharedMem,NHORNE,m
CIPP,JRED,m
CLI::Framework,KERISMAN,m
CORBA::IOP::IOR,PHILIPA,m
CORBA::Python,PERRAD,m
CORBA::XPIDL,PERRAD,m
CORBA::omniORB,HOUSEL,m
CPAN::Mini::Inject::Server,CMCKAY,m
CPAN::SQLite,STRO,m
CPAN::Search::Lite::Index,ISHIGAKI,m
CPANPLUS::Dist::Gentoo,VPIT,m
CPANPLUS::Shell::Wx,SKAMANSAM,m
CPU::Z80::Disassembler,PSCUST,m
CSS::Croco,GUGU,m
CSS::DOM,SPROUT,m
CSS::Inliner,KAMELKEV,m
CSS::Packer,NEVESENIN,m
CSS::Prepare,MNF,m
CSS::SAC,BJOERN,m
CSS::SpriteBuilder,YOREEK,m
CSS::SpriteMaker,DARKSMO,m
Cache::BerkeleyDB,BALDUR,m
Cache::Cache,DCLINTON,m
Cache::CacheFactory,SGRAHAM,m
Cache::FastMemoryCache,MILLAWAY,m
Cache::Repository,DMCBRIDE,m
Cache::Static,BRIANSKI,m
Calendar::Bahai,MANWAR,m
Captcha::AreYouAHuman,JONATAYAH,m
Carp::Assert,YVES,m
Carp::Clan,JJORE,m
Carp::REPL,SARTAK,m
Catalog,LDACHARY,m
Catalyst::Action::Role::ACL,CONVERTER,m
Catalyst::ActionRole::ACL,CONVERTER,m
Catalyst::Authentication::Credential::Twitter,JESSESTAY,m
Catalyst::Authentication::Store::DBIx::Class,BOBTFISH,m
Catalyst::Controller::BindLex,NUFFIN,m
Catalyst::Controller::FormBuilder::MultiForm,DWARREN,m
Catalyst::Log::Log4perl,BOBTFISH,m
Catalyst::Model::DBIC::Schema,MSTROUT,m
Catalyst::Model::XML::Feed,JROCKWAY,m
Catalyst::Plugin::Authentication,BOBTFISH,m
Catalyst::Plugin::Authentication::Credential::TypeKey,NUFFIN,m
Catalyst::Plugin::Authorization::Roles,NUFFIN,m
Catalyst::Plugin::CRUD,BAYSIDE,m
Catalyst::Plugin::ConfigLoader,BRICAS,m
Catalyst::Plugin::DefaultEnd,MRAMBERG,m
Catalyst::Plugin::FormBuilder,NWIGER,m
Catalyst::Plugin::Log::Dispatch,SHOT,m
Catalyst::Plugin::Log::Handler,PEPE,m
Catalyst::Plugin::Log::Message,MICHIEL,m
Catalyst::Plugin::OrderedParams,AGRUNDMA,m
Catalyst::Plugin::PageCache,AGRUNDMA,m
Catalyst::Plugin::Params::Profile,MICHIEL,m
Catalyst::Plugin::RequireSSL,AGRUNDMA,m
Catalyst::Plugin::Scheduler,AGRUNDMA,m
Catalyst::Plugin::Server,KANE,m
Catalyst::Plugin::Server::JSONRPC,DARKNOS,m
Catalyst::Plugin::Session::PerUser,NUFFIN,m
Catalyst::Plugin::Session::State::Cookie,NUFFIN,m
Catalyst::Plugin::Session::Store::DBI,AGRUNDMA,m
Catalyst::Plugin::Session::Store::FastMmap,MSTROUT,m
Catalyst::Plugin::Session::Store::Memcached,NUFFIN,m
Catalyst::Plugin::StackTrace,AGRUNDMA,m
Catalyst::Plugin::Static::Simple,BOBTFISH,m
Catalyst,MSTROUT,m
Catalyst::Base,MSTROUT,m
Catalyst::Controller,MSTROUT,m
Catalyst::Engine,MSTROUT,m
Catalyst::Model,MSTROUT,m
Catalyst::View,MSTROUT,m
Catalyst::View::Image::Empty,CAGAO,m
Catalyst::View::JavaScript::Minifier::XS,DRINCHEV,m
Catalyst::View::PDF::API2,FERZ,m
Catalyst::View::TT,MSTROUT,m
Catalyst::View::TT::FunctionGenerator,NUFFIN,m
Catalyst::View::Templated,JROCKWAY,m
Catalyst::View::Tenjin,IDOPEREL,m
CatalystX::ListFramework,SNAFUFANS,m
CatalystX::RoseIntegrator,MIDNITE,m
Chart::EPS_graph,APLONIS,m
Chart::Graph,CAIDAPERL,m
Chart::PNGgraph,SBONDS,m
Chart::Plot::Canvas,PERRAD,m
Chatbot::Alpha,KIRSLE,m
Chatbot::Alpha::Sort,KIRSLE,m
Chatbot::Alpha::Syntax,KIRSLE,m
Chatbot::Alpha::Tutorial,KIRSLE,m
Chatbot::Eliza,JNOLAN,m
Chemistry::File::PDB,ITUB,m
Cisco::Accounting,MWALLRAF,m
Cisco::Conf,JWIED,m
Cisco::UCS,LTP,m
Clarion,ICHE,m
Class::Accessor,KASEI,m
Class::Action,DMUEY,m
Class::ArrayObjects,RONAN,m
Class::Closure,ARISTOTLE,m
Class::CodeStyler,GAFFIE,m
Class::Core,CODECHILD,m
Class::DBI,TMTM,m
Class::DBI::Loader::Informix,JSTOWE,m
Class::DBI::Oracle,DANIEL,m
Class::DBI::Plugin::Pager,DAVEBAIRD,m
Class::DBI::Replicated,HDP,m
Class::DBI::Template,JASONK,m
Class::DI,HAOSAN,m
Class::Data::Reloadable,DAVEBAIRD,m
Class::Date,DLUX,m
Class::Template,DMR,m
Class::Fields,MSCHWERN,m
Class::GAPI,CROSSWIRE,m
Class::Generate,SWARTIK,m
Class::ISA,SMUELLER,m
Class::Injection,AHERNIT,m
Class::Interface,SINISTER,m
Class::IntrospectionMethods,DDUMONT,m
Class::Loader,VIPUL,m
Class::MakeMethods,EVO,m
Class::Measure,BLUEFEET,m
Class::MethodFilter,MSTROUT,m
Class::MethodMaker,FLUFFY,m
Class::OWL,LEIFJ,m
Class::Prevayler,NATHANAEL,m
Class::Prototyped,TEVERETT,m
Class::PseudoHash,AUTRIJUS,m
Class::Ref,MYDMNSN,m
Class::STL::Containers,GAFFIE,m
Class::Singleton,ABW,m
Class::StructTemplate,HEIKOWU,m
Class::Tangram,SAMV,m
Class::User::DBI,DAVIDO,m
Class::XML::Parser,MMORGAN,m
ClearCase::Wrapper::MGi,MGI,m
CljPerl,WEHU,m
Clone,RDF,m
CloudApp::REST,MDIETRICH,m
Clutter,EBASSI,m
Collision::2D,ZPMORGAN,m
Color::Calc,CFAERBER,m
Color::Scheme,IAN,m
Color::TupleEncode,MARTINK,m
Compiler::Lexer,GOCCY,m
Compiler::Parser,GOCCY,m
Compress::Bzip2,ARJAY,m
Compress::LZW,MHOWARD,m
Compress::LZW::Progressive,EWATERS,m
Config::Abstract,AVAJADI,m
Config::Apt::Sources,IANK,m
Config::Augeas,DDUMONT,m
Config::BuildHelper,TRIDDLE,m
Config::FileManager,DOCCY,m
Config::Find,SALVA,m
Config::General,TLINDEN,m
Config::IniFiles,WADG,m
Config::LotusNotes,ALBERS,m
Config::Magic,RUSTYP,m
Config::Model,DDUMONT,m
Config::Model::Approx,DDUMONT,m
Config::Model::CursesUI,DDUMONT,m
Config::Model::Itself,DDUMONT,m
Config::Model::OpenSsh,DDUMONT,m
Config::Model::Xorg,DDUMONT,m
Config::Scoped,GAISSMAI,m
Config::Strict,BLAKEW,m
Confman,MASAHJI,m
Connector,MRSCOTTY,m
Convert::ASCII::Armor,VIPUL,m
Convert::BER,GBARR,m
Convert::Base32,MIYAGAWA,m
Convert::Binary::C,MHX,m
Convert::GeekCode,AUTRIJUS,m
Convert::IBM390,GROMMEL,m
Convert::Morse,TELS,m
Convert::PEM,BTROTT,m
Convert::TNEF,DOUGW,m
Convert::Wiki,TELS,m
Convert::yEnc,SWMCD,m
Coy,DCONWAY,m
Lingua::EN::Hyphenate,DCONWAY,m
Criteria::Compile,ALUCAS,m
Crypt::Affine,MANWAR,m
Crypt::CBC,LDS,m
Crypt::CFB,KJH,m
Crypt::DH,BTROTT,m
Crypt::DSA,BTROTT,m
Crypt::Eksblowfish,ZEFRAM,m
Crypt::Eksblowfish::Bcrypt,ZEFRAM,m
Crypt::FNA,ANAK,m
Crypt::GCrypt,AAR,m
Crypt::GOST,AMS,m
Crypt::GPG,AGUL,m
Crypt::IDA,DMALONE,m
Crypt::IDEA,DPARIS,m
Crypt::Image,MANWAR,m
Crypt::Keys,BTROTT,m
Crypt::NSS::X509,JOHANNA,m
Crypt::Nettle,DKG,m
Crypt::OTR,REVMISCHA,m
Crypt::OpenSSL::RSA,IROBERTS,m
Crypt::OpenSSL::Random,IROBERTS,m
Crypt::PBC,JETTERO,m
Crypt::PasswdMD5,LUISMUNOZ,m
Crypt::RSA,VIPUL,m
Crypt::RandPasswd,JDPORTER,m
Crypt::Random,VIPUL,m
Crypt::Rijndael,BDFOY,m
Crypt::SSLeay,NANIS,m
Net::SSL,NANIS,m
Crypt::SaltedHash,ESSKAR,m
Crypt::TripleDES,VIPUL,m
Crypt::Twofish,AMS,m
Crypt::X509,JACKSONM,m
Csistck,AGJ,m
Cz::Cstocs,JANPAZ,m
Cz::Sort,JANPAZ,m
Cdk,GLOVER,m
Curses::Forms,CORLISS,m
Curses::Widgets,CORLISS,m
DB2::db,DMCBRIDE,m
DBD::ADO,SGOELDNER,m
DBD::ASAny,SMIRNIOS,m
DBD::Amazon,DARNOLD,m
DBD::AnyData,REHSACK,m
DBD::CSV,HMBRAND,m
DBD::DB2,IBMTORDB2,m
DBD::DtfSQLmac,TWEGNER,m
Mac::DtfSQL,TWEGNER,m
DBD::Empress,SWILLIAM,m
DBD::Excel,KWITKNR,m
DBD::Firebird,MARIUZ,m
DBD::Illustra,PMH,m
DBD::Informix,JOHNL,m
DBD::Ingres,HTOUG,m
Ingperl,HTOUG,m
DBD::InterBase,EDPRATOMO,m
DBD::MVS_FTPSQL,CBIONDO,m
DBD::MaxDB,MAXDB,m
DBD::Multi,DWRIGHT,m
DBD::ODBC,TIMB,m
DBD::PgLite,BALDUR,m
DBD::PgPP,OYAMA,m
DBD::PrimeBase,PRIMEBASE,m
DBD::QBase,BENLI,m
DBD::RAM,JZUCKER,m
DBD::Salesforce,BAYSIDE,m
DBD::SearchServer,SHARI,m
DBD::Solid,TWENRICH,m
DBD::Sprite,TURNERJW,m
DBD::Sybase,MEWP,m
DBD::TSM,LBENDAVID,m
DBD::Unify,HMBRAND,m
DBD::Wire10,DUBEX,m
DBD::cubrid,CUBRID,m
DBD::drizzle,CAPTTOFU,m
DBD::mysql,CAPTTOFU,m
Mysql,CAPTTOFU,m
DBD::mysqlPP,TSUCCHI,m
DBD::pNET,JWIED,m
DBD::Sqlflex,INFOFLEX,m
DBIx::ActiveRecord,TSAITO,m
DBIx::AnyDBD,MSERGEANT,m
DBIx::Browse,EJDRS,m
DBIx::Changeset,PARANOID,m
DBIx::Chart,DARNOLD,m
DBIx::Class::CustomPrefetch,GUGU,m
DBIx::Class::FrozenColumns,SYBER,m
DBIx::Class::PgLog,SHEEJU,m
DBIx::Class::Snowflake,MFOLLETT,m
DBIx::Compare::ContentChecksum::mysql,CJONES,m
DBIx::DBSchema,IVAN,m
DBIx::FetchLoop,BITS,m
DBIx::FullTextSearch,TJMATHER,m
DBIx::Informix::Perform,WEAV,m
DBIx::Log4perl,MJEVANS,m
DBIx::Lookup::Field,MARCEL,m
DBIx::Migration::Classes,KITOMER,m
DBIx::Migration::Directories,CRAKRJACK,m
DBIx::MyParse,PHILIPS,m
DBIx::MyParsePP,PHILIPS,m
DBIx::MyParseX,CTBROWN,m
DBIx::MyServer,PHILIPS,m
DBIx::NamedQuery,BOLEK,m
DBIx::ORM::Declarative,JSCHNEID,m
DBIx::ObjectMapper,OISHI,m
DBIx::Objects,ISAAC,m
DBIx::PgLink,ASVBR,m
DBIx::Query,GRYPHON,m
DBIx::Recordset,GRICHTER,m
DBIx::RetryOverDisconnects,SYBER,m
DBIx::RoboQuery,RWSTAUNER,m
DBIx::Roles,KARASIK,m
DBIx::Romani,DSNOPEK,m
DBIx::SQLEngine,EVO,m
DBIx::Safe,TURNSTEP,m
DBIx::Simple,JUERD,m
DBIx::SimpleQuery,SSIMMS,m
DBIx::Table::TestDataGenerator,JDS,m
DBIx::TextIndex,DKOCH,m
DBIx::Threaded,DARNOLD,m
DBIx::Transaction,CRAKRJACK,m
DBIx::Tree,BJEPS,m
DBIx::Tree::MaterializedPath,LARRYL,m
DBIx::Tree::Persist,RSAVAGE,m
DBIx::XML::DataLoader,CBERNING,m
DBZ_File,IANPX,m
DCE::ACL,PHENSON,m
DCE::Login,PHENSON,m
DCE::Registry,PHENSON,m
DCE::Status,PHENSON,m
DCE::UUID,PHENSON,m
DMTF::CIM,SHURD,m
DMTF::CIM::WSMan,SHURD,m
DMTF::WSMan,SHURD,m
DNS::Config,WOLF,m
DNS::LDNS,ERIKOEST,m
DNS::Zone,WOLF,m
DNS::ZoneParse,SIMONFLK,m
DOCSIS::ConfigFile,JHTHORSEN,m
DPKG::Log,APTITUZ,m
DVB::Epg,NABOJ,m
DWH_File,SUMUS,m
Daemon::Shutdown,RCL,m
Dancer::Plugin::DebugToolbar,ODYNIEC,m
Dancer::Plugin::FakeCGI,KOCEASY,m
Dancer::Plugin::Redis,CELOGEEK,m
Dancer::Session::DBIC,HORNBURG,m
Danga::Socket,BRADFITZ,m
Darcs::Inventory,DAVID,m
Darcs::Notify,DAVID,m
Data::Alias,ZEFRAM,m
Data::All,DELANO,m
Data::BitStream,DANAJ,m
Data::Classifier,TRIDDLE,m
Data::Constraint,BDFOY,m
Data::CosineSimilarity,AIMBERT,m
Data::DEC,KITOMER,m
Data::DRef,EVO,m
Data::Domain,DAMI,m
Data::FeatureFactory,SIXTEASE,m
Data::Flow,ILYAZ,m
Data::Freq,MAHIRO,m
Data::JavaScript,ADOPTME,m
Data::Nested,SBECK,m
Data::Paging,AINAME,m
Data::Passphrase,KORTY,m
Data::Password::Filter,MANWAR,m
Data::Petitcom,HAYAJO,m
Data::Predicate,AYATES,m
Data::Random,BAREFOOT,m
Data::Range::Compare::Stream,AKALINUX,m
Data::Reporter,RVAZ,m
Data::RuledValidator,KTAT,m
Data::SExpression,NELHAGE,m
Data::SecsPack,SOFTDIA,m
Data::Serializer,NEELY,m
Data::Session,RSAVAGE,m
Data::Shark,BILLWALZ,m
Data::Sync,CCOLBOURN,m
Data::Tabular,GAM,m
Data::Tabular::Dumper,GWYN,m
Data::TimeSeries,TOMMIE,m
Data::URIEncode,RHANDOM,m
Data::Validate::Domain,NEELY,m
Data::Validate::IP,NEELY,m
Data::Validate::VIN,CSEATON,m
Data::Walk::Clone,JANDREW,m
Data::Walk::Extracted,JANDREW,m
Data::Walk::Graft,JANDREW,m
Data::Walk::Print,JANDREW,m
Data::Walk::Prune,JANDREW,m
DataCube,DAVEGMX,m
Date::Calc,STBEY,m
Date::DayOfWeek,RBOW,m
Date::Doomsday,RBOW,m
Date::Gregorian,MHASCH,m
Date::Handler,BBEAUSEJ,m
Date::ICal,RBOW,m
Date::Japanese::Era,MIYAGAWA,m
Date::Manip,SBECK,m
Date::Namedays::Simple,FAGZAL,m
Date::Parser,HEJKI,m
Date::Passover,RBOW,m
Date::Pcalc,STBEY,m
Date::Simple,YVES,m
DateTime::BusinessHours,SOLARANT,m
DateTime::Event::Cron,MSISK,m
DateTime::Event::Easter,RICKM,m
DateTime::Format::Builder,DROLSKY,m
DateTime::Format::Pg,DMAKI,m
DateTime::Format::Strptime,RICKM,m
DateTimeX::Factory,TAKUJI,m
DateTimeX::Mashup::Shiras,JANDREW,m
Db::DFC,MSROTH,m
Db::Documentum,MSROTH,m
Debug::FaultAutoBT,STAS,m
Debug::Fork::Tmux,VERESC,m
Debug::ShowStuff,MIKO,m
Decision::ACL,BBEAUSEJ,m
Decision::Markov,ALANSZ,m
Devel::Backtrace,PEPE,m
Devel::Callsite,ROCKY,m
Devel::Comments,XIONG,m
Devel::Constants,CHROMATIC,m
Devel::Cover,PJCJ,m
Devel::Cover::Report::Clover,DBARTLE,m
Devel::DProf,DMR,m
Devel::DebugInit,JASONS,m
Devel::Declare::Lexer,IANKENT,m
Devel::GDB,JEZRA,m
Devel::GDB::Reflect,AFN,m
Devel::Hints,AUTRIJUS,m
Devel::MemoryTrace::Light,WOLFSAGE,m
Devel::Modlist,RJRAY,m
Devel::PPPort,MHX,m
Devel::PerlySense,JOHANL,m
Devel::RingBuffer,DARNOLD,m
Devel::STrace,DARNOLD,m
Devel::STrace,DARNOLD,m
Devel::SearchINC,MARCEL,m
Devel::Size,NWCLARK,m
Devel::SmallProf,ASHTED,m
Devel::StackTrace,DROLSKY,m
Devel::Symdump,ANDK,m
Devel::TraceLoad,ANDYA,m
Devel::Trepan,ROCKY,m
Device::Cdio,ROCKY,m
Device::ISDN::OCLM,MERLIN,m
Device::Inverter::Aurora,FREMAN,m
Device::LaCrosse::WS23xx,ESM,m
Device::Modem,COSIMO,m
Device::Opto22,TROXEL,m
Device::ParallelPort,SCOTT,m
Device::SNP,MIKEM,m
Device::SerialPort,COOK,m
Device::TNC,RBDAVISON,m
Device::USB::PCSensor::HidTEMPer,MSULLAND,m
Device::VantagePro,ABEVERLEY,m
Device::ZyXEL::IES,JDALBERG,m
Dialog,UNCLE,m
Digest::CMAC,NUFFIN,m
Digest::DMAC,JCDUQUE,m
Digest::HMAC,GAAS,m
Digest::SHA1,UWEH,m
Digest::SHA2,JCDUQUE,m
Digest::Whirlpool,JCDUQUE,m
Dirbuster::Parser,JABRA,m
Directory::Queue,LCONS,m
Directory::Scratch,JROCKWAY,m
Dist::Zilla::Plugin::Subversion,MJGARDNER,m
Dist::Zilla::Plugin::Subversion::ReleaseDist,MJGARDNER,m
Dist::Zilla::Plugin::Subversion::Tag,MJGARDNER,m
Dist::Zilla::Role::Subversion,MJGARDNER,m
Dist::Zilla::PluginBundle::Author::LESPEA,LESPEA,m
Dist::Zilla::PluginBundle::ODYNIEC,ODYNIEC,m
Dotiac::DTL,MALUKU,m
Doxygen::Filter::Perl,JORDAN,m
Drogo,MJFLICK,m
Drupal::Admin,DURIST,m
Drupal::Module::Starter,SMCNABB,m
EBook::Generator,KITOMER,m
EBook::MOBI,BORISD,m
EBook::Tools,AZED,m
EJS::Template,MAHIRO,m
EEDB,JMS,m
Egg::Release,LUSHE,m
Ekahau,GIFF,m
Emacs,JTOBEY,m
Emacs::Lisp,JTOBEY,m
Emacs::PDE,YEWENBIN,m
Email::AutoReply,AMONSEN,m
Email::ConstantContact,ARICH,m
Email::ExactTarget,AUBERTG,m
Email::Find,MIYAGAWA,m
Email::Fingerprint,BUDNEY,m
Email::Outlook::Message,MVZ,m
EmbedIT::WebIT,DEVMORFO,m
Embedix::DB,BEPPU,m
Embedix::ECD,BEPPU,m
Apache::Embperl,GRICHTER,m
HTML::Embperl,GRICHTER,m
Encode,DANKOGAI,m
Encode::Arabic,SMRZ,m
Encode::Detect,JGMYERS,m
Encode::Detect::Detector,JGMYERS,m
Encode::HanConvert,AUTRIJUS,m
Encode::HanDetect,AUTRIJUS,m
Encode::Korean,YOU,m
Encode::Registry,MHOSKEN,m
Encode::UTR22,MHOSKEN,m
Erlang::Parser,ANNELI,m
Error,SHLOMIF,m
Error::TryCatch,NILSONSFJ,m
Etk,LEVIATHAN,m
Eve,ZINIGOR,m
Event,JPRIT,m
Event::RPC,JRED,m
Event::Stats,JPRIT,m
Evented::Object,COOPER,m
Excel::Template,RKINYON,m
Exception::Class,DROLSKY,m
Exception::Cxx,JPRIT,m
Expect,RGIERSIG,m
ExtJS::AutoForm::Moose,MET,m
ExtUtils::AutoInstall,INGY,m
ExtUtils::F77,CHM,m
ExtUtils::Manifest,BINGOS,m
ExtUtils::ModuleMaker,JKEENAN,m
FCGI,MSTROUT,m
FCGI::Spawn,VERESC,m
FFI,GAAL,m
FFI::Library,GAAL,m
FLV::AudioExtractor,FVOX,m
FSA::Engine,ICYDEE,m
FTDI,MVOELKER,m
FTDI::D2XX,MVOELKER,m
Fatal::Exception,DEXTER,m
Fennec,EXODIST,m
Fierce::Parser,JABRA,m
File::AptFetch,WHYNOT,m
File::Attributes,JROCKWAY,m
File::Cache,DCLINTON,m
File::Copy::Link,RMBARKER,m
File::Spec::Link,RMBARKER,m
File::FcntlLock,JTT,m
File::Find::Rule,RCLAMP,m
File::Flock,MUIR,m
File::Flock::Tiny,ZWON,m
File::Format::RIFF,STURM,m
File::KeePass,RHANDOM,m
File::KeePass::Agent,RHANDOM,m
File::LinearRaid,ROSULEK,m
File::Listing,GAAS,m
File::Locate,VPARSEVAL,m
File::Mirror,JWU,m
File::Monitor,ANDYA,m
File::NFSLock,BBB,m
File::Properties,WOHL,m
File::Rename,RMBARKER,m
File::RoundRobin,HOREA,m
File::Slurp,URI,m
File::Stat::Moose,DEXTER,m
File::Sync,CEVANS,m
File::Tabular,DAMI,m
File::Temp,TJENNESS,m
File::Touch,NWETTERS,m
File::Util,TOMMY,m
File::Which,PEREINAR,m
File::Wildcard,IVORW,m
FileHandle::Unget,DCOPPIT,m
Filesys::DiskUsage,COG,m
Filesys::SmbClient,ALIAN,m
Filter::cpp,PMQS,m
Filter::decrypt,PMQS,m
Filter::exec,PMQS,m
Filter::sh,PMQS,m
Filter::tee,PMQS,m
Filter::Util::Call,PMQS,m
Filter::Util::Exec,PMQS,m
Filter::Crypto,SHAY,m
Filter::Heredoc,BKRON,m
Filter::NumberLines,BEATNIK,m
Filter::Template,RCAPUTO,m
Finance::Bank::AU::StGeorge,IWADE,m
Finance::Bank::Bankwest,LXP,m
Finance::Bank::Commerzbank,TOBI,m
Finance::Bank::CreateCard,RMCKAY,m
Finance::Bank::IE::PermanentTSB,PALLOTRON,m
Finance::Bank::JP::Mizuho,NGS,m
Finance::Bank::LaPoste,PIXEL,m
Finance::Bank::NL::CLIEOP03,ZEBAZ,m
Finance::Bank::NetBranch,KULP,m
Finance::Bank::SentinelBenefits::Csv401kConverter,DSOLIMANO,m
Finance::Bank::Wachovia,JGARVIN,m
Finance::OFX,BFOZ,m
Finance::QuoteDB,ECOCODE,m
Finance::QuoteHist,MSISK,m
Finnigan,SELKOVJR,m
Flickr::Upload,CPB,m
Font::AFM,GAAS,m
Font::TTF,MHOSKEN,m
Font::Fret,MHOSKEN,m
Food::ECodes,MANWAR,m
Form::Factory,HANENKAMP,m
Form::Processor::Model::DBIC,GSHANK,m
Form::Sensible,JAYK,m
Fortran::F90Namelist,WDOBLER,m
Fortran::Format,ITUB,m
Math::Fraction,KEVINA,m
FrameMaker::MifTree,RST,m
FrameNet::WordNet::Detour,REITER,m
Freecell::App,SHIRHA,m
FreezeThaw,ILYAZ,m
Frost,ERNESTO,m
Fukurama::Class,TOBIWAN,m
Functional::Utility,BELDEN,m
Furl::Cookies,KAZUNORI,m
Fuse::Class,TOSHIFJW,m
Fuse::Filesys::Virtual,TOSHIFJW,m
Fuse::PerlSSH::FS,CLIPLAND,m
Fuse::TagLayer,CLIPLAND,m
FusqlFS,KSTEPME,m
Fwctl,FRAJULAC,m
IPChains::PortFW,FRAJULAC,m
GD::Barcode,KWITKNR,m
GD::Graph::smootharea,ANDREI,m
GD::Graph::smoothlines,ANDREI,m
GD::Graph3d,WADG,m
GD::SecurityImage,BURAK,m
GD::Graph,MVERB,m
GDS2,SCHUMACK,m
GD::Text,MVERB,m
GIFgraph,MVERB,m
GMail::IMAPD,KRS,m
GPS::Poi,EGERMAN,m
GSM::Gnokii,DFORSI,m
GStreamer,TSCH,m
GTop,MJH,m
Games::AlphaBeta,STIG,m
Games::Sequential,STIG,m
Games::Bingo,JONASBN,m
Games::Cards,AKARGER,m
Games::Cards::Pair,MANWAR,m
Games::Crosswords,XERN,m
Games::Dice::Loaded,MGOULD,m
Games::Domino,MANWAR,m
Games::DungeonMaker,ACDALTON,m
Games::Go::Cinderblock,ZPMORGAN,m
Games::Lacuna::Client,HALKEYE,m
Games::Maze,JGAMBLE,m
Games::Object,PSTEWART,m
Games::Quake::Stats,MBEEBE,m
Games::QuizTaker,TSTANLEY,m
Games::RailRoad,JQUELIN,m
Games::Ratings,BARTOLIN,m
Games::Risk,JQUELIN,m
Games::SGF,WHITCODE,m
Games::SGF::Go,WHITCODE,m
Games::SGF::Util,WHITCODE,m
Games::TicTacToe,MANWAR,m
Games::Tournament::BlackJack,PJACOBS,m
Games::Tournament::RoundRobin,DRBEAN,m
Games::Tournament::Swiss,DRBEAN,m
Games::Worms,AVIF,m
Gapp,JHALLOCK,m
Gapp::App,JHALLOCK,m
GappX::FormTraits,JHALLOCK,m
GappX::NoticeBox,JHALLOCK,m
GappX::SSNEntry,JHALLOCK,m
Gearman::XS,KROW,m
Gedcom,PJCJ,m
Genealogy::Gedcom,RSAVAGE,m
Genealogy::Gedcom::Date,RSAVAGE,m
Genezzo,JCOHEN,m
Genezzo::Contrib::Clustered,EROLLINS,m
Geo::Calc::XS,ASP,m
Geo::Coder::Canada,JETTRA,m
Geo::Coder::HostIP,DODGER,m
Geo::Coordinates::OSGB,TOBY,m
Geo::CountryFlags,MIKER,m
Geo::OGR,AJOLMA,m
Geo::OSR,AJOLMA,m
Geo::GeoNames,BDFOY,m
Geo::Gpx,ANDYA,m
Geo::Hashing,ZIGDON,m
Geo::Heatmap,HOFSTETTM,m
Geo::HelmertTransform,MYSOCIETY,m
Geo::IP,MAXMIND,m
Geo::METAR,KOOS,m
Geo::OSM::MapFeatures,BOBKARE,m
Geo::ShapeFile,SLAFFAN,m
MailBot,RHNELSON,m
Getargs::Long,DCOPPIT,m
Getopt::Attribute,MARCEL,m
Getopt::Declare,DCONWAY,m
Getopt::Flex,RPKELLY,m
Getopt::Long,JV,m
Getopt::Mixed,CJM,m
Gimp::ScriptFu::Client,ASTEWART,m
Git::Demo,RCL,m
Git::DescribeVersion,RWSTAUNER,m
Git::Github::Creator,BDFOY,m
Git::Hooks,GNUSTAVO,m
Git::Repository,BOOK,m
Gnome2,TSCH,m
Gnome2::VFS,TSCH,m
Google::Fusion,RCL,m
Google::OAuth,TQISJIM,m
Google::ProtocolBuffers,GARIEV,m
Google::Spreadsheet::Agent,DMLOND,m
Graph,JHI,m
Graph::Layout::Aesthetic,THOSPEL,m
Graph::Reader,NEILB,m
Graph::Reader::XML,NEILB,m
Graph::Writer,NEILB,m
Graph::Writer::daVinci,NEILB,m
Graph::Writer::Dot,NEILB,m
Graph::Writer::VCG,NEILB,m
Graph::Writer::XML,NEILB,m
Graph::Similarity,SHOHEIK,m
GraphViz,LBROCARD,m
GraphViz2,RSAVAGE,m
GraphViz2::Marpa,RSAVAGE,m
GraphViz2::Marpa::PathUtils,RSAVAGE,m
Graphics::Asymptote,DCMERTENS,m
Graphics::ColorNames,RRWO,m
Graphics::Libplot,JLAPEYRE,m
Grid::Request,VICTORF,m
Gtk2,TSCH,m
Gtk2::Ex::CellRendererWrappedText,JHALLOCK,m
Gtk2::Ex::DBI,DKASAK,m
Gtk2::Ex::Datasheet::DBI,DKASAK,m
Gtk2::Ex::FormFactory,JRED,m
Gtk2::Ex::WYSIWYG,MDBGRIZ,m
Gtk2::MozEmbed,TSCH,m
Gtk2::Net::LDAP::Widgets,ADAMOWSKI,m
Guile,SAMTREGAR,m
HPSG::Mason,CJCOLLIER,m
HTML::Base,GAND,m
HTML::Barcode,MSTRAT,m
HTML::Bricks,PETERMCD,m
HTML::CalendarMonth,MSISK,m
HTML::DOM,SPROUT,m
HTML::DataTable,NICWOLFF,m
HTML::Diff,EZRAKILTY,m
HTML::EP,JWIED,m
HTML::EasyTags,DUNCAND,m
HTML::EditableTable,AESPEN,m
HTML::ElementGlob,MSISK,m
HTML::ElementRaw,MSISK,m
HTML::ElementSuper,MSISK,m
HTML::ElementTable,MSISK,m
HTML::Feature,MIKI,m
HTML::FillInForm,TJMATHER,m
HTML::Form::XSS,DUMB,m
HTML::FormHandler,GSHANK,m
HTML::FromANSI,AUTRIJUS,m
HTML::FromMail,MARKOV,m
HTML::FromText,CWEST,m
HTML::GenToc,RUBYKAT,m
HTML::HTML5::Parser,TOBYINK,m
HTML::Index,AWRIGLEY,m
HTML::LinkChanger,SERGEYCHE,m
HTML::ListScraper,VBAR,m
HTML::LoL,BOBG,m
HTML::Macro,SOKOLOV,m
HTML::Packer,NEVESENIN,m
HTML::ParseBrowser,DODGER,m
HTML::Parser::Simple,RSAVAGE,m
HTML::Processor,PSCHNELL,m
HTML::Restrict,OALDERS,m
HTML::StickyForms,PMH,m
HTML::Stream,DSTAAL,m
HTML::TableExtract,MSISK,m
HTML::TagHelper,MAMATUX,m
HTML::TagParser,KAWASAKI,m
HTML::Template::Compiled,TINITA,m
HTML::Template::Parser,SHMORIMO,m
HTML::Tested::JavaScript,BOSU,m
HTML::Element,JFEARN,m
HTML::WebMake,JMASON,m
HTML::WikiConverter::DokuWikiFCK,TURNERMM,m
HTML::YUI3::Menu,RSAVAGE,m
HTTP::AppServer,KITOMER,m
HTTP::BrowserDetect,LHS,m
HTTP::Client,LINC,m
HTTP::CookieMonster,OALDERS,m
HTTP::Cookies::Mozilla,ADOPTME,m
HTTP::DAVServer,JLAWRENC,m
HTTP::Daemon::Threaded,DARNOLD,m
HTTP::Date,LWWWP,m
HTTP::Exception,TMUELLER,m
HTTP::GetImages,LGODDARD,m
HTTP::Link::Parser,TOBYINK,m
HTTP::Lint,LKUNDRAK,m
HTTP::Headers,LWWWP,m
HTTP::Message,LWWWP,m
HTTP::Request,LWWWP,m
HTTP::Request::Common,LWWWP,m
HTTP::Response,LWWWP,m
HTTP::Status,LWWWP,m
HTTP::Negotiate,LWWWP,m
HTTP::Proxy,BOOK,m
HTTP::Recorder,LEIRA,m
HTTP::Request::FromLog,MIKI,m
HTTP::Response::Switch,LXP,m
HTTP::Server::EV,NYAKNYAN,m
HTTP::Server::EV::Buffer,NYAKNYAN,m
HTTP::Server::EV::BufTie,NYAKNYAN,m
HTTP::Server::Simple::Dispatched,FRODWITH,m
HTTP::WebTest,ILYAM,m
HTTP::Webdav,GRICHTER,m
HTTPD::Authen,LDS,m
HTTPD::GroupAdmin,LDS,m
HTTPD::UserAdmin,LDS,m
HackaMol,DEMIAN,m
Hadoop::Streaming,SPAZM,m
Ham::APRS::FAP,HESSU,m
Ham::Fldigi,MEH,m
Handel,CLACO,m
Hardware::PortScanner,GALILEO,m
Hash::Case,MARKOV,m
Hash::WithDefaults,JENDA,m
Heap,JMM,m
Heap::Binary,JMM,m
Heap::Binomial,JMM,m
Heap::Elem,JMM,m
Heap::Elem::Num,JMM,m
Heap::Elem::NumRev,JMM,m
Heap::Elem::Ref,JMM,m
Heap::Elem::RefRev,JMM,m
Heap::Elem::Str,JMM,m
Heap::Elem::StrRev,JMM,m
Heap::Fibonacci,JMM,m
Heap::Simple,THOSPEL,m
Heap::Simple::Perl,THOSPEL,m
Heap::Simple::XS,THOSPEL,m
Heimdal::Kadm5,LEIFJ,m
Hg,RTWARD,m
Hg,RTWARD,m
Hook::Filter,ERWAN,m
Hypatia,JACKMANEY,m
HyperWave::CSP,GOSSAMER,m
IO::Callback,PUBNOOP,m
Compress::Zlib,PMQS,m
IO::Default,NWIGER,m
IO::Dir::Recursive,FLORA,m
IO::Event,MUIR,m
IO::File::Lockable,MAKOTO,m
IO::Journal,FREQUENCY,m
IO::LCDproc,JCMULLER,m
IO::Lambda,KARASIK,m
IO::Multiplex,BBB,m
IO::Socket::CLI,ASHLEYW,m
IO::Socket::DNS,BBB,m
IO::Stream::MatrixSSL,POWERMAN,m
IO::String,GAAS,m
IO::Stty,RGIERSIG,m
IO::AtomicFile,DSKOLL,m
IO::Lines,DSKOLL,m
IO::Scalar,DSKOLL,m
IO::ScalarArray,DSKOLL,m
IO::Stringy,DSKOLL,m
IO::Wrap,DSKOLL,m
IO::WrapTie,DSKOLL,m
IP::CountryFlag,MANWAR,m
IP::Info,MANWAR,m
IPC::AnyEvent::Gearman,KHS,m
IPC::Cache,DCLINTON,m
IPC::Concurrency::DBI,AUBERTG,m
IPC::DirQueue,JMASON,m
IPC::Door,ASARIH,m
IPC::LDT,JSTENZEL,m
IPC::Locker,WSNYDER,m
IPC::Mmap,DARNOLD,m
IPC::Open3::Callback,LTHEISEN,m
IPC::Run,TODDR,m
IPC::Shareable,BSUGARS,m
IPC::SysV,MHX,m
IPChains,JESSICAQ,m
IPDR,SHAMROCK,m
IPTables::Log,MEH,m
IUP,KMX,m
IkiWiki::Plugin::syntax,VMORAL,m
Image::BoxModel,MBP,m
Image::DS9,DJERIUS,m
File::RandomAccess,EXIFTOOL,m
Image::ExifTool,EXIFTOOL,m
Image::GeoTIFF::Tiled,BLAKEW,m
Image::Magick::Chart,RSAVAGE,m
Image::Magick::PolyText,RSAVAGE,m
Image::MetaData::JPEG,BETTELLI,m
Image::PNG,BKB,m
Image::ParseGIF,BENL,m
Image::WMF,TCOX,m
Image::WordCloud,BHANN,m
Image::WorldMap,LBROCARD,m
Inferno::RegMgr,POWERMAN,m
Inline,INGY,m
Inline::ASM,NEILW,m
Inline::C,INGY,m
Inline::CPR,INGY,m
Inline::Files,DCONWAY,m
Inline::Guile,SAMTREGAR,m
Inline::Struct,NEILW,m
Inline::Tcl,RRS,m
InterMine::Item,INTERMINE,m
InterMine::Model,INTERMINE,m
ex::implements,PDCAWLEY,m
ex::interface,PDCAWLEY,m
Date::Interval,KTORP,m
Iterator,ROODE,m
Iterator::BreakOn,VMORAL,m
Iterator::DBI,ROODE,m
Iterator::Diamond,JV,m
Iterator::IO,ROODE,m
Iterator::Misc,ROODE,m
Iterator::Util,ROODE,m
JavaScript::Engine,SPROUT,m
JE,SPROUT,m
JIRA::Client,GNUSTAVO,m
JQuery,PETERG,m
JSON::RPC2,POWERMAN,m
JSON::Tiny,DAVIDO,m
Jabber::Connection,QMACRO,m
Jabber::RPC,QMACRO,m
Jaipo,BLUET,m
Java,METZZO,m
Java::Build,PHILCROW,m
Java::JCR,HANENKAMP,m
Java::JVM::Classfile,LBROCARD,m
JavaScript::Framework::jQuery,CONVERTER,m
JavaScript::Packer,NEVESENIN,m
JavaScript::Sprockets,LEEDO,m
Jcode,DANKOGAI,m
Jorge,PORTA,m
Kelp,MINIMAL,m
Kephra,LICHTKIND,m
KeywordsSpider,KATKAD,m
KeywordsSpider::Core,KATKAD,m
Konstrukt,TWITTEK,m
Authen::Krb4,JHORWITZ,m
Authen::Krb5,JHORWITZ,m
Kwiki,INGY,m
Kx,MARKPF,m
LEGO::NXT,COLLINS,m
LIMS::Controller,CJONES,m
LMDB_File,SORTIZ,m
LWP::Authen::Negotiate,AGROLMS,m
LWP::MediaTypes,LWWWP,m
LWP::Protocol::http::SocketUnix,FLORA,m
LWP::Protocol::socks,SCR,m
URI::virtual,RPAUL,m
LWP::UserAgent::Mockable,MMORGAN,m
LWPx::ParanoidAgent,BRADFITZ,m
LaTeX::Driver,EINHVERFR,m
LaTeX::Encode,EINHVERFR,m
LaTeX::Table,LIMAONE,m
Language::Basic,AKARGER,m
Language::Befunge,JQUELIN,m
Language::MinCaml,NEJIGANE,m
Language::Prolog::Types,SALVA,m
Language::Prolog::Yaswi,SALVA,m
Language::XSB,SALVA,m
Language::Zcode,AKARGER,m
Language::l33t,YANICK,m
Lazy::Bool,PACMAN,m
Lemonldap::Cluster::Status,EGERMAN,m
Lemonldap::Config::Parameters,EGERMAN,m
Lemonldap::Handlers::CAS,EGERMAN,m
Lemonldap::Handlers::Generic,EGERMAN,m
Lemonldap::Portal::Script,EGERMAN,m
Lemonldap::Portal::Standard,EGERMAN,m
Lemonolap::Log4lemon,EGERMAN,m
LibTracker::Client,GERA,m
Lingua::AlignmentSet,PLAMBERT,m
Lingua::Alphabet::Phonetic,MTHURN,m
Lingua::Boolean,DOHERTY,m
Lingua::Conjunction,RRWO,m
Lingua::Deva,GLTS,m
Lingua::EN::AddressParse,KIMRYAN,m
Lingua::EN::NameCase,ADOPTME,m
Lingua::EN::NameParse,KIMRYAN,m
Lingua::EN::Syllable,GREGFAST,m
Lingua::FR::Ladl,INGRIF,m
Lingua::GA::Gramadoir,SCANNELL,m
Lingua::Identify,AMBS,m
Lingua::JA::Romanize::Japanese,KAWASAKI,m
Lingua::Jspell,AMBS,m
Lingua::LO::Romanize,JOKKE,m
Lingua::Lid,ALINKE,m
Lingua::PT::Conjugate,EGROSS,m
Lingua::PT::UnConjugate,EGROSS,m
Lingua::PT::Nums2Words,COG,m
Lingua::GL::Stemmer,XERN,m
Lingua::PT::Stemmer,XERN,m
Lingua::Slavic::Numbers,TEODOR,m
Lingua::Stem,SNOWHARE,m
Lingua::Stem::Ru,ALGDR,m
Lingua::Translit,ALINKE,m
Lingua::Treebank,KAHN,m
Lingua::Verbnet,VKH,m
Lingua::ZH::CEDICT,CRENZ,m
Lingua::ZH::HanDetect,AUTRIJUS,m
Lingua::ZH::Keywords,AUTRIJUS,m
Lingua::ZH::PinyinConvert,XERN,m
Lingua::ZH::Romanize::Pinyin,KAWASAKI,m
Lingua::ZH::Summarize,AUTRIJUS,m
Lingua::ZH::Toke,AUTRIJUS,m
Lingua::ZH::Wrap,AUTRIJUS,m
Linux::Bootloader,BRYCE,m
Linux::Cpuinfo,JSTOWE,m
Linux::DVB::DVBT,SDPRICE,m
Linux::DVB::DVBT::Advert,SDPRICE,m
Linux::Distribution::Packages,JUDITH,m
Linux::Ethtool,DJCOLLINS,m
Linux::Fuser,JSTOWE,m
Linux::Inotify,TWERNER,m
Linux::Input::Wiimote,TEMPALTE,m
Linux::LVM,CKERNER,m
Linux::Prctl,SEVEAS,m
Linux::Svgalib,JSTOWE,m
Linux::Sysfs,FLORA,m
List::BinarySearch,DAVIDO,m
List::Compare,JKEENAN,m
LittleORM,EUGENEK,m
Locale::Country,SBECK,m
Locale::Currency,SBECK,m
Locale::Language,SBECK,m
Locale::MakePhrase,MATHEW,m
Locale::Maketext::Fuzzy,AUTRIJUS,m
Locale::Maketext::Gettext,IMACAT,m
Locale::Maketext::Utils,DMUEY,m
Locale::PO,KEN,m
Locale::SubCountry,KIMRYAN,m
Locale::VersionedMessages,SBECK,m
Log::Agent,MROGASKI,m
Log::Agent::Logger,MROGASKI,m
Log::Agent::Rotate,MROGASKI,m
Log::Any::Adapter::Handler,GVL,m
Log::Declare,CHGOVUK,m
Log::Dispatch,DROLSKY,m
Log::Dispatch::MacGrowl,RYOCHIN,m
Log::Dispatch::TkText,DDUMONT,m
Log::Dispatch::ToTk,DDUMONT,m
Log::Dispatch::Win32EventLog,ABERGMAN,m
Log::Fine,CFUHRMAN,m
Log::Handler,BLOONIX,m
Log::Handler::Plugin::DBI,RSAVAGE,m
Log::Message::JSON,DOZZIE,m
Log::Report,MARKOV,m
Log::Syslog::Abstract,DONEILL,m
Log::Unrotate,MMCLERIC,m
CGI::LogCarp,MIKEKING,m
Logfile::EPrints,TIMBRODY,m
Lorem,JHALLOCK,m
Lucy,KARMAN,m
Luka,TPG,m
MARC::Errorchecks,EIJABB,m
MARC::Loader,REIVEUNE,m
MARC::Record::Stats,CRUSOE,m
MARC::Transform,REIVEUNE,m
MCDB_File,GSTRAUSS,m
MColPro,WJIAN,m
MIDI,CONKLIN,m
MIME::Base64,GAAS,m
MIME::QuotedPrint,GAAS,m
MIME::EcoEncode,MURATAYA,m
MIME::Lite,YVES,m
MIME::Lite::HTML,ALIAN,m
MIME::Lite::TT,HORIUCHI,m
MIME::Types,MARKOV,m
MIME::Decoder,DSKOLL,m
MIME::Entity,DSKOLL,m
MIME::Head,DSKOLL,m
MIME::Parser,DSKOLL,m
MIME::Words,DSKOLL,m
MLDBM,GSAR,m
MLDBM::Sync,CHAMAS,m
MODS::Record,HOCHSTEN,m
MP3::Daemon,BEPPU,m
MP3::ID3Lib,LBROCARD,m
MP3::Info,DANIEL,m
MP3::M3U::Parser,BURAK,m
MP3::Mplib,VPARSEVAL,m
MPEG::Audio::Frame,NUFFIN,m
MPEG::MP3Play,JRED,m
MQSeries,MQSERIES,m
MRS::Client,TULSOFT,m
Mac::AppleScript::Glue,JLABOVITZ,m
Mac::Apps::Anarchie,CNANDOR,m
Mac::Apps::MacPGP,CNANDOR,m
Mac::Apps::PBar,CNANDOR,m
Mac::AppleEvents,CNANDOR,m
Mac::Carbon,CNANDOR,m
Mac::Components,CNANDOR,m
Mac::Files,CNANDOR,m
Mac::Gestalt,CNANDOR,m
Mac::Memory,CNANDOR,m
Mac::MoreFiles,CNANDOR,m
Mac::Notification,CNANDOR,m
Mac::OSA,CNANDOR,m
Mac::Processes,CNANDOR,m
Mac::Resources,CNANDOR,m
Mac::Sound,CNANDOR,m
Mac::Speech,CNANDOR,m
Mac::Types,CNANDOR,m
Mac::Comm::OT_PPP,CNANDOR,m
Mac::Finder::DSStore,WIML,m
Mac::Glue,CNANDOR,m
Mac::Macbinary,MIYAGAWA,m
Mac::OSA::Simple,CNANDOR,m
Mac::PropertyList,BDFOY,m
Mac::PropertyList::SAX,KULP,m
Mac::iTunes,ADOPTME,m
Mac::iTunes::Library::XML,DINOMITE,m
Mail::Audit,RJBS,m
Mail::Box,MARKOV,m
Mail::CheckUser,ILYAM,m
Mail::DKIM,JASLONG,m
Mail::DMARC,MSIMERSON,m
Mail::DMARC::opendmarc,SHARI,m
Mail::Decency,UKAUTZ,m
Mail::DeliveryStatus::BounceParser,RJBS,m
Mail::DomainKeys,ANTHONYU,m
Mail::GPG,JRED,m
Mail::GnuPG,DDB,m
Mail::IMAPClient,MARKOV,m
Mail::Mbox::MessageParser,DCOPPIT,m
Mail::MboxParser,VPARSEVAL,m
Mail::OpenDKIM,NHORNE,m
Mail::Postfix::Postdrop,PMAKHOLM,m
Mail::Procmailrc,SCOTTW,m
Mail::SPF::Query,FREESIDE,m
Mail::SRS,SHEVEK,m
Mail::SendGrid,NEILB,m
Mail::Sender,JENDA,m
Mail::Toaster,MSIMERSON,m
Mail::Client::Yahoo,JOHNSCA,m
Mail::Folder,KJOHNSON,m
Mail::Address,MARKOV,m
Mail::Cap,MARKOV,m
Mail::Field,MARKOV,m
Mail::Header,MARKOV,m
Mail::Internet,MARKOV,m
Mail::Mailer,MARKOV,m
Mail::Send,MARKOV,m
Mail::Util,MARKOV,m
MangoX::Queue,IANKENT,m
Map::Tube,MANWAR,m
Maplat,CAVAC,m
Mariachi,RCLAMP,m
Marpa::R2,JKEGL,m
MarpaX::Database::Terminfo,JDDPAUSE,m
MarpaX::Languages::C::AST,JDDPAUSE,m
MarpaX::Languages::ECMAScript::AST,JDDPAUSE,m
MasonX::Maypole,DAVEBAIRD,m
MasonX::Resolver::PAR,MRAMBERG,m
Math::Base::Convert,MIKER,m
Math::BigInt::GMP,TELS,m
Math::BigInt::Pari,TELS,m
Math::Calc::Units,SFINK,m
Math::Cephes,SHLOMIF,m
Math::Expr,HAKANARDO,m
Math::FastGF2,DMALONE,m
Math::Fractal::DLA,ARCOLF,m
Math::Interpolator,ZEFRAM,m
Math::MPFR,SISYPHUS,m
Math::Macopt,TOM,m
Math::ModInt,MHASCH,m
Math::Pari,ILYAZ,m
Math::Polygon,MARKOV,m
Math::Polynomial,MHASCH,m
Math::Primality,LETO,m
Math::Prime::Util,DANAJ,m
Math::Project3D,SMUELLER,m
Math::RPN,OWEN,m
Math::Random,GROMMEL,m
Math::Random::MT,AMS,m
Math::Random::MT::Auto,JDHEDDEN,m
Math::Random::MT::Auto::Range,JDHEDDEN,m
Math::Random::MT::Perl,JFREEMAN,m
Math::SparseMatrix,JMAHESH,m
Math::SparseVector,JMAHESH,m
Math::StochasticProcess,SILASMONK,m
Math::Symbolic,SMUELLER,m
Math::Symbolic::Custom::CCompiler,SMUELLER,m
Math::Symbolic::Custom::Pattern,SMUELLER,m
Math::Symbolic::Custom::Transformation,SMUELLER,m
Maypole::Plugin::Authorization,DJH,m
Mecom,HVALVERDE,m
MediaWiki::DumpFile,TRIDDLE,m
MegaDistro,DBUCHMAN,m
Memcached::Server,CINDY,m
Memoize,MJD,m
Message::Passing::Filter::Regexp,CHENRYN,m
Messaging::Message,LCONS,m
Metadata::Base,DJBECKETT,m
Metadata::IAFA,DJBECKETT,m
Metadata::SOIF,DJBECKETT,m
MetasploitExpress::Parser,JABRA,m
Mobile::Ads,TCHATZI,m
Mobile::UserAgent,CMANLEY,m
ModPerl::ParamBuilder,FWILES,m
Module::Build,KWILLIAMS,m
Module::Install,INGY,m
Module::Install::ORLite2Pod,SDOWIDEIT,m
Module::Metadata::CoreList,RSAVAGE,m
Module::Optional,IVORW,m
Module::Release,BDFOY,m
Module::Reload,JPRIT,m
Module::ScanDeps,AUTRIJUS,m
Module::Signature,AUDREYT,m
Module::Use,JSMITH,m
Mojar,NICZERO,m
MojoX::JSON::RPC,HENRYYKT,m
MojoX::Redis,UNDEF,m
MojoX::Transaction::WebSocket76,DIONYS,m
MojoX::UserAgent,ACAJOU,m
Mojolicious::Plugin::AdvancedMod,GRISHKOV,m
Mojolicious::Plugin::DeCSRF,SYSADM,m
Mojolicious::Plugin::DeCSRF,SYSADM,m
Mojolicious::Plugin::KossyValidator,FUKAI,m
Mojolicious::Plugin::StaticCompressor,MUGIFLY,m
Mojolicious::Plugin::Vparam,RSHADOW,m
Mon::Client,TROCKIJ,m
Mon::SNMP,TROCKIJ,m
MonetDB::CLI::MapiLib,SGOELDNER,m
MonetDB::CLI::MapiPP,SGOELDNER,m
MongoDB::Async,NYAKNYAN,m
MongoDBx::Tiny,TOONA,m
MongoX,DOGGY,m
Monit::HTTP,PALLOTRON,m
Monitis,YKO,m
MooX,GETTY,m
MooseX::Locked,CHIPS,m
MooseX::MultiInitArg,FRODWITH,m
MooseX::Role::Pluggable,GENEHACK,m
MooseX::ShortCut::BuildInstance,JANDREW,m
MooseX::SingletonMethod,DRAEGTUN,m
MooseX::Types::Path::Class,THEPLER,m
Mozilla::Mechanize::GUITester,BOSU,m
Muck,MIKE,m
Muldis::Rosetta,DUNCAND,m
MySQL::Admin,LZE,m
MySQL::Diff,ASPIERS,m
MySQL::Replication,ALFIE,m
MySQL::Sandbox,GMAX,m
MySQL::Util,GRAVATTJ,m
Myco,SOMMERB,m
Net::NISPlus,RIK,m
NLP::GATE,JOHANNP,m
NLP::Service,VIKAS,m
NNML::Server,ULPFR,m
News::NNTPClient,RVA,m
NNexus,DGINEV,m
Nagios::Passive,DATA,m
NcFTPd::Log::Parse,SHAW,m
Nes,NES,m
Net::AIM,ARYEH,m
Net::AIM::TOC,FRIFFIN,m
Net::APNS::Feedback,AUFFLICK,m
Net::APNS::Persistent,AUFFLICK,m
Net::AS2,SWONG,m
Net::Amazon::Glacier,GBARCO,m
Net::Amazon::MechanicalTurk,MTURK,m
Net::Amazon::Signature::V4,GBARCO,m
Net::BEEP::Lite,DBLACKA,m
Net::BGP,SSCHECK,m
Net::BitTorrent,SANKO,m
Net::Bluetooth,IGUTHRIE,m
Net::Bonjour,CHLIGE,m
Net::CDP,MCHAPMAN,m
Net::CIDR::Lookup,MBETHKE,m
Net::CIDR::Lookup::Tie,MBETHKE,m
Net::Chat::Daemon,SFINK,m
Net::CyanChat,KIRSLE,m
Net::CyanChat::Server,KIRSLE,m
Net::DAS,TDWINTER,m
Net::DBus,DANBERR,m
Net::DHCP::Info,JHTHORSEN,m
Net::DNS,NLNETLABS,m
Net::DNS::Check,LLT,m
Net::DNS::Dynamic::Proxyserver,MAJA,m
Net::DNS::SEC,NLNETLABS,m
Net::DNS::TestNS,NLNETLABS,m
Net::DNS::Zone::Parser,NLNETLABS,m
Net::DNS::ZoneParse,BTIETZ,m
Net::DNSServer,BBB,m
Net::DRI,PMEVZEK,m
Net::DSML,CHARDEN,m
Net::Daemon,MNOONING,m
Net::Daemon::SSL,MKUL,m
Net::Defensio,BCHOATE,m
Net::DirectConnect,PRO,m
Net::Domain::Info,APLA,m
Net::DownloadMirror,KNORR,m
Net::EMI::Client,SCHAFFTER,m
Net::EPP::Client,GBROWN,m
Net::FRN,FROLLER,m
Net::FreeDB,DSHULTZ,m
Net::GPSD,MRDVT,m
Net::Gnutella,IWADE,m
Net::Google,ASCOPE,m
Net::Google::PicasaWeb,HANENKAMP,m
Net::Hotline,JSIRACUSA,m
Net::ICAP,CORLISS,m
Net::ICQ,JMUHLICH,m
Net::IDN::Encode,CFAERBER,m
Net::IMP,SULLR,m
Net::INET6Glue,SULLR,m
Net::IP::RangeCompare,AKALINUX,m
Net::IPAddress::Util,PWBENNETT,m
Net::IPTrie,CVICENTE,m
Net::Icecast2,REV,m
Net::Ident,JPC,m
Net::Inspect,SULLR,m
Net::Interface,REHSACK,m
Net::Jabber,DAPATRICK,m
Net::LDAPapi,MISHIKAL,m
Net::LibLO,NJH,m
Net::MRIM,AAU,m
Net::MessageBus,HOREA,m
Net::MirrorDir,KNORR,m
Net::NIS,ESM,m
Net::OpenID::Server::Standalone,VERESC,m
Net::OpenSRS,IVAN,m
Net::OpenSoundControl,CRENZ,m
Net::P0f,SAPER,m
Net::PH,GBARR,m
Net::PSYC,AGOE,m
Net::Packet,GOMOR,m
Net::Pager,ROOTLEVEL,m
Net::Pcap,PLISTER,m
Net::Pcap::Reassemble,JRAFTERY,m
Net::PcapWriter,SULLR,m
Net::Peep,STARKY,m
Net::Ping::External,COLINM,m
Net::Proxy,BOOK,m
Net::RTP,NJH,m
Net::Route,TEQUETER,m
Net::Rovio,IVANTIS,m
Net::SAP,NJH,m
Net::SCP,IVAN,m
Net::SDP,NJH,m
Net::SFTP,DBROBINS,m
Net::SFTP::SftpServer,SIMM,m
Net::SIP,SULLR,m
Net::SMPP,SAMPO,m
Net::SMS,ROOTLEVEL,m
Net::SMS::ASPSMS,SUPCIK,m
Net::SMS::ArxMobile,COSIMO,m
Net::SMS::Cellsynt,OLOF,m
Net::SMS::Genie,AWRIGLEY,m
Net::SMS::Web,AWRIGLEY,m
Net::SMS::WorldText,SEVEAS,m
Net::SNMP,DTOWN,m
Net::SNMP::Interfaces,JSTOWE,m
Net::SNPP,TOBEYA,m
Net::SPOCP,LEIFJ,m
Net::SSLGlue,SULLR,m
Net::SSLeay,FLORA,m
Net::STOMP::Client,LCONS,m
Net::TL1,STEVENH,m
Net::Telnet::Cisco,JOSHUA,m
Net::Telnet::Wrapper,MWALLRAF,m
Net::UKDomain::Nominet::Automaton,CLIFFORDJ,m
Net::UploadMirror,KNORR,m
Net::VNC,LBROCARD,m
Net::WWD,BALESHI,m
Net::WebSocket::Server,TOPAZ,m
Net::Whois::Gateway::Client,GRAYKOT,m
Net::Whois::Gateway::Server,GRAYKOT,m
Net::Wire10,DUBEX,m
Net::XWhois,AUGIE,m
Net::Z3950,MIRK,m
Net::ZooKeeper,CDARROCH,m
Net::Gen,SPIDB,m
Net::Inet,SPIDB,m
Net::TCP,SPIDB,m
Net::UDP,SPIDB,m
Net::iTMS,TSIBLEY,m
Net::uFTP,STRZELEC,m
NetApp,WPMOORE,m
NetServer::Portal,JPRIT,m
Netscape::Bookmarks,BDFOY,m
Netscape::Cache,SREZIC,m
Net::ACAP,KJOHNSON,m
Net::IMAP,KJOHNSON,m
Net::xAP,KJOHNSON,m
News::Article,AGIERTH,m
News::GnusFilter,JOESUF,m
News::Scan,GBACON,m
NexposeSimpleXML::Parser,JABRA,m
Nikto::Parser,JABRA,m
Nmap::Scanner,MAXSCHUBE,m
NoSQL::PL2SQL,TQISJIM,m
Nokia::File::NFB,RPRICE,m
No::Dato,GAAS,m
No::KontoNr,GAAS,m
No::PersonNr,GAAS,m
No::Sort,GAAS,m
Number::Phone::IE,DERMOT,m
ODF::lpOD,JMGDOC,m
OLE::PropertySet,MSCHWARTZ,m
OLE::Storage,MSCHWARTZ,m
OLE::Storage_Lite,JMCNAMARA,m
OODoc,MARKOV,m
ORM,AKIMOV,m
OS2::UPM,ILYAZ,m
OSPF::LSDB,BLUHM,m
Kernel::Modules::AdminESCL,ROHITBASU,m
Kernel::System::Escalation,ROHITBASU,m
OWL::Simple::Parser,TOMASZ,m
Object::Exercise,LEMBARK,m
Object::Hybrid,METADOO,m
Object::InsideOut,JDHEDDEN,m
Object::Iterate,BDFOY,m
Object::Trampoline,LEMBARK,m
Object::Transaction,MUIR,m
OnlineJudge::Progra,ILV,m
OpenGL,BFREE,m
OpenGL::Image,BFREE,m
Games::Quest3D,OVERMARS,m
OpenGL::QEng,OVERMARS,m
OpenGL::Shader,BFREE,m
OpenID::Login,REALHOLGI,m
OpenOffice::OODoc,JMGDOC,m
OpenOffice::UNO,MBARBON,m
Oracle::Trace,RFOLEY,m
Oraperl,DBIML,m
PAR::WebStart,ISHIGAKI,m
PAUSE::Permissions,NEILB,m
PDF::Boxer,LECSTOR,m
PDF::Report,AORR,m
PDF::Report::Table,DAVEBAR,m
PDF::ReportWriter,DKASAK,m
PDF::Reuse,CNIGHS,m
PDF::Reuse::Tutorial,CNIGHS,m
PDF::Table,RHYTHMAN,m
PDF::TableX,PAPKALA,m
PDFLib::PPS,MONTUORI,m
PDL::Finance::TA,VIKAS,m
PDL::Graphics::Gnuplot,ZOWIE,m
PDL::Graphics::PLplot,DHUNT,m
PDL::Graphics::Simple,ZOWIE,m
PDL::NDBin,EBAUDREZ,m
PDL::Stats,MAGGIEXYZ,m
Language::PGForth,PETERGAL,m
PHP,KARASIK,m
PHP::Include,AMBS,m
PHP::Interpreter,DWHEELER,m
PHP::Session,MIYAGAWA,m
PICA::Record,VOJ,m
PIX::Walker,LIFO,m
POD2::RU,MISHIN,m
POE,RCAPUTO,m
POE::Kernel,RCAPUTO,m
POE::Session,RCAPUTO,m
POE::API::Hooks,SUNGO,m
POE::API::Peek,BINGOS,m
POE::Component::Client::FTP,MCHING,m
POE::Component::Client::HTTP,RCAPUTO,m
POE::Component::Client::MPD,JQUELIN,m
POE::Component::Client::Ping,RCAPUTO,m
POE::Component::Client::TCPMulti,TAG,m
POE::Component::Client::Traceroute,AHOYING,m
POE::Component::Client::UserAgent,RCAPUTO,m
POE::Component::ControlPort,XANTUS,m
POE::Component::DebugShell,XANTUS,m
POE::Component::IRC,BINGOS,m
POE::Component::OSCAR,DMCC,m
POE::Component::Pcap,FLETCH,m
POE::Component::Proxy::TCP,ANDYPUR,m
POE::Component::RSS,SUNGO,m
POE::Component::Resolver,RCAPUTO,m
POE::Component::SSLify::NonBlock,PRIVI,m
POE::Component::Client::SOAP,AIMASS,m
POE::Component::Server::AsyncEndpoint,AIMASS,m
POE::Component::Server::HTTP,ABERGMAN,m
POE::Component::Server::Syslog,BINGOS,m
POE::Component::SubWrapper,SUNGO,m
POE::Component::TFTPd,JHTHORSEN,m
POE::Loop::Glib,MARTIJN,m
POE::Loop::Wx,MIKE,m
POOF,BMILLARES,m
PPI::HTML::CodeFolder,DARNOLD,m
PPM,MURRAY,m
XML::PPD,MURRAY,m
PPM::Make,ISHIGAKI,m
PPresenter,MARKOV,m
Padre::Plugin::PHP,SEWI,m
Padre::Plugin::WebGUI,PDONELAN,m
PagSeguro::API,DVINCI,m
Palm::Magellan::NavCompanion,ADOPTME,m
Palm::SMS,LOLO,m
Panda::Date,SYBER,m
Panda::URI,SYBER,m
Paper::Specs,JONALLEN,m
Parallel::ForkManager,DLUX,m
Parallel::Pvm,DLECONTE,m
LWP::Parallel,MARCLANG,m
Params::Dry,NEO,m
Params::Profile,MICHIEL,m
Params::Validate,DROLSKY,m
Paranoid,CORLISS,m
Parse::ABNF,BJOERN,m
Parse::DMIDecode,NICOLAW,m
Parse::DNS::Zone,OLOF,m
Parse::Dia::SQL,AFF,m
Parse::FSM,PSCUST,m
Parse::FixedLength,DOUGW,m
Parse::Gnaw,GSLONDON,m
Parse::Highlife,KITOMER,m
Parse::Liberty,EGA,m
Parse::MediaWikiDump,TRIDDLE,m
Parse::Readelf,DORNER,m
Parse::RecDescent,DCONWAY,m
Parse::Stallion,ARTHUR,m
Parse::Vipar,SFINK,m
Parse::Yapp,FDESAR,m
Parse::Lex,PVERD,m
Perl::Critic::Itch,MARCELO,m
Perl::Critic::Storable,MATTD,m
Perl::Critic::Swift,ELLIOTJS,m
RPM,RJRAY,m
RPM::Constants,RJRAY,m
RPM::Database,RJRAY,m
RPM::Header,RJRAY,m
Perl6::Doc,LICHTKIND,m
Perl6::Pod,ZAG,m
PV,AGUL,m
Perlipse,JAE,m
Perlmazing,ZARABOZO,m
Persevere::Client,WIRELESSD,m
Persistent::Base,DWINTERS,m
PgSQL,GTHYNI,m
Physics::Unit,KLORTHO,m
RPC::PlClient,MNOONING,m
RPC::PlServer,MNOONING,m
Plack::Middleware::Auth::BrowserID,BOLILA,m
Plack::Middleware::ExtDirect,TOKAREV,m
Plack::ResponseHelper,KOMAROV,m
Plucene::Plugin::Analyzer::MetaphoneAnalyzer,ALANSZ,m
Pod::Autopod,AHERNIT,m
Pod::Checker,MAREKR,m
Pod::DocBook,MBERENDS,m
Pod::Index,ITUB,m
Pod::Manual,YANICK,m
Pod::POM,ABW,m
Pod::PP,RAM,m
Pod::Parser,MAREKR,m
Pod::Select,MAREKR,m
Pod::PerlPoint,JSTENZEL,m
Pod::Perldoc::ToToc,BDFOY,m
Pod::Plainer,RMBARKER,m
Pod::Readme,RRWO,m
Pod::Simple,ARANDAL,m
Pod::Tree,SWMCD,m
Pod::Usage,MAREKR,m
Pod::Weaver::Section::MooseConsumes,MILSO,m
Pod::Weaver::Section::MooseExtends,MILSO,m
Pod::XML,MSERGEANT,m
Pod::Hlp,PVHP,m
Pogo,SEYN,m
Bio::Polloc,LRR,m
Polycom::App::Push,ZBLAIR,m
Polycom::Contact::Directory,ZBLAIR,m
Polyglot,BDFOY,m
Pony::Object,BUGOV,m
Positron,BDEUTSCH,m
PostScript::Document,SHAWNPW,m
PostScript::Elements,SHAWNPW,m
PostScript::Metrics,SHAWNPW,m
PostScript::TextBlock,SHAWNPW,m
PostScript::File,CJM,m
PostScript::BasicTypesetter,JV,m
PostScript::Font,JV,m
PostScript::FontInfo,JV,m
PostScript::FontMetrics,JV,m
PostScript::ISOLatin1Encoding,JV,m
PostScript::PrinterFontMetrics,JV,m
PostScript::PseudoISO,JV,m
PostScript::Resources,JV,m
PostScript::StandardEncoding,JV,m
PostScript::Graph::Bar,CJM,m
PostScript::Graph::Key,CJM,m
PostScript::Graph::Paper,CJM,m
PostScript::Graph::Style,CJM,m
PostScript::Graph::XY,CJM,m
Postgres,DAVEHOLL,m
Prima,KARASIK,m
Proc::Background,BZAJAC,m
Proc::Exists,BRIANSKI,m
Proc::ProcessTable,DURIST,m
Project::Euler,LESPEA,m
Project::Gantt,AWESTHOLM,m
Provision::Unix,MSIMERSON,m
QDBM_File,YAMATO,m
QWizard,HARDAKER,m
QualysGuard::Request,PDEVLIN,m
Quantum::Entanglement,AJGOUGH,m
Quantum::Superpositions,LEMBARK,m
Queue::DBI,AUBERTG,m
R::YapRI,BOMBARELY,m
R3,SCHOEN,m
RADIUS::Dictionary,CHRMASTO,m
RADIUS::Packet,CHRMASTO,m
RDF::Core,PAVELH,m
RDF::RDFa::Parser,TOBYINK,m
RDF::Service,JONAS,m
RDF::Trine,GWILLIAMS,m
REST::Neo4p,MAJENSEN,m
RPC::ExtDirect,TOKAREV,m
RPC::Object,JWU,m
RPC::Simple,CEDWARDS,m
RPG::Traveller::Person,COWDAWG,m
RPG::Traveller::Starmap,COWDAWG,m
RPM::Header::PurePerl,TLBDK,m
RPSL,LMC,m
RRDTool::Creator,JACQUELIN,m
RSH::Logging,MLUKER,m
RT::Client::REST,DMITRI,m
RT::Extension::PushoverNotify,RINGERC,m
RT::Extension::QueueWizard,KEVINR,m
RT::Extension::SMSNotify,RINGERC,m
RT::Extension::ShiftPlanning,RINGERC,m
RTx::RightsMatrix,HTCHAPMAN,m
Range::Object,TOKAREV,m
Ravenel,RDIETRICH,m
Rc,JPRIT,m
Apache::RedirectDBI,SANDERSON,m
RedisDB,ZWON,m
RDF::Redland,DJBECKETT,m
Reflex,RCAPUTO,m
Regexp::Assemble,DLAND,m
Regexp::Common,ABIGAIL,m
Regexp::Extended,CRUNCHIE,m
Regexp::MultiLanguage,ROBWALKER,m
Regexp::RegGrp,NEVESENIN,m
Religion,KJALB,m
RenderMan,GMLEWIS,m
Replication::Recall::Client,AGUL,m
Replication::Recall::Server,AGUL,m
Riak::Light,WEBORAMA,m
RiveScript,KIRSLE,m
RobotC::Wrapper,CRLYJEP,m
Robotics,JCLINE,m
Games::Roguelike::Area,EARONESTY,m
Games::Roguelike::Console,EARONESTY,m
Games::Roguelike::World,EARONESTY,m
Rose::DB,JSIRACUSA,m
Rose::DB::Object,JSIRACUSA,m
Rose::DBx::Bouquet,RSAVAGE,m
Rose::DBx::Object::MakeMethods::EKSBlowfish,HRUPP,m
Rose::DateTime,JSIRACUSA,m
Rose::HTML::Objects,JSIRACUSA,m
Rose::Object,JSIRACUSA,m
Run::Parts,ABE,m
SAS::Parser,MLF,m
SCGI,VIPERCODE,m
SGML::Parser::OpenSP,BJOERN,m
SIAM,SSINYAGIN,m
SIL::Shoe,MHOSKEN,m
SNMP::Monitor,JWIED,m
SNMP::NPAdmin,BOZZIO,m
SNMP::Util,WMARQ,m
SOAP::Clean,STODGHIL,m
SOAP::Data::ComplexType,RYBSKEJ,m
SOAP::Transport::HTTP::Nginx,CYGA,m
XMLRPC::Transport::HTTP::Nginx,CYGA,m
SOAP::WSDL,MKUTTER,m
SOAP::WSDL::Server::Plack,AST,m
SOAP::XML::Client,LLAP,m
SOAPjr,ROBMAN,m
Net::SOCKS,SCOOPER,m
SQL::Abstract,MSTROUT,m
SQL::Abstract::Limit,DAVEBAIRD,m
SQL::Bibliosoph,MATIU,m
SQL::Exec,MATHIAS,m
SQL::Generator,MUENALAN,m
SQL::QueryBuilder::Pretty,RIVOTTI,m
SQL::Snippet,PRL,m
SQL::Statement,REHSACK,m
SQL::Template,NICEPERL,m
SQL::Translator,JROBINSON,m
SQL::Yapp,THEILING,m
SVG,RONAN,m
SVG::DOM,RONAN,m
SVG::Element,RONAN,m
SVG::XML,RONAN,m
SVG::Graph,ALLENDAY,m
SVG::Rasterize,LGEHLEN,m
SVN::Deploy,TOMK,m
SVN::Dumpfile,MSCHARRER,m
SVN::Hooks,GNUSTAVO,m
SVN::TeamTools::Indexer,MARKLEEUW,m
SWIFT::Factory::Tag::Tag20,BIKER,m
SWIFT::Factory::Tag::Tag21,BIKER,m
SWIFT::Factory::Tag::Tag30,BIKER,m
SWIFT::Factory::Tag::Tag30T,BIKER,m
SWIFT::Factory::Tag::Tag30V,BIKER,m
Safe::Hole,SEYN,m
Sailthru::Client,SAILTHRU,m
Salesforce,BAYSIDE,m
Salvation,GFILATOV,m
Samba::LDAP,GHENRY,m
Scalar::Properties,MARCEL,m
Schedule::Pluggable,EDWARDSON,m
DBIx::SystemCatalog,MILSO,m
Hints,MILSO,m
Script::Toolbox,ECKARDT,m
Search::Binary,XAERXESS,m
Search::Fulltext,LAYSAKURA,m
Search::InvertedIndex,SNOWHARE,m
Search::Lemur,PKAEDING,m
SemanticWeb::OAI::ORE,SIMEON,m
Sendmail::M4::Mail8,CML,m
Sendmail::M4::Mail8,CML,m
Sendmail::M4::Utils,CML,m
Sepia,SEANO,m
Set::Array,RSAVAGE,m
Set::Bag,JHI,m
Set::FA,MROGASKI,m
Set::Hash,RSAVAGE,m
Set::Infinite,FGLOCK,m
Set::NestedGroups,ABARCLAY,m
Set::Relation,DUNCAND,m
Set::String,RSAVAGE,m
Set::Toolkit,SIRROBERT,m
Shatterproof,SGOVIND,m
Siebel::Integration::Com,BOYDLE,m
Siebel::Srvrmgr,ARFREITAS,m
Silly::Werder,CXREG,m
SimpleCDB,BENL,m
Simulation::Automate,WVDB,m
Simulation::DiscreteEvent,ZWON,m
Slackware::Slackget,DUPUISARN,m
Slauth,IKLUFT,m
Slay::Makefile,NODINE,m
Sledge::Template::Xslate,KARUPA,m
Soar::Production,NGLENN,m
Soar::Production::Parser,NGLENN,m
Soar::WM,NGLENN,m
Data::Sofu,MALUKU,m
Solaris::Kstat,ABURLISON,m
Solaris::MapDev,ABURLISON,m
Solaris::ProcessContract,DWARREN,m
Solaris::Procfs,JNOLAN,m
Solaris::SMF,BRAD,m
Solr,GARAFOLA,m
Solstice,PMICHAUD,m
Sort::Fields,JNH,m
Sort::Key,SALVA,m
Sort::Versions,NEILB,m
Speech::Recognizer::SPX,DJHD,m
Spreadsheet::ParseExcel,JMCNAMARA,m
Squid::Guard,LUX,m
Sslscan::Parser,JABRA,m
Statistics::ANOVA,RGARTON,m
Statistics::ChiSquare,DCANTRELL,m
Statistics::Descriptive,SHLOMIF,m
Statistics::LTU,TOMFA,m
Statistics::MVA,DSTH,m
Statistics::MaxEntropy,TERDOEST,m
Statistics::Robust,WMSZELIGA,m
Statistics::RserveClient,DJUNKIM,m
Statistics::PointEstimation,YUNFANG,m
Statistics::TTest,YUNFANG,m
Storm,JHALLOCK,m
Geo::Storm_Tracker,CARPENTER,m
String::Multibyte,SADAHIRO,m
String::Parity,WINKO,m
String::Random,STEVE,m
String::Replace,MATHIAS,m
String::Strip,BPOWERS,m
Su,LOTTZ,m
Sub::ArgShortcut,ARISTOTLE,m
Sub::Assert,SMUELLER,m
Sub::Chain,RWSTAUNER,m
Sub::Curry,LODIN,m
Sub::DeferredPartial,SGOELDNER,m
Sub::Lambda,TOYVO,m
Sub::Private,PMAKHOLM,m
SugarSync::API,ADOPTME,m
Sun::Solaris::Exacct,SUNCPAN,m
Sybase::Simple,MEWP,m
Sybase::Xfer,SPRAGST,m
Symbol::Approx::Sub,DAVECROSS,m
Symbol::Table,GSLONDON,m
Syntax::Highlight::Perl6,AZAWAWI,m
Syntax::Highlight::Universal,MISHOO,m
Sys::AlarmCall,ABH,m
Sys::CPU,MKODERER,m
Sys::Statistics::Linux,BLOONIX,m
Sys::Utmp,JSTOWE,m
SyslogScan::SendmailLine,RHNELSON,m
SyslogScan::SyslogEntry,RHNELSON,m
SystemC::Netlist,WSNYDER,m
SystemC::Parser,WSNYDER,m
Sysync,MJFLICK,m
TAP::Harness::JUnit,LKUNDRAK,m
TAP::Runner,REV,m
TCP::Rebuild,EDECA,m
TL1ng,SSCAFFIDI,m
Taint,PHOENIX,m
Tapper,TAPPER,m
Task::Catalyst::Tutorial,JROCKWAY,m
Task::OTRS,ROLFS,m
TaskForest,ENOOR,m
TeX::AutoTeX,TSCHWAND,m
TeX::DVI,JANPAZ,m
TeX::Hyphen,JANPAZ,m
Teamspeak,MALETIN,m
Tempest,EVANK,m
Template::Alloy,RHANDOM,m
Template::Like,ASKADNA,m
Template::Multilingual,CHOLET,m
Template::Mustache,PVANDE,m
Template::Plugin::Latex,EINHVERFR,m
Template::Plugin::MARC,JCAMINS,m
Template::Plugin::TwoStage,ALEXK,m
Template::Recall,GILAD,m
Template::Reverse,KHS,m
Tenjin,IDOPEREL,m
Term::ANSIScreen,AUTRIJUS,m
Term::Clui,PJB,m
Term::Gnuplot,ILYAZ,m
Term::Prompt,ALLENS,m
Term::Query,AKSTE,m
Term::ReadLine::Gnu,HAYASHI,m
Term::ReadLine::Perl,ILYAZ,m
Term::RouterCLI,JORDAN,m
Term::Screen,JSTOWE,m
Term::ScreenColor,RUITTENB,m
Term::Shell::Pluggable,PIN,m
Term::Shelly,DPAVLIN,m
Term::Size,TIMPX,m
Term::Slang,DANIEL,m
Term::Spark,LURST,m
Term::Visual,LUNARTEAR,m
Term::Vspark,LURST,m
Test::AskAnExpert,TRIZOR,m
Test::Assert,DEXTER,m
Test::CPANpm,CRAKRJACK,m
Test::CallFlow,KORPIQ,m
Test::Collectd::Plugins,FAXMODEM,m
Test::Config::System,IANK,m
Test::Data,BDFOY,m
Test::DistManifest,JAWNSY,m
Test::Dynamic,TURNSTEP,m
Test::EasyMock,KISEKI,m
Test::Exception,EXODIST,m
Test::FIT,INGY,m
Test::FITesque,KONOBI,m
Test::File,BDFOY,m
Test::File::Find::Rule,FABPOT,m
Test::Filesystem,FUZZ,m
Test::Fixme,EVDB,m
Test::Functional,ERIK,m
Test::Given,ROVJUVANO,m
Test::Glade,NMUELLER,m
Test::HTML::Spelling,RRWO,m
Test::ISBN,BDFOY,m
Test::LectroTest,TMOERTEL,m
Test::Litmus,ZLIPTON,m
Test::Mail,SKUD,m
Test::Mini,PVANDE,m
Test::Mini::Unit,PVANDE,m
Test::Mock::Mango,JGREGORY,m
Test::MockClass,JJORDAN,m
Test::MockCommand,KYZ,m
Test::Module::Used,TSUCCHI,m
Test::MultiFork,MUIR,m
Test::Net::LDAP,MAHIRO,m
Test::PDL,EBAUDREZ,m
Test::Pcuke,CRUSOE,m
Test::PerlTidy,EVDB,m
Test::Ping,XSAWYERX,m
Test::Pockito,EXUSSUM,m
Test::Pod,DWHEELER,m
Test::Pod::Snippets,YANICK,m
Test::Portability::Files,SAPER,m
Test::Prereq,BDFOY,m
Test::Regression,SILASMONK,m
Test::Signature,AUTRIJUS,m
Test::Spelling,JESSE,m
Test::Syntax::Aggregate,ZWON,m
Test::Trap,EBHANSSEN,m
Test::Unit::Lite,DEXTER,m
Test::Valgrind,VPIT,m
Test::Version,XENO,m
Test::WWW::Selenium::Catalyst,JROCKWAY,m
Test::WWW::Selenium::More,KABLAMO,m
Test::WWW::Selenium::Sencha,PLYTLE,m
Test::Weaken,KRYDE,m
Test::YAML::Valid,JROCKWAY,m
Text::AI::CRM114,MSCHUETT,m
Text::ASCIIMathML,NODINE,m
Text::ASCIITable,LUNATIC,m
Text::Affixes,KAPPA,m
Text::Balanced,DMANURA,m
Text::BibTeX,AMBS,m
Text::Bidi,KAMENSKY,m
Text::CSV,MAKAMAKA,m
Text::CSV::Easy,WETERS,m
Text::CSV::Track,JKUTEJ,m
Text::CSV::Unicode,RMBARKER,m
Text::Conversation,RCAPUTO,m
Text::DHCPLeases,CVICENTE,m
Text::Diff3,TOCIYUKI,m
Text::Editor::Easy,GROMMIER,m
Text::EtText,JMASON,m
Text::FindLinks,ZOUL,m
Text::Flowchart::Script,XERN,m
Text::Format,GABOR,m
Text::German,ULPFR,m
Text::Graphics,SFARRELL,m
Text::Merge,SHARRIS,m
Text::MetaText,ABW,m
Text::Morse,BENNIE,m
Text::MultiMarkdown,KULP,m
Text::Ngram,AMBS,m
Text::Orientation,XERN,m
Text::ProcessMap,BADKINS,m
Text::Query,JONJ,m
Text::Refer,ERYQ,m
Text::Restructured,NODINE,m
Text::Same,KIM,m
Text::Scan,IWOODHEAD,m
Text::Scraper,MCEWAN,m
Text::Similarity,JASONM,m
Text::Table,ANNO,m
Text::Tabs,MUIR,m
Text::Wrap,MUIR,m
Text::Template,MJD,m
Text::Template::Simple,BURAK,m
Text::TemplateLite,BKATZUNG,m
Text::Twiddler,DMUEY,m
Text::Xslate::Syntax::HTMLTemplate,SHMORIMO,m
Text::vCard,LLAP,m
Thesaurus,DROLSKY,m
Thread::Apartment,DARNOLD,m
Thread::Barrier,MJP,m
Thread::Pool,ELIZABETH,m
Thread::Task::Concurrent,JWB,m
Tibco::Rv,STURM,m
Tie::Cache::LRU,MSCHWERN,m
Tie::CharArray,ILTZU,m
Tie::DBI,LDS,m
Tie::RDBM,LDS,m
Tie::DB_FileLock,JMV,m
Tie::Discovery,AUDREYT,m
Tie::File::AsHash,CANGELL,m
Tie::Array::CustomStorage,DDUMONT,m
Tie::Hash::CustomStorage,DDUMONT,m
Tie::Hash::Stack,REHSACK,m
Tie::IxHash,GSAR,m
Tie::Judy,BHOLZMAN,m
Tie::LDAP,TAIY,m
Tie::LLHash,KWILLIAMS,m
Tie::Persistent,RGIERSIG,m
Tie::REHash,METADOO,m
Tie::RangeHash,RRWO,m
Tie::RegexpHash,RRWO,m
Tie::Scalar::Timeout,MARCEL,m
Tie::SecureHash,DCONWAY,m
Tie::Simple,HANENKAMP,m
Tie::SortHash,CTWETEN,m
Tie::Util,SPROUT,m
Tie::iCal,BSDZ,m
Time::Elapsed,BURAK,m
Time::CTime,MUIR,m
Time::DaysInMonth,MUIR,m
Time::JulianDay,MUIR,m
Time::ParseDate,MUIR,m
Time::Timezone,MUIR,m
Time::Period,PRYAN,m
Time::Seconds,RJBS,m
Time::TAI64,JOVAL,m
Time::UTC,ZEFRAM,m
Time::Warp,JPRIT,m
Tivoli,RHASE,m
Tk::FcyEntry,ASB,m
Tk::Calculator::RPN::HP,LUSOL,m
Tk::Canvas::Draw,JCNORTON,m
Tk::Chart,DJIBEL,m
Tk::ContextHelp,SREZIC,m
Tk::Date,SREZIC,m
Tk::DoubleClick,JCNORTON,m
Tk::FileEntry,ASB,m
Tk::FlatCheckbox,SREZIC,m
Tk::Cloth,SREZIC,m
Tk::FireButton,SREZIC,m
Tk::NumEntry,SREZIC,m
Tk::TFrame,SREZIC,m
Tk::GraphItems,LAMPRECHT,m
Tk::GraphViz,JGS,m
Tk::HistEntry,SREZIC,m
Tk::JComboBox,RCSEEGE,m
Tk::ObjEditor,DDUMONT,m
Tk::ObjEditorDialog,DDUMONT,m
Tk::Pgplot,CPHIL,m
Tk::Splashscreen,LUSOL,m
Tk::Stderr,KVAIL,m
Tk::StyleDialog,KIRSLE,m
Tk::TableMatrix,CERNEY,m
Tk::Task,KVAIL,m
Tk::TextANSIColor,TJENNESS,m
Tk::TextVi,JSTROM,m
Tk::Wizard,LGODDARD,m
Tk::Wizard::Choices,LGODDARD,m
Tk::Wizard::FileSystem,LGODDARD,m
Tk::Wizard::Installer,LGODDARD,m
Tk::Wizard::Installer::Win32,LGODDARD,m
Tk::Workspace,RKIES,m
Tk::Carp,JOHNSCA,m
TomTom::WEBFLEET::Connect,IMIOSGA,m
Tree,RSAVAGE,m
Tree::DAG_Node,RSAVAGE,m
Tree::DAG_Node::Persist,RSAVAGE,m
Tree::Fat,JPRIT,m
Tree::Node,RRWO,m
Tree::Predicate,MARSHALL,m
Tree::Range,ONEGRAY,m
Triggermail,SGERSTEN,m
UAV::Pilot,TMURRAY,m
UDDI,GAAS,m
UML::Sequence,PHILCROW,m
UMLS::Interface,BTMCINNES,m
UMLS::SenseRelate,BTMCINNES,m
UMLS::Similarity,BTMCINNES,m
URI::Find,MSCHWERN,m
URI::OpenURL,TIMBRODY,m
USB::Descriptor,BFOZ,m
Ubigraph,GAOU,m
Unicode::EastAsianWidth,AUTRIJUS,m
Unicode::Japanese,MIKAGE,m
Unicode::String,GAAS,m
Unicode::Stringprep,CFAERBER,m
Unix::ConfigFile,SSNODGRA,m
Unix::Lsof,MARCB,m
Unix::Processors,WSNYDER,m
Unix::SavedIDs,DMARTIN,m
Mail::Identity,MARKOV,m
User::Identity,MARKOV,m
VCI,SGREEN,m
VCS::CMSynergy,RSCHUPP,m
VCS::PVCS,BMIDD,m
VKontakte::API,ASDEEVA,m
VKontakte::API::OAuth,ASDEEVA,m
VM::Dreamer,WDS,m
VM::EC2,LDS,m
VM::JiffyBox,BORISD,m
VMS::Device,DSUGAL,m
VMS::Lock,BHUGHES,m
VMS::Mail,DNORTH,m
VMS::Monitor,DSUGAL,m
VMS::Priv,DSUGAL,m
VMS::Process,DSUGAL,m
VMS::Queue,DSUGAL,m
VMS::System,DSUGAL,m
VMS::Persona,DSUGAL,m
VRML,HPALM,m
VRML::Base,HPALM,m
VRML::Color,HPALM,m
VRML::VRML1,HPALM,m
VRML::VRML2,HPALM,m
VarGuard,CINDY,m
Variable::Alias,BRENTDAX,m
VendorAPI::2Checkout::Client,LENJAFFE,m
Verilog::CodeGen,WVDB,m
Verilog::Language,WSNYDER,m
Verilog::Parser,WSNYDER,m
Verilog::SigParser,WSNYDER,m
Video::CPL,CSR,m
Video::FFmpeg,RANDOMMAN,m
Vim::Debug,KABLAMO,m
Visio,AAKHTER,m
VoiceXML::Client,PDEEGAN,m
Voldemort,EXUSSUM,m
W3C::LinkChecker,SCOP,m
WDDX,ZOMBITHRD,m
WL,LKUNDRAK,m
WML::Card,MALVARO,m
WML::Deck,MALVARO,m
WWW::Adblock,EDECA,m
WWW::Anonymouse,GRAY,m
WWW::Asg,FUKATA,m
WWW::BigDoor,ALEXD,m
WWW::Bing::Search,EDAM,m
WWW::Cache::Google,MIYAGAWA,m
WWW::Codeguard,RYEDDULA,m
WWW::Deezer,KABANOID,m
WWW::DomainTools,DBARTLE,m
WWW::EchoNest,BSORAHAN,m
WWW::Formspring,WORR,m
WWW::FreeProxy,SWINED,m
WWW::Geni,ERINSPICE,m
WWW::GoDaddy::REST,DBARTLE,m
WWW::Google::APIDiscovery,MANWAR,m
WWW::Google::CustomSearch,MANWAR,m
WWW::Google::DistanceMatrix,MANWAR,m
WWW::Google::PageSpeedOnline,MANWAR,m
WWW::Google::Places,MANWAR,m
WWW::Google::URLShortener,MANWAR,m
WWW::ImageSpool,CRAKRJACK,m
WWW::Link,MIKEDLR,m
WWW::Live::Auth,JENKINSON,m
WWW::Live::Contacts,JENKINSON,m
WWW::LogicBoxes,DRZIGMAN,m
WWW::Mechanize,JESSE,m
WWW::Mechanize::Pliant,REITMAN,m
WWW::Metaweb,HDS,m
WWW::Monitor,YARON,m
WWW::Moviepilot,FWIE,m
WWW::Newzbin,CHRISN,m
WWW::NicoVideo,HIRATA,m
WWW::OReillyMedia::Store,MANWAR,m
WWW::Ohloh::API,YANICK,m
WWW::Opentracker::Stats,HOVENKO,m
WWW::PDAScraper,CODYP,m
WWW::Patent::Page,ANONWB,m
WWW::Pipeline,HOWARS,m
WWW::PivotalTracker,JHELWIG,m
WWW::Postini,PGUZIS,m
WWW::Robot,NEILB,m
WWW::SMS,EIM,m
WWW::Scraper::ISBN,ASCHAMP,m
WWW::Scraper::Wikipedia::ISO3166,RSAVAGE,m
WWW::Scripter,SPROUT,m
WWW::Scripter::Plugin::Ajax,SPROUT,m
WWW::Scripter::Plugin::JavaScript,SPROUT,m
WWW::Scroogle,SCHLUMPF,m
WWW::Search,MTHURN,m
WWW::Search::Ebay,MTHURN,m
WWW::Search::PharmGKB,ARUN,m
WWW::Search::Scrape,QSUN,m
WWW::Search::Torrentz,MGV,m
WWW::Search::Yahoo,MTHURN,m
WWW::Shopify,ADAMDH,m
WWW::SlideShare,ASHISHM,m
WWW::Slides,POLETTIX,m
WWW::Splunk,LKUNDRAK,m
WWW::StatsMix,MANWAR,m
WWW::StreamSend,KABANOID,m
WWW::Sucksub::Divxstation,TFOUCART,m
WWW::TMDB::API,MARIAB,m
WWW::Twitpic,DIEGOK,m
WWW::Wappalyzer,NALOBIN,m
WWW::WolframAlpha,YEGG,m
WWW::WuFoo,PLYTLE,m
WWW::Wunderground::API,NEBULOUS,m
WWW::Yandex::PDD,ALUCK,m
WWW::Yandex::TIC,BASHLOV,m
WWW::phpBB,STEFANT,m
Wais,ULPFR,m
Weather::TW,DRYMAN,m
Web::Sitemap,MBOGDANOV,m
WebAPI::DBIC,TIMB,m
WebFS::FileCopy,BZAJAC,m
WebService::Affiliate,CAGAO,m
WebService::Amazon::Route53,ODYNIEC,m
WebService::Belkin::WeMo::Device,ERICBLUE,m
WebService::Belkin::WeMo::Discover,ERICBLUE,m
WebService::CRUST,HESCHONG,m
WebService::Cath::FuncNet,ISILLITOE,m
WebService::Cmis,NUDDLEGG,m
WebService::DataDog,JPINKHAM,m
WebService::DigitalOcean,ANDRE,m
WebService::Eulerian::Analytics,MJONDET,m
WebService::EveOnline,CHRISC,m
WebService::FC2::SpamAPI,FUJIWARA,m
WebService::FogBugz::XML,GBJK,m
WebService::FreeDB,HMERSCH,m
WebService::GData,SHIRIRU,m
WebService::Geograph::API,SDEN,m
WebService::GlucoseBuddy,CUBABIT,m
WebService::Google::Language,HMA,m
WebService::Google::Reader,GRAY,m
WebService::ISBNDB,RJRAY,m
WebService::Linode,MIKEGRB,m
WebService::Linode::DNS,MIKEGRB,m
WebService::Mappoint,CGARCIA,m
WebService::MoviePosterDB,CJK,m
WebService::MusicBrainz,BFAIST,m
WebService::NationBuilder,AANARI,m
WebService::Pandora,DEFCON,m
WebService::Qiita,YUUKI,m
WebService::SOS,JDAVIS,m
WebService::ScormCloud,LARRYL,m
WebService::Search123,CAGAO,m
WebService::TVRage,KBRANDT,m
WebService::Upcoming,GKNAUSS,m
WebService::VaultPress::Partner,SYMKAT,m
WebService::Wedata,KOYACHI,m
WebService::Wikimapia,MANWAR,m
WebService::Yelp,JDR,m
WebService::YouTube,YOSHIDA,m
WebSphere::MQTT::Client,NJH,m
Webservice::InterMine,INTERMINE,m
Webservice::InterMine::Bio,INTERMINE,m
Webservice::InterMine::Simple,INTERMINE,m
What,TPG,m
Wiki::Toolkit::Formatter::Mediawiki,DPRICE,m
Wily,SHOLDEN,m
Win32::AD::Control::DirSync,AKR,m
Win32::Clipboard,ACALPINI,m
Win32::Console,ACALPINI,m
Win32::EventLog,JDB,m
Win32::EventLog::Carp,ADOPTME,m
Win32::Exchange::Mailbox,SMANROSS,m
Win32::Exchange::SMTP::Security,SMANROSS,m
Win32::File::Summary,RPAGITSCH,m
Win32::File::VersionInfo,ALEXEYT,m
Win32::FileOp,JENDA,m
Win32::FileSystem::Watcher,ANK,m
Win32::Fonts::Info,RPAGITSCH,m
Win32::IEFavorites,ISHIGAKI,m
Win32::ChangeNotify,CJM,m
Win32::Event,CJM,m
Win32::IPC,CJM,m
Win32::Mutex,CJM,m
Win32::Semaphore,CJM,m
Win32::Internet,ACALPINI,m
Win32::MultiMedia::Joystick,THAMUS,m
Win32::MultiMedia::Mci,THAMUS,m
Win32::Net::Session,RPAGITSCH,m
Win32::NetAdmin,JDB,m
Win32::NetResource,JDB,m
Win32::ODBC,DAVEROTH,m
Win32::OLE,JDB,m
Win32::OLE::OPC,MARTINTO,m
Win32::Pipe,DAVEROTH,m
Win32::PowerPoint,ISHIGAKI,m
Win32::PrintBox,DCLARKE,m
Win32::Process,JDB,m
Win32::Process::Info,WYANT,m
Win32::Process::Perf,RPAGITSCH,m
Win32::Process::User,RPAGITSCH,m
Win32::Registry,JDB,m
Win32::Resources,FABPOT,m
Win32::SAPI5,JOUKE,m
Win32::SDDL::ACE,TOJO,m
Win32::SerialPort,BBIRTH,m
Win32API::CommPort,BBIRTH,m
Win32::ShellExt,JBNIVOIT,m
Win32::Shortcut,ACALPINI,m
Win32::Sound,ACALPINI,m
Win32::SqlServer,SOMMAR,m
Win32::SqlServer::DTS,ARFREITAS,m
Win32::TSA::Notify,THW,m
Win32::Watir,SHIMI,m
Win32::WinError,JDB,m
Win32::WindowsMedia,SHAMROCK,m
Win32::Word::Writer,JOHANL,m
Win32API::MIDI,HAYASHI,m
Win32API::Registry,TYEMQ,m
WordNet::SenseRelate::TargetWord,TPEDERSE,m
WordNet::Similarity::Visual,KOHLIS,m
Workflow,JONASBN,m
Wx::ActiveX,GMPASSOS,m
Wx::PdfDocument,MWARDELL,m
Wx::Perl::Packager,MDOOTSON,m
Wx::Perl::ProcessStream,MDOOTSON,m
X11::Lib,KENFOX,m
X11::Motif,KENFOX,m
X11::Toolkit,KENFOX,m
X11::Xbae,KENFOX,m
X11::Xpm,KENFOX,m
X11::Auth,SMCCAM,m
X11::Keysyms,SMCCAM,m
X11::Protocol,SMCCAM,m
X11::Protocol::Enhanced,BIDULOCK,m
X11::Protocol::Ext::RANDR,BIDULOCK,m
X11::Protocol::Ext::SYNC,BIDULOCK,m
X11::Protocol::Ext::XKEYBOARD,BIDULOCK,m
X500::DN,RJOOP,m
X500::RDN,RJOOP,m
X86::Disasm,BOBW,m
X86::Udis86,BOBW,m
XBRL,MGANNON,m
XML::XForms::Generator,DHAGEMAN,m
XHTML::Instrumented,GAM,m
XHTML::MediaWiki,GAM,m
XML::ASCX12,BKANEY,m
XML::AutoWriter,RBS,m
XML::Doctype,RBS,m
XML::Bare,CODECHILD,m
XML::Catalog,EBOHLMAN,m
XML::Checker,TJMATHER,m
XML::Clean,PKUBANEK,m
XML::DOM,TJMATHER,m
XML::DT,JJOAO,m
XML::DTD,WOHL,m
XML::Debian::ENetInterfaces,CHEAKO,m
XML::Directory,PCIMPRICH,m
XML::Dumper,MIKEWONG,m
XML::EP,JWIED,m
XML::Encoding,COOPERCL,m
XML::Entities,SIXTEASE,m
XML::Filter::DetectWS,TJMATHER,m
XML::Filter::Reindent,TJMATHER,m
XML::Filter::SAXT,TJMATHER,m
XML::Filter::Sort,GRANTM,m
XML::GDOME,TJMATHER,m
XML::GXML,JCARTER,m
XML::Generator,BHOLZMAN,m
XML::Grove,KMACLEOD,m
XML::Handler::Composer,TJMATHER,m
XML::Handler::PrintEvents,TJMATHER,m
XML::Handler::Trees,EBOHLMAN,m
XML::Mini,PDEEGAN,m
XML::MyXML,KARJALA,m
XML::NamespaceSupport,ZOOLEIKA,m
XML::NewsML_G2,GORTAN,m
XML::PYX,MSERGEANT,m
XML::Parser::Wrapper,DOWENS,m
XML::Pastor,AULUSOY,m
XML::QL,MSERGEANT,m
XML::Quick,ROBN,m
XML::RDB,METZZO,m
XML::RSS,SHLOMIF,m
XML::RSS::FOXSports,PEREZ,m
XML::Reader,KEICHNER,m
XML::RegExp,TJMATHER,m
XML::RelaxNG::Compact::PXB,MPG,m
XML::SAX::ExpatXS,PCIMPRICH,m
XML::STX,PCIMPRICH,m
XML::Sablotron,PAVELH,m
XML::Spew,FRIEDO,m
XML::Stream,DAPATRICK,m
XML::Element,JGOFF,m
XML::TreeBuilder,JGOFF,m
XML::TreePuller,TRIDDLE,m
XML::Twig,MIROD,m
XML::UM,TJMATHER,m
XML::Validator::Schema,SAMTREGAR,m
XML::XPath,MSERGEANT,m
XML::XQL,TJMATHER,m
XML::XSS,YANICK,m
XML::miniXQL,MSERGEANT,m
XUL::Gui,ASG,m
Xcruciate,MELONMAN,m
X11::XEvent,MARTINB,m
X11::XFontStruct,MARTINB,m
Xmldoom,DSNOPEK,m
Xmms,DOUGM,m
Xmms::Config,DOUGM,m
Xmms::Remote,DOUGM,m
YAML,INGY,m
YATT::Lite,HKOBA,m
Yote,CANID,m
Yote::WebAppServer,CANID,m
Zenoss,PATBAKER,m
Zeta,ZETA,m
arXiv,SIMEON,m
autodie,PJF,m
Business::Payroll,JAMESP,m
cPanel::SyncUtil,DMUEY,m
Conjury::C,JWOODYATT,m
Conjury::Core,JWOODYATT,m
Conjury::Stage,JWOODYATT,m
constant::lexical,SPROUT,m
Lingua::DetectCharset,JNEYSTADT,m
dTemplate,DLUX,m
DBIx::dbMan,MILSO,m
DBD::RDB,ASTILLER,m
define,GGUREVICH,m
ePortal,RUSAKOV,m
OurNet::BBSApp::Sync,CLKAO,m
enum,ZENIN,m
Apache::ePerl,RSE,m
Parse::ePerl,RSE,m
Text::TeX,ILYAZ,m
ex::caution,YVES,m
ex::constant::vars,NEILB,m
ex::override,CTWETEN,m
DB::Table,KITE,m
DB::Table::Row,KITE,m
HP200LX::DB,GGONTER,m
HP200LX::DBgui,GGONTER,m
jQuery::DataTables,TOKAR,m
JMX::Jmx4Perl,ROLAND,m
Authen::PAM::Module,BHILDRED,m
Alarm::Concurrent,JOHNSCA,m
Apache::Cookie,APML,m
Apache::Request,APML,m
Netscape::Server,BSUGARS,m
SGML::Parser,EHOOD,m
Text::English,IANPX,m
IPTables::IPv4::IPQueue,MATTK,m
RPC::ONC,JAKE,m
POEST::Server,CWEST,m
Python,GAAS,m
Python::Err,GAAS,m
Python::Object,GAAS,m
Router::LG,CHRISJ,m
Ruby::Collections,CLAIR,m
Pod::Diff,IANC,m
Pod::Sdf,IANC,m
Solaris::Contents,CHRISJ,m
Solaris::InstallDB,CHRISJ,m
Solaris::Package,CHRISJ,m
Speech::Festival,RCALEY,m
Speech::Festival::Synthesiser,RCALEY,m
Math::Business::ATR,JETTERO,m
Math::Business::BollingerBands,JETTERO,m
Math::Business::DMI,JETTERO,m
Math::Business::EMA,JETTERO,m
Math::Business::HMA,JETTERO,m
Math::Business::LaguerreFilter,JETTERO,m
Math::Business::MACD,JETTERO,m
Math::Business::ParabolicSAR,JETTERO,m
Math::Business::RSI,JETTERO,m
Math::Business::SMA,JETTERO,m
Math::Business::WMA,JETTERO,m
Sybase::BCP,MEWP,m
Sybase::CTlib,MEWP,m
Sybase::DBlib,MEWP,m
Sybase::Sybperl,MEWP,m
Text::Highlight,ICRF,m
Tk::Zinc,ZINCDEV,m
Triceps,BABKIN,m
VMS::ICC,DSUGAL,m
VMS::Misc,DSUGAL,m
VMS::User,DSUGAL,m
Net::SAML,SAMPO,m
