#!/usr/bin/perl

# use 5.010;
use strict;
use warnings;

=head1 NAME



=head1 SYNOPSIS



=head1 OPTIONS

=over 8

=cut

my @opt = <<'=back' =~ /B<--(\S+)>/g;

=item B<--dry-run|n!>

Run the from-mods-to-primeur.pl with the --dry-run option.

=item B<--help|h!>

This help

=back

=head1 DESCRIPTION

As in the previous batchfiles, converting-m-to-f-*.pl, Neil
Bowers sent me the data and I wrapped them into the script.

=cut


use FindBin;
use lib "$FindBin::Bin/../lib";
BEGIN {
    push @INC, qw(       );
}

use Dumpvalue;
use File::Basename qw(dirname);
use File::Path qw(mkpath);
use File::Spec;
use File::Temp;
use Getopt::Long;
use Pod::Usage;
use Hash::Util qw(lock_keys);

our %Opt;
lock_keys %Opt, map { /([^=|!]+)/ } @opt;
GetOptions(\%Opt,
           @opt,
          ) or pod2usage(1);
if ($Opt{help}) {
    pod2usage(0);
}
$Opt{"dry-run"} //= 0;
my @dry_run;
push @dry_run, "--dry-run" if $Opt{"dry-run"};
use Time::HiRes qw(sleep);

my $i = 0;
while (<DATA>) {
    chomp;
    my $csv = $_;
    my($m,$a,$type) = split /,/, $csv;
    die "illegal type" unless $type eq "m";
    my $t = scalar localtime;
    $i++;
    warn sprintf "(%d) %s: %s\n", $i, $t, $m;
    0 == system "/opt/perl/current/bin/perl", "-Iprivatelib", "-Ilib", "bin/from-mods-to-primeur.pl", @dry_run, $m or die "Alert: $t: Problem while running from-mods-to-primeur for '$m'";
    sleep 0.08;
}

# Local Variables:
# mode: cperl
# cperl-indent-level: 4
# End:

__END__
WebService::TheGameCrafter,COLINK,m
WWW::Trello,EDUARDOW,m
Tie::Array::Unsafe,YURY,m
Dist::Zilla::PluginBundle::DOHERTY,DOHERTY,m
Test::Include::DontRun,CCOLBOURN,m
Finance::Bank::Commonwealth,DDICK,m
Data::BinStruct,DJHD,m
Data::Normalize,KAKADU,m
MetaPage,SEMENOVF,m
Net::ZKMon,MNIKHIL,m
Haiku::StorageKit,JALOPEURA,m
Webject,SEMENOVF,m
Geo::Projection,THOSPEL,m
CiviCRM::Client::REST,WMORGAN,m
Logfile,ULPFR,m
Net::BitTorrent::Scrape,QANTINS,m
Tk::Multi,DDUMONT,m
Evented::IRC,COOPER,m
Religion::Package,GWYN,m
Math::BooleanEval,MIKO,m
Device::SerialPort::Xmodem,MITTI,m
AnyEvent::HTTPD::SendMultiHeaderPatch,CINDY,m
Text::Normalize,DMUEY,m
PQI,SIMONJ,m
Covetel,WVARGAS,m
Net::ICQ2000,SNEMAROV,m
Dancer::Serializer::MessagePack,MNIKHIL,m
Benchmark::OO,QWER,m
Crypt::WEP::Key,MANWAR,m
Solaris::Kmem,ABURLISON,m
Win32::CreateProcess,GLENSMALL,m
Getopt::Long::String,LEVENGLI,m
DBD::Recall,AGUL,m
Net::CDDB,DSTALDER,m
lib::App::Guiio,JSIMPSON,m
Convert::PKCS7,RBA,m
RTF::Reader,SARGIE,m
SOAP::Amazon::S3,KARJALA,m
WordNet::Similarity::Article,CEZHANG,m
Data::Check,KENHOLM,m
Router::Statistics,SHAMROCK,m
Perlet,ZARABOZO,m
Test::Fluentd,SATOSIN,m
Acme::Halt,JKEGL,m
File::Magic,REHSACK,m
Config::IniHash,JENDA,m
MarpaX::Languages::ECMA::AST,JDDPAUSE,m
PDA::Pilot,KJALB,m
Myspace::REST,DMITRY,m
Mail::UCEResponder,CHSTROSS,m
SQL::Builder,ZENIN,m
Panda::Util,SYBER,m
IO::SWF::Editor,SHARADA,m
LotusNotes,CCLOUTIER,m
Term::Scraper,INGY,m
GVF::Parser,SRYNOBIO,m
Filesys::mntent,TOMC,m
Algorithm::Sequitur,RNS,m
Health::Devices,OWEN,m
Math::Telecom,NICOLAW,m
WWW::Mechanize::Plugin::JavaScript,SPROUT,m
Sort::ByCompatMatrix,ICKHABOD,m
Bio::Mitomaster,MBRANDON,m
Tie::Plural::Scalar,LALLIP,m
CGI::Application::Demo,RSAVAGE,m
Parse::Syntax,SHERZODR,m
File::Searcher::Similars,SUNTONG,m
MR::AsyncHTTP,ALT,m
Win32::Share,MNIKHIL,m
Records::Split,ANKUR,m
Crypt::CKE,QUIZDOG,m
Crypt::Analysis::Frequency,CMORRIS,m
Syntax::SourceHighlight,MURPHY,m
Lingua::Collate,TBUSCH,m
Enom::Base,JAMSHAID,m
Apache::AnonProxy,MPB,m
Apache::State,RSE,m
FireEye,GNAZAREY,m
CGI::Lazy::Auth,VAYDE,m
Marpa::Any,JKEGL,m
Mojolicious::Plugin::ConfigDir,AMARSCHKE,m
Flash::SWF,SABREN,m
CPANPLUS::Dist::Mdv,JQUELIN,m
Fresco,BPETH,m
Finance::SEC::Edgar,VIKAS,m
Apache::MimeDBI,MPB,m
Fcntl::Flock,ANDERS,m
Chart::HeatMap::Simple,JINKEE,m
Getopt::Numeric,CABUTLER,m
WWW::SuperAgent,SILLYMOOS,m
WWW::NzbMatrix,OGMONSTER,m
Compress::Archimedes,NIRMA,m
Text::CSV::Transform,DEEPFRYED,m
X500::DN::Parser,RSAVAGE,m
App::PerlWatcher,DMOL,m
Crypt::ProtectedString,IDO,m
Git::Cmdr,SBLANTON,m
Log::EmbedCmd,TUSHAR,m
App::Depst,GRYPHON,m
Test::Segment,DCARVELL,m
Debian::Package::Make,HBENGEN,m
Tent::Client,FKALTER,m
Log::Any::Adapter::Term,PITCHLESS,m
XMLI,ISTERIN,m
POE::Exceptions,SUNGO,m
Tk::ImageButton,DHICKLING,m
Debug::Puke,TRUEY,m
WAP::Wbmp,SAA,m
WattsUp,ROBBAT,m
BioX::DB::SCOP,WALSHTP,m
Template::XML,ABW,m
Authen::UserVerify,TERENCEMO,m
Mojolicious::Plugin::RestAPI,ANTONIKO,m
WWW::WebPAC,AQUILINA,m
WWW::Foursquare::Simple,AQUILINA,m
App::BackupAndRestore,HOOO,m
Game::Archive::Mopaq,SEIJ,m
Spreadsheet::Excel,RRAWLINGS,m
DBIx::ScaleOut,JAMCC,m
Games::Hex,JHKIM,m
RPG::Traveller::Person::CTB1,COWDAWG,m
Marpa::PP,JKEGL,m
Parse::Log::OpenSSH::SFTP,SHAW,m
Tk::ProgressMeter,BPOWERS,m
HTTP2::Draft,SLUDIN,m
SVN::Statistics,LINMAR,m
Tk::Olwm,TKML,m
SVN::Diff,DMUEY,m
HTML::AjaxTags,KMCGRATH,m
SSLeay,EAYNG,m
Language::GolfScript,MOB,m
MailProto,HAMBSTER,m
Dumpvalue::HTML,DMUEY,m
HTTP::Response::HandlerChains,LXP,m
Audio::Cuefile::ParserPlus,JCUZELLA,m
File::quotas,CMORRIS,m
DBIx::Tiny,TECHCODE,m
TidyAndCommit,SHANTANU,m
Finance::Bank::JP::MUFG,PERFORB,m
Finance::Bank::Smile,ADOPTME,m
POE::Session::Cascading,SUNGO,m
Lingua::ES::Hyphenate,NGLENN,m
Crypt::Trillian3,CMORRIS,m
Class::Driver,CRAKRJACK,m
HTML::GUI,JCHASSLER,m
Net::Cloud,FSPEISER,m
Number::Zero,UMEYUKI,m
App::Git::HomeSync,TSTANTON,m
Marpa,JKEGL,m
HTML::Widgets::DateEntry,KENNEDYH,m
Games::Diplomacy,JAMESTHOM,m
Panda::Net::Event::Connection,SYBER,m
Math::Interval,HOLLYKING,m
Test::JUTE,METZZO,m
Splunk,PFIG,m
Audio::OpenAL,JOHNYJH,m
ERG,PHOENIXL,m
BizTalk,SIMONJ,m
ConfigReader,AMW,m
FameHLI,DAVEO,m
Glade,DMUSGR,m
Object::Mapper,EJS,m
Acme::Elsewhere,JSTOWE,m
Numbers::Base::DWIM,CMO,m
Attribute::Imports,LEMBARK,m
EB,JV,m
Catalyst::Model::IMAP,FOOLISH,m
Math::MatrixCplx,STBEY,m
Deploy,RMICHAUD,m
Mozilla::Profile,ADOPTME,m
HTML::AjaxTags::Response,KMCGRATH,m
Bool,KHAREC,m
Config::YUM,OPITZ,m
WebService::Smartling,MCOX,m
Net::Amazon::SQS,JKIM,m
Tie::FlatFile::Hash,MUMIAW,m
NNTP::Server,JOEHIL,m
Twitter::CLI,SVIEBROCK,m
Apache::PUT,SORTIZ,m
Video::M3U8,MRSLX,m
SyncSort,MAGO,m
DBIx::MSSQLReporter,RSAVAGE,m
Crypt::ChaffingAndWinnowing,ZANDET,m
Orac,ANDYDUNC,m
Wiki::Toolkit::Mediawiki,DPRICE,m
WWW::Lyrics,CORUSCATE,m
WhatsApp,DVINCI,m
DBIx::Std,DMUEY,m
Text::7Segment,MANIGREW,m
Games::Gliclo,BGARBER,m
WWW::Mail::Hotmail,HOWARD,m
Env::Transaction,CIA,m
Devel::Truth_Table,MJCARMAN,m
Linksys::Config,JTAVARES,m
Games::Traveller::UWP,RJE,m
DBIx::Class::SchemalessColumns,GAMACHE,m
Finance::FixedIncome,GRODITI,m
SLOOPS,JETEVE,m
Text::Substitute,ILTZU,m
App::pake,DVINCI,m
Crypt::SDTree,JOHANNA,m
Mail::Vacation,RFOLEY,m
App::cpansearch,CORNELIUS,m
SystemC::Vregs,WSNYDER,m
Hardware::UPS::Perl,DRULENSOT,m
Class::Trigger::Ordered,BOXPHERE,m
Apache::AuthzSSL,MPB,m
Apache::AdBlocker,MPB,m
Synergy,HENKE,m
Atlassian::Confluence,SUE,m
Mail::MH,MRG,m
Zefy,JMT,m
WWW::LacunaExpanse::Script,ICYDEE,m
Log::Dispatch::Nagios,VALDEZ,m
Blarghy,DHOSS,m
Apache::ASP::Lite,FERGUSOR,m
Interface::Param,SHAUNGUTH,m
Apache2::CloseKeepAlive,MACKENNA,m
POE::Component::MPG123,MCASHNER,m
App::Vimpl,MOSHEN,m
Math::BigIntFast,STBEY,m
Template::DBI,ABW,m
WebService::BladeCenter::OA,ENKI,m
Solaris::MIB,ABURLISON,m
Net::SSH::Perl::Timeout,AVIVSIM,m
Spread::Client,MBAILEY,m
Haiku::InterfaceKit,JALOPEURA,m
Lingua::PT,EGROSS,m
Scalar::Util::Refcount,JNIXON,m
WWW::Spider,BYTBOX,m
DBD::Altera,DSOUFLIS,m
Bio::SAGE,SCOTTZED,m
RT::Extension::CustomerGroup,RINGERC,m
Mail::Maildir,ZEROALTI,m
WWW::eBridge,PERLPROXY,m
Clips,MSULLIVAN,m
Barcode::QRCode,NEVESENIN,m
Mono,AMMMA,m
Perl::Analysis::Static,GGOLDBACH,m
WWW::Akismet,NIKOLAY,m
Regexp::Func,NWIGER,m
HTML::Stripper,CORUSCATE,m
Geo::Search,JKRAMER,m
HTML::Demoroniser,JDPORTER,m
DataWarehouse,NFERRAZ,m
CLI::Application::Plugin::RC::YAML,JKRAMER,m
Bio::FastaGrep,JIMI,m
Net::Google::Picasa,CCHAMBER,m
SRCE::Client,CORMANDER,m
Pod::Pod,KJALB,m
Exporter::PkgAlias,JDPORTER,m
Hyper,ACID,m
App::FonBot::Client,MGV,m
Tk::Timer,IVORW,m
RSS::ArchiveReader,SMCAFEE,m
Sub::ReasonableParams,JHELWIG,m
WebService::Fitbit,BRIX,m
MySQL::MyAdmin,HAOYAYOI,m
Tk::Login,BPOWERS,m
SVN::TeamTools,MARKLEEUW,m
Filesys::dfent,TOMC,m
NEXT::init,LEMBARK,m
Task::Elkhound,SKI,m
Net::DNS::Namesever::Trivial,STRZELEC,m
VisualStudio::vcproj,GDM,m
Crypt::OpenSSL::BN,IROBERTS,m
Array::Vec,LWALL,m
xDash,JWACH,m
SQL::Schema,TODD,m
PDL::LAPACK,HBARTEL,m
OVARA,GAMBURGER,m
DTREE,JWAT,m
VideoLan::Client::Media::Output,ELLIRYC,m
Apache::ConfigLDAP,MARKK,m
Apache::WebSQL,GUNTHER,m
XML::GccXml,MOLT,m
Assert::Std,WST,m
Cz::Speak,YENYA,m
Chart::Pie3d,EKMETT,m
Business::OnlinePayment::Moneris,DOWNHOM,m
PDL::Graphics::OpenGL::Perl,CHM,m
App::Spirograph,LICHTKIND,m
Spreadsheet::Lotus,RRAWLINGS,m
Tie::RemoteVar,XERN,m
Text::Parser,PATM,m
DBIx::ContentChecksum::mysql,CJONES,m
WWW::Readability,PHIL,m
CGI::Query,MPECK,m
Net::Amazon::EMR,PFIG,m
Lingua::KO::DateTime,AERO,m
Data::MPQ,CONO,m
WWW::YouTube,ERMEYERS,m
WWW::InstaMapper,AQUILINA,m
WebService::Jamendo::XML,JLOPHTY,m
Lingua::EN::Clarity,BSINGER,m
Digest::Dovecot::CRAM_MD5,DJO,m
Cpuid,MANJUNATH,m
AIX::Devices,SLEONOV,m
HTML::EasyTable,ANIO,m
Class::Translucent,GED,m
AWS::Dynamo,PLYTLE,m
Evented::API,COOPER,m
Act,BOOK,m
P4::OO,ARMSTD,m
VMS::smg,FRIDA,m
File::Split,MIDDLETO,m
Template::Plugin::Duration,HEDWIG,m
Lingua::EN::Semtags,IGORM,m
Mac::Accessibility,BOGA,m
NetCDF,SEMM,m
Apache::MIME,MPB,m
EDA::Cadence,MARKEMER,m
Gtk2::Ex::TimeEntry,JHALLOCK,m
Bryar::DataSource::SVNRepos,MARTIJN,m
Algorithm::Hamming,PEARL,m
ClearCase::Base,THUNDERA,m
WWW::Imgur,BKB,m
Text::Templar,GED,m
Plotter,RDEYS,m
Verilog::Pli,WSNYDER,m
App::PPBuild,EXODIST,m
App::PFM::Abstract,RUITTENB,m
Sys::Linux::Sensors,TKLEIN,m
Crypt::PGP,AGUL,m
WWW::TwentyQuestions,KIRSLE,m
DBIx::Class::ResultSet::Memcache,SYBER,m
Statistics::Distributions::Analyze,SWANSUN,m
PerlPoint::Package,JSTENZEL,m
RDR::Collection,SHAMROCK,m
Text::CaffeinatedMarkup,JGREGORY,m
File::OPC,DOUGDUDE,m
No::Telenor,GAAS,m
Lingua::Zompist,PNE,m
App::Munchies,PJFL,m
Array::Virtual,LWALL,m
Authen::NIST::RBAC,PEDWARDS,m
WordPress::Plugin::RSVP,LUXOR,m
Statistics::Descriptive::Weighted,DHARD,m
Catalyst::Plugin::DBIC::Profiler,TRAVAIL,m
Apache::RobotRules,PARKER,m
Apache::Forward,MPB,m
Apache::Magick,MPB,m
Log::Writer,ARPADF,m
Class::Flyweight,DKUBB,m
XML::OCS,BHANN,m
Palm::MaTirelire,MAXS,m
OpenSync,MAGO,m
XML::Topology::RINGS,ENDLER,m
WebService::Affiliate::CommissionJunction,CAGAO,m
Lemonldap::Portal,EGERMAN,m
Alice,YUKI,m
CGI::Session::DBI,DMUEY,m
Chart::Gdchart,MHEMPEL,m
Sub::Autostub,LEMBARK,m
CGI::SimpleCache,JSCH,m
Monitor::Xymon::Server,TJYANG,m
VMS::SysCalls,CBAIL,m
GSM::SMS,JOHANVDB,m
Alien::GeniusTrader,ECOCODE,m
Module::Cooker,BOFTX,m
TV::Guide,HPA,m
Apache::PATCH,MPB,m
Bio::CloneQC,NOTDOCTOR,m
Digest::CubeHash,CMORRIS,m
URI::Dispatch,MNF,m
WWW::RedditAPI,AQUILINA,m
Verizon::Cloud,JGOTHTX,m
DBIx::QueryByExample,JACKB,m
Mail::Sort,THEDEVIL,m
Authen::Ticketless,JVANASCO,m
DBI::DDI,SEMENOVF,m
WWW::Google::Prediction,MANWAR,m
TAIR::TairBlast,HSUREN,m
autobox::scalar::dump,COWENS,m
Mail::Postfix,VALDEZ,m
Bio::Tapioca,JAC,m
Netware::NDS,KTHOMAS,m
Expect::Angel,MINGZHANG,m
WWW::Lunarstorm,BUMBY,m
WWW::Atlassian::Jira,DBARTLE,m
Data::Compare::Type,SATOSIN,m
Device::Inverter::KOSTAL::PIKO,FANY,m
MSSQL::DBlib,SOMMAR,m
WWW::Foursquare::RSS,AQUILINA,m
CGI::CList,PEARCEC,m
WWW::Reddit::Reader,MATTDEES,m
App::TimeTracking,TEX,m
GISI::SHAPE,SORO,m
RFID::Matrics,GIFF,m
Test::Copyright,SILASMONK,m
WWW::Google::SiteMap,JASONK,m
Win32API::Window,TYEMQ,m
Language::ML,DSPARLING,m
Algorithm::Pair::Best,REID,m
Games::Go::DGS::Status,AMARQUIS,m
PixDraw,KSB,m
ProjectBuilder,BCO,m
Crypt::Rot13,AYRNIEU,m
CfgTie,RANDYM,m
Openview::Message,LBAXTER,m
Solaris::PerlGcc,SUNCPAN,m
Mojolicious::Command::Generate::Lexemes,UNDEF,m
CGI::Explorer,RSAVAGE,m
SQL::QueryBroker,NRBRT,m
Haiku::ApplicationKit,JALOPEURA,m
Geo::Coordinates::WGS84toCH1903,JOACHIMDS,m
WWW::Bookmarks,SOCK,m
Roku::DVP::Remote,DYLAN,m
Calendar::Hebrew,YSTH,m
Speech::Google,NIELSD,m
ActiTime::WebForms,PRANTL,m
Audio::Sox,ADOPTME,m
Openview::Admin,NHARALE,m
WebService::Zabbix,FGA,m
WWW::Hackernews::Parser,DBB,m
Text::Wrap::Hyphenate,MJD,m
IP::RangeCompare,AKALINUX,m
Cache::Memcached::Stack,BANG,m
Text::Perfide::BookSync,ANDREFS,m
WWW::Search::Feedster,SOCK,m
Calendar::TimeTable,POUM,m
DBA::Backup,SEANQ,m
Image::ASCII,NICK,m
GenomePlot,LANCET,m
JSON::DWIW::RPCClient,DOWENS,m
Web::Widget,CORNELIUS,m
DBD::SimpleDB,DARNOLD,m
RFID::Base,GIFF,m
Fuse::YandexFotki,TADAM,m
Prometheus,GURUGEEK,m
WWW::ShopBot,XERN,m
Mail::Sieve,BRONG,m
Gemstone,YOUD,m
DBIx::TableAdapter,GED,m
Geo::Coder::Multiple,FRIFFIN,m
Weed,HOOO,m
Business::OnlinePayment::E2Payments,AIDAN,m
HtDig,JTILLMAN,m
Panda::Net::HTTP,SYBER,m
WWW::Dattebayo,SEPP,m
Getopt::Gnu,WSCOT,m
Tie::RndHash,DFAN,m
WWW::PDB,MIOREL,m
Bundle,ANDK,m
Tie::ShiftSplice,LWALL,m
HTML::Info,JPOWERS,m
Splash::DB,BEN,m
URI::Bookmarks,ASPIERS,m
Hardware::1Wire,DVKLEIN,m
File::MultiTail,SGMIANO,m
User::Vault,GREENPAU,m
CGI::Office::Contacts,RSAVAGE,m
Bio::Genex,JASONS,m
DBD::Nagios,SAPER,m
Telephony::Phonedev,DJHD,m
Catalyst::Plugin::InflateMore,PJFL,m
aLid,MARTIRE,m
Dashboards,KKOLAGO,m
Set::CheckList,MIKO,m
HTTP::Fuzzer,JANSTARKE,m
Bio::PopMX,POPMXTM,m
BBYOPEN,EMOTICON,m
Image::Magick::BarChart,AWESTHOLM,m
Business::OnlinePayment::VirtualNet3,ODO,m
Tk::PhotoRotate,LUSOL,m
Attribute::Exporter,AJWANS,m
BeeSQL,SCOTTA,m
Apache2::LogParser,DEEPAK,m
Audio::Play::MPG321,BREEGSTER,m
CGI::Session::Encrypted,SRIHA,m
Mirago::Search,PAPILLION,m
Nagios::Spool::Writer,DATA,m
WWW::Scraper::Mediathek,RCL,m
Net::SMTP::AfterPOP,DAWOOD,m
CMMi,THUNDERA,m
Laszlo::Documentation,BRICE,m
Solaris::Disk::Mnttab,JFENAL,m
Number::Theory,BARUCH,m
Passwd::Keyring,MEKK,m
YAML::Object,JHTHORSEN,m
Parse::Marpa,JKEGL,m
GSS,MSHLD,m
Thread::Object,DSUGAL,m
Acme::AGMorse,NXONEP,m
File::Size,DMUEY,m
Solaris::NDD,ABURLISON,m
Term::Control,KJALB,m
IO::Toolkit,LINMAR,m
Business::AllPay::Code,DWUZIU,m
Netware::Bindery,KTHOMAS,m
Apache::StripSession,MPB,m
Gtk2::Ex::FormFactory::Entry::SSN,JHALLOCK,m
MSDOS::SysCalls,DMO,m
Solaris::picl,MANJUNATH,m
Xpriori::XMS,KWITKNR,m
Bloom::Filter::XS,AXIAK,m
Geo::Caching::Geocache,NSHADOW,m
XPKG,PMICHAUX,m
Date:Jalali,AHMAD,m
Net::TDMA,JANE,m
BIE::Stat,XINZHENG,m
WebService::Affiliate::WebGains,CAGAO,m
Concurrent,VIPUL,m
Test::Farm,JWU,m
Apache2::ExplorerDestroyer,CRAKRJACK,m
URI::Obfuscate,DDF,m
PDF::PlainLayout,STRAITJAC,m
Lingua::Han2PinYin,FAYLAND,m
Parse::YALALR,SFINK,m
IPC::UPDmsg,RLAUGHLIN,m
Neo4j,NUBA,m
File::Hierarchy,CATALIN,m
Finance::Shares::MySQL,CJM,m
Astro::SkyCoords,GRIXON,m
Proc::ExitStatus,ROSCH,m
Net::SSH::LibSSH,NEPOS,m
Plugin::Language::DML,LEMBARK,m
Mac::Apps::Seasonality::LoadICAOHistory,ELLIOTJS,m
WWW::Livedoor::Frepa,SAYANO,m
WebService::Affiliate::BuyAt,CAGAO,m
NXC::Wrapper,CRLYJEP,m
App::Openmake,SBLANTON,m
Net::3m::Sip2,JSHERMAN,m
MMDS,JV,m
Net::Azureus::AzSMRC,PHDYE,m
DB::Objects,ISAAC,m
WWW::Mechanize:Frames,CPANPERL,m
WebService::Face,AASSAD,m
Business::OnlinePayment::Transfirst,DRFROG,m
Win32::Async,BULKDD,m
Perl6::Subs,CHIPS,m
Crypt::CCTB,DKS,m
Net::Addr,DMTHOMAS,m
Abjad,PERLISH,m
WIN32::MSI::SummaryInfo,EMPI,m
Verilog::GetInfo,ROHITM,m
File::Lock::Any,FANGLY,m
Date::Holidays::SE,PJOTREK,m
CGI::Auth::FOAF_SSL,TOBYINK,m
Murex,LINMAR,m
WWW::Spamla,GRAY,m
PHP::MySQL_Session,CARCUS,m
JUNOS,JUNOS,m
Apache::TrafficServer::BinLog,KRAZUCKY,m
Hessian,HEYTRAV,m
Data::xPathLike,JVVERDE,m
Fukurama,TOBIWAN,m
String::Ruby,VPARSEVAL,m
Cloud::Infrastructure,EWINDISCH,m
Apache2::ModBT,CRAKRJACK,m
TAP::Formatter::Spreadsheet,MURUGU,m
Include,GBARR,m
Convert::Clothing::Sizes,NICOLAW,m
Web::Beacon,JEREMIAH,m
Apache::AuthAny,MPB,m
RFID::Alien,GIFF,m
Perl6::Comments,CHORNY,m
BGPmon,BGPMON,m
LockFile::Scheme,JV,m
HTML::ParseForm,NMONNET,m
Compiler::CodeGenerator::LLVM,GOCCY,m
Magento,VANHOESEL,m
Devel::Env::ElaborateDump,OSMUNDOHW,m
Win32::Skype,MNCOPPOLA,m
Apache::AddrMunge,MJD,m
Geo::GoogleEarth::Document,MRDVT,m
Tk::ReportBox,LAWGON,m
IO::Socket:CAN,CITA,m
Lingua::FR::Fathom,LEFORESJF,m
Marpa::HTML::XS,JKEGL,m
WWW::NanoRef,DOWENS,m
Thread::Sociable,DARNOLD,m
Bio::PDB::Structure,RULIX,m
OTRS::AdminESCL,ROHITBASU,m
Physics::Solar::VSO,ONEIROS,m
NetMgmt,RSTAATS,m
Net::BitTorrent::LibBT::Tracker,CRAKRJACK,m
URI::Bookmark,ASPIERS,m
Boulder,LDS,m
Devel::sdb,KRAMAN,m
HTML::TabulateData,TIAO,m
Solaris::DeviceTree,DAGOBERT,m
CPAN::Curate,NEILB,m
Geo::TextGIS::Gazetteer,LEIDNER,m
Win32::FileType,JENDA,m
Var::State,JHTHORSEN,m
XML::Xalan,EDPRATOMO,m
Krolik,BOAG,m
WebService::BitBucket,MEKK,m
IPCdb,NEO,m
Tree::Menu,PSHARPE,m
Apache::LogMail,MPB,m
Quiz::Flashcard,MITHALDU,m
SGI::GL,AMOSS,m
WWW::HtmlUnit::Spidey,NINUZZO,m
Datascope,DANMQ,m
Music::GUIDO,KARLWARD,m
Marpa::Perl,JKEGL,m
Lingua::Tolkien::BURL,RJE,m
Geo::Location,JKRAMER,m
Class::Clone,CRAKRJACK,m
Tk::TableMatrix::SpreadsheetHideRowsOrCols,ARJUN,m
FestVox,LENZO,m
Text::Quickwrap,IVANPAN,m
Config::Screwdriver,SILASMONK,m
SAFT,MHO,m
BIE,XINZHENG,m
CGI::SessionM,ABALAMA,m
Oak,DRUOSO,m
Bio::MaxQuant,JIMI,m
Scalar::Footnote,SPURKIS,m
Net::CoSign,DAPATRICK,m
Android,DNS,m
Authorizenet,DLINCOLN,m
Class::Eroot,DMR,m
DBIx::Encoding,MYFINDER,m
Test::NoCoreDump,NHORNE,m
Text::Math::NumExp,ANDREFS,m
WWW::Yahoo::DrivingDirections,KESTER,m
Net::DNS::Sinkhole,RHARMAN,m
BabelObjects,KERMAGO,m
Apache::AuthenDBI,MERGL,m
Apache::Checksum,MPB,m
App::FileTools::BulkRename,SWESTRUP,m
HTTP::Server:::Brick,AUFFLICK,m
Apache2::WebApp::Toolkit,MBROOKS,m
Net::FluidDB,FXN,m
SGI::FM,AMOSS,m
SOAP::Axis,BWMCADAMS,m
App::Kaizendo,SJN,m
Games::RogueLike::MapGenerator,SKAUFMAN,m
Resolute::RAPS,CHGOETZE,m
Apache::BlockAgent,MPB,m
File::PID::Named,CAGAO,m
App::nztop,JCUA,m
WWW::Scraper::ISBN::LibUniverIt::Driver,MARCOG,m
InterMine,INTERMINE,m
WWW::DHL,SEPP,m
Gtk::Dialog,ALISTAIRC,m
SVN::Simple::Client,MJGARDNER,m
Date::Hebrew,EPSALON,m
Apache::TarGzip,ZENIN,m
Text::A2E,PILHAMU,m
Genealogy,RSAVAGE,m
Catalyst::Plugin::ConfigComponents,PJFL,m
Puppet::VcsTools::History,DDUMONT,m
SQL::Extended,DARNOLD,m
Ratpoison,BUU,m
Geo::Postcodes::PL,BLINDLUKE,m
Perl::DependList,DMUEY,m
App::Hiveminder,GENEHACK,m
Business::OnlinePayment::Bluepay,CPKOIS,m
Tk::DBIx,XPIX,m
Panda::Encode::Base2N,SYBER,m
WebService::Affiliate::AffiliateWindow,CAGAO,m
Class::DBI::Loader::Multiplex,NAOKIURAI,m
Milarepa,JKEGL,m
Image::OpenCV,DRYMAN,m
Net::Bitly,SKAUFMAN,m
App::Wubot,VVU,m
RRG::Parser,CLBECKER,m
Crypt::CubeHash,CMORRIS,m
Devel::Psichedb,DARNOLD,m
WWW::TVguide::NL,BAS,m
WWW::LacunaExpanse::API,ICYDEE,m
DBIx::MSAccess::Convert2Db,RSAVAGE,m
Lemonldap::Federation,EGERMAN,m
Gtk2::Ex::FormFactory::DateEntry,JHALLOCK,m
VideoLan::Client::Media,ELLIRYC,m
Net::IPP,BIGHIL,m
Win32::VFW,DNS,m
DBIx::SchemaView,MILSO,m
Pod::Texinfo,KJALB,m
Jeens,JESSESTAY,m
WebService::Sharepoint,SATRAC,m
Finance::Bank::DE::SpardaBank,RMORIZ,m
WWW::BetFair::Sports::FreeAPI,BLABOS,m
Statistics::Synchrony,RGARTON,m
Solaris::Disk::VTOC,JFENAL,m
PerlPanel,NICZERO,m
MooseX::Types::Date::Piece,STEVENL,m
CLI::Application::Plugin,JKRAMER,m
Tk::OutlookBar,ZABEL,m
WWW::Webjay,SPACEMAN,m
ProxyGrinder,KANGU,m
Bundle::Test,SZABGAB,m
Apache::FTP,PMKANE,m
DateTimeX::Tie::Hash,METAL,m
XML::LibXSLT::Processor,YOREEK,m
GatherScatter,AQUILINA,m
AFS::Command,ISAACSON,m
Puppet::VcsTools::File,DDUMONT,m
Audio::glitchDS,PFIG,m
Tribunais,EDUARDOW,m
Time:Compare,YAK,m
Mail::Barracuda,JAUER,m
Math::Logic::Ternary,MHASCH,m
Marpa::HTML,JKEGL,m
Puppet::Body,DDUMONT,m
Haiku::SupportKit,JALOPEURA,m
Marpa::R3,JKEGL,m
Monitor::Xymon::Client,TJYANG,m
Geo::Caching::Interfaces::GCcom,NSHADOW,m
Test::Class::Rig,BYTEROCK,m
Cisco::Network,CMORRIS,m
Crypt::Password,DRSTEVE,m
Net::SPDY,LKUNDRAK,m
CLI::Application::Plugin::RC,JKRAMER,m
Device::SerialPort::Arduino,SYXANASH,m
Crypt::PGP6,AGUL,m
TAMeb::Admin,MIKFIRE,m
Win32::GD,DAVEROTH,m
Rills,MEWSOFT,m
DFA::Command,RSAVAGE,m
Google::Shopping,OVNTATAR,m
Acme::Adjudge,DMUEY,m
Slash,CNANDOR,m
Geo::Postcodes::JP,BKB,m
Pod::MIF,JNH,m
Lingua::JA::EDICT,JKIM,m
IO::Redirect,DMUEY,m
WebService::BabelFish,DMUEY,m
Parse::Lexer,EKMETT,m
Parse::Krb5::Config,PKNOWLES,m
Math::XOR,CRAKRJACK,m
Chemistry::ESPT,JSONNENB,m
CompBio,SEANQ,m
File::sudoers,CMORRIS,m
Log::Detect,WSNYDER,m
Sybase::SybAdm,DGRAEVEJ,m
Chado::Schema,RBUELS,m
SMSC,SMS,m
Finance::Bank::NFCU,DYLAN,m
JSON::RPC::Client::Spec,KOPYTOV,m
Module::Test,INGY,m
Bing::Azure::WebSearch,SEOVISUAL,m
WOA::REST,PLCGI,m
Finance::NikkeiQuote,DAIBA,m
autobox::hash::dump,COWENS,m
CGI::Formalware,RSAVAGE,m
Template::GD,ABW,m
Error::Layout,LEPTON,m
Mac::Apps::Seasonality::LoadICAOHistoryFromWunderground,ELLIOTJS,m
Mojolicious::Plugin::DBIProfiler,RSHADOW,m
DHX,LUCAS,m
Apache::BBS,MKOSSATZ,m
X11::Xforms,MARTINB,m
CGI::Session::Auth::Mouse,NOBJAS,m
WebService::LOC::CongRec,DINOMITE,m
T3D,GJB,m
Gtk2::Ex::DateEntry,JHALLOCK,m
PDA::PilotDesktop,JWIEGLEY,m
SWF,LISCOVIUS,m
Finance::Bank::Nationwide,TEHSI,m
Finance::TechnicalAnalysis,REDOX,m
Win32::MSI,PMAREK,m
OpenCA,MADWOLF,m
SMIMEUtil,SAMPO,m
File::Atomic,DMUEY,m
GISI,SORO,m
WWW::Google::Voice,NICSPA,m
Carp::Once,DMUEY,m
Net::IPRangeCompare,AKALINUX,m
MogileFS::Helpers,FUKAI,m
Proc::times,TOMC,m
Regexp::Compost,SHIELDS,m
Twitter::ZenTwitter,ZEFONSECA,m
Oracle::Reporter,GEOTIGER,m
Archive::Cabinet,BRADD,m
Net::IM,KIRSLE,m
MooseX::Types::IPv6,KHULTMAN,m
WWW::Qaiku,AJAYRES,m
Finance::GeniusTrader,ECOCODE,m
Mail::DSN,MMCLAGAN,m
Tie::PerfectHash,XERN,m
SVGLAB,XIAODIAN,m
Text::Record::Cleanser,KIMRYAN,m
ZipTie,LBAYER,m
HTTPD::Config,LDS,m
Speech::EST,DJHD,m
GUI::Guido,TBRADFUTE,m
Tree::List2Tree,THW,m
Plagger::Plugin::Publish::Reddit,AQUILINA,m
App::sh2p,CLIVE,m
Geo::GPS::Data,NFMNUNES,m
GD::Gauge,CCLOUTIER,m
When::Happens,MOODFARM,m
Opsview::Performanceparsing,OPSVIEW,m
DHTXML::Core,EDUARDOW,m
Device::LabJack::Control,APLONIS,m
Crypt::Analysis,CMORRIS,m
Mail::Vacation::LDAP,RFOLEY,m
Text::Record::Filter,KIMRYAN,m
Language::Style,EKMETT,m
NetServer::Compiler,CHSTROSS,m
Gtk2::Ex::FileQuickFind,HOOO,m
Perl::Tidyview,LEIF,m
RDF::SIO,MARKW,m
CGI::FormFactory,GAVINC,m
DB::Migrate,KITOMER,m
AI::Categorize,KWILLIAMS,m
WWW::Search::Bookmarks,SOCK,m
Plex,SCIO,m
IPC::ChildSafe,DSB,m
Net::AMQP::Haiku,REBX,m
Net::Cloud::Session,FSPEISER,m
BnP,STBEY,m
Chess::GameClock,CHESSKIT,m
Mobile::Messaging::ApplePushNotification,TCHATZI,m
Lemonolap,EGERMAN,m
Data::ID::OnceID,YAKUBORI,m
Thread::IO,DSUGAL,m
Log::Delayed,WSNYDER,m
Text::Corpus,KUBINA,m
Audio::Ecasound::Multitrack,GANGLION,m
Crypt::Schnorr::AuthSign,AGUL,m
Sendmail::M4::mail8_zombie,CML,m
Net::Irate,DTHAY,m
Net::OpenVPN::ProxyManager,SILLYMOOS,m
Religion::Bible::Regex,HOLMLUND,m
User::utent,ROSCH,m
RSS::Tree,SMCAFEE,m
Math::Random::Seed,FANGLY,m
Apache::Log::Spread,GSCHLOSS,m
Apache::AuthenRaduis,DANIEL,m
Verilog::Info,ROHITM,m
Device::IRU::GE,TROXEL,m
POE::Component::IMDB,BUU,m
Apache::QuickCMS,TMURRAY,m
AppleII::DOS33,CJM,m
HoneyClient,MITREHC,m
Solaris::Disk::SVM,JFENAL,m
Apache::AuthzGender,MPB,m
Org::FRDCSA,ANDREWD,m
Tree::Interval,GNB,m
Plugin::Installer,LEMBARK,m
SGI::SysCalls,AMOSS,m
Carp::Dump,CATALIN,m
WWW::DirectUpload,SEPP,m
GISI::MIFMID,SORO,m
TinkerForge,JOBA,m
Date::FromToday,AWOHLD,m
SWIFT::Factory::MT300,BIKER,m
Filter::Log4perl,FUJIMURA,m
CGI::Session::DB2,DMCBRIDE,m
Schedule::Load,WSNYDER,m
Net::CBQ,DEEPAK,m
Net::SMS::LogicSMS,LENGEL,m
Apache::WDB,JROWE,m
Shockwave::Lingo,MARTIN,m
IPC::Run::Simple,SFINK,m
Lingua::KR::Hangul,OKLETSGO,m
WebService::TGC,COLINK,m
PNI,FIBO,m
DateTime::Event::Predict,BHANN,m
WebService::GoogleMaps,KLOHNER,m
Wikifier,COOPER,m
PostScript::Basic,STWIGGER,m
Eng::Naval,RAGRO,m
Oracle::OCI,TIMB,m
TeX::Convert::Image,MRTS,m
DHTMLX,EDUARDOW,m
BoxBackup,PTHOMSEN,m
Mac::Serial,DIVERDI,m
DFA::Simple,RANDYM,m
ThetaCRM::Utils,JLOUISBIZ,m
Apache::ModBT,CRAKRJACK,m
Parallel::Cluster,RJHARMON,m
Bio::Affymetrix,SKIPPY,m
Language::VBParser,FRETT,m
CFEngine::CFPerl,TEODOR,m
Text::TEng,ANDREFS,m
autobox::array::dump,COWENS,m
Data::Postponed,JJORE,m
SICStus,CBAIL,m
Thread::Group,DSUGAL,m
MarpaX::Parse,RNS,m
SimpleStringsService::Client,DARBYR,m
Sandgrains,MGODINHO,m
SemanticDebugger,HCKKID,m
Apache::SpeedLimit,MPB,m
Cake,MAMOD,m
Riscos,RISCOSML,m
Graph::Easy::Marpa,RSAVAGE,m
Sort::PolySort,DMACKS,m
File::Compare::Util,KRUGGLE,m
WWW::Shorten::Smrls,MGVDM,m
PDF::Render,BORONK,m
Locale::CLDR::ID,PHILKIME,m
Win32::PsTools,BRAD,m
Security::LibPath,JAMESODEN,m
Device::SVGA,SCOTTVR,m
Lingua::EN::GivenNames,RSAVAGE,m
MOP,ORTALO,m
Language::Befunge::Debugger,JQUELIN,m
Lemonldap::Handler,GUIMARD,m
WWW::LycaMobile,MANWAR,m
CGI::WebApp,SHAWNVAN,m
Nagios::Status,RCROWDER,m
Win32::SlimCore,BULKDD,m
DBIx::GenerateData,JACKB,m
Nagios::Plugin::CAS,DOUGDUDE,m
Math::SimpleInterest,BYOURTH,m
Toc,RCL,m
App::Twirssi,ZIGDON,m
Encode::Any,PCSJJ,m
Tk::XMLTree,SANTOS,m
App::autopod,COSIMO,m
GSM::PDU,TECHCODE,m
Cisco::ACS::AccountActions,ENDLER,m
Nginx::Engine,ZZZ,m
ActiveRecord,DEEPFRYED,m
WWW::AgileZen,MANOWAR,m
Marpa::XS,JKEGL,m
Net:::DDDS,LEIFJ,m
WWW::Nike::NikePlus,ALEXLOMAS,m
Win32::Message,DAVEROTH,m
IP::ChinaISP,PANGJ,m
Lemonldap::Crypto,GUIMARD,m
POE::Component::Client::Kismet,WIRELESSD,m
Net::LDAP::Extension::eDirectoryPassword,GHALSE,m
DBIx::Pquery,PCHINES,m
SNMP::Query::Asynch,SSCAFFIDI,m
Sub::Prototype::Introspect,CIA,m
RFID::EPC,GIFF,m
Cobweb,LEPREVOST,m
Email::Send::Yahoomail,ADARSHTP,m
EMC::Symcli::Symm,FUNKJAMES,m
Bio::DNAssemble,NOTDOCTOR,m
Ensure,SMKZONE,m
WWW::Forge,FPORCHER,m
DBIx::Router,PERRIN,m
SDL2,KTHAKORE,m
GD::Image::Aggregation::Resize,LOGIE,m
WWW::RottenTomatoes::API,CVEGA,m
Class::Tree,RSAVAGE,m
Bundle::Moose,SKI,m
App::SMSCli,HVALVERDE,m
Paranoid::Network::UDP,CORLISS,m
App::SPG,GERA,m
Gtk2::Ex::Entry::SSN,JHALLOCK,m
Weather::GFS,LBECCHI,m
RTF::Base,ADOPTME,m
Business::OnlinePayment::HSBC,WREIS,m
X11::XRT,KENFOX,m
Ham::WSPR,MEH,m
WAP::WML,SAA,m
Finance::Bank::Melbourne,LXP,m
Test::Reporter::Transport::Outlook,ARFREITAS,m
Net::OM2,LEIFJ,m
Mail::Exchange,GBL,m
jQuery::jqGrid,ICYDEE,m
Tivoli::AccessManager,MIKFIRE,m
CGI::Response,MGH,m
Math::GaloisField,MHASCH,m
Agent,SPURKIS,m
Parse::DMOZ,VIPUL,m
CGI::Application::GDGraph::lines_ap,JNBROOKES,m
Net::SIGTRAN,MOBILEART,m
Device::ISY,JCHONIG,m
MSSQL::Sqllib,SOMMAR,m
Tk::Wizard::Images,LGODDARD,m
Fax::DataFax,GEOTIGER,m
WWW::Livedoor,SAYANO,m
Muldis::D,DUNCAND,m
Bundle::Wx::Perl,LICHTKIND,m
Finance::Streamer,JERI,m
Parallax::App,MACROFAGE,m
DBIx::Class::Migrate,KITOMER,m
Number::Theory::CFrac,BARUCH,m
Games::Tournament::TableTennis,MYRTSCHT,m
Hash::HPath,JERRYMBC,m
BLX::XSDSQL,BLX,m
Apache2::AuthLDAP,CFILIPPE,m
Graph::Centrality,KUBINA,m
WWW::Firebase,ICYDEE,m
SAP::Rfc,PIERS,m
Devel::ObjectCount,TBUSCH,m
Net::SMS::Clickatell:SOAP,PFARR,m
Net::ICQ::On,JEROMEMCK,m
Podcast,CLONE,m
DBD::FreeTDS,SPANNRING,m
Geo::StreetAddress::Canada,TEEDOT,m
Parallel::Application,CHOLT,m
WWW::Shorten::SuPr,KANISHKA,m
Net::WSF,SAMPO,m
WordLists,PERRETTDL,m
Asterisk::config::syntax,NSNAKE,m
Mojolicious::Plugin::FluentLogger,FUKATA,m
WebService::Affiliate::TradeDoubler,CAGAO,m
OTRS::OPM::MultilevelEscalation,ROHITBASU,m
Redis::Object,UKAUTZ,m
Win32::Lglcd,XLAT,m
HTTP::UserAgentStringParser,NMOLDAV,m
ThreeD,ADESC,m
FormValidator::Simple::Plugin::Number::Phone::US,BCMB,m
Webservice::Yandex::Suggest,STEALTHY,m
POE::Component::IRC::Plugin::Vim::Tips,CURTIS,m
MIME::Base32::Readable,PIROLIX,m
ETL::Pequel,GAFFIE,m
CompBio::Simple,SEANQ,m
HTML::AjaxTags::TT,KMCGRATH,m
Module::Include,INGY,m
MooseX::Storage::File_or_DB,SETITESUK,m
XML::DSIG,WISSER,m
Algorithm::BellmanFord,ROHANK,m
Net::SSH::Cluster,VVU,m
Apache::VhostSandwich,MARKC,m
Object::POOF,MARKLE,m
Task::Gtk2,KIMMEL,m
MasonX::Resolver::CVS,KORTY,m
RandomJungle,RFREIMUTH,m
Array::Substr,LWALL,m
Cookie::Session::Login,BLACKWIND,m
SQL::QueryBuilder,RIVOTTI,m
File::Hierarchy::Rule,CATALIN,m
App::Mafia,MGV,m
Finance::QFX,BUDNEY,m
Lingua::Norms::USF,RGARTON,m
Games::Freelancer,MALUKU,m
Apache::RobotLimit,PARKER,m
SOAP::MySOAP,KARJALA,m
Net::Async::WAMP,SROLLYSON,m
Alien::LibUSB::Compat,BRIX,m
VMWare::LabmanSoap,DOSNIBBLE,m
XML::Simple::Planner,WVARGAS,m
Freedesktop::Trash,RRWO,m
WWW::Mechanize::Plugin::Ajax,SPROUT,m
HtDig::Htsearch,DMUEY,m
Apache::AuthzDBI,MERGL,m
SDDF,FIS,m
Echo::StreamServer,ADROFFNER,m
Wapiti::Parser,MARCUSSEN,m
Net::SFTP::Expect,JONASBULL,m
SinaWeibo::OAuth,XIAOMO,m
Statistics::Cluster::KMeans,ERIKE,m
Finance::Bank::US::ShareBuilder,SSEVERIN,m
Class::ReluctantORM,CLWOLFE,m
Spreadsheet::ParseGoogle,DIVIDOR,m
CatalystX::Usul,PJFL,m
PagerDuty::Schedule,JACOBROSE,m
SnitchD,AAYARS,m
ToolTalk,MARCP,m
Wrap,XIAOMO,m
App::backimap,ALEXM,m
Mikrotik,MAKITA,m
XML::XPS,MAIN,m
Test::WWW::Accessibility,ADOPTME,m
Apache::NavBar,MPB,m
Exporter::Options,YSTH,m
Template::Object,IFOMICHEV,m
WWW::BTjunkie,LEV,m
Finance::SE::PPM,ERWAN,m
Cicero,FRIEDO,m
Finance::Shares::Chart,CJM,m
XML::Parser::Generic,BANG,m
Math::Matrix::SVD,MCEGLOWS,m
CaCORE,JIANGS,m
Bundle::SSH,SZABGAB,m
Finance::Risk,TOM,m
DBD::Spatialite,LOKKJU,m
Sub::ForceEval,LEMBARK,m
File::ManualFlock,WCATLAN,m
WebService::Amazon::CloudSearch,SALTBREEZ,m
Unix::Admin,BDA,m
AppleII::Pascal,CJM,m
Mail::PerlTix,JJARVINEN,m
Tie::Assert,MOLT,m
PDF::Maker,GWHITE,m
Alien::Tidy,MBAAS,m
DBIx::Simple::Procedure,AWNCORP,m
AutoCons,RIDDLE,m
PDL::Graphics::ColorSpace,MAGGIEXYZ,m
Mail::vpopmaild,DDF,m
Uta,YUKI,m
