#!/usr/bin/perl

# use 5.010;
use strict;
use warnings;

=head1 NAME



=head1 SYNOPSIS



=head1 OPTIONS

=over 8

=cut

my @opt = <<'=back' =~ /B<--(\S+)>/g;

=item B<--help|h!>

This help

=back

=head1 DESCRIPTION



=cut


use FindBin;
use lib "$FindBin::Bin/../lib";
BEGIN {
    push @INC, qw(       );
}

use Dumpvalue;
use File::Basename qw(dirname);
use File::Path qw(mkpath);
use File::Spec;
use File::Temp;
use Getopt::Long;
use Pod::Usage;
use Hash::Util qw(lock_keys);

our %Opt;
lock_keys %Opt, map { /([^=|!]+)/ } @opt;
GetOptions(\%Opt,
           @opt,
          ) or pod2usage(1);
if ($Opt{help}) {
    pod2usage(0);
}
use Time::HiRes qw(sleep);

my $i = 0;
while (<DATA>) {
    chomp;
    my $m = $_;
    my $t = scalar localtime;
    $i++;
    warn sprintf "(%d) %s: %s\n", $i, $t, $m;
    0 == system "/opt/perl/current/bin/perl", "-Iprivatelib", "-Ilib", "bin/from-mods-to-primeur.pl", $m or die "Alert: $t: Problem while running from-mods-to-primeur for '$m'";
    sleep 0.08;
}

# Local Variables:
# mode: cperl
# cperl-indent-level: 4
# End:

__END__
ACL::Regex
AI::FANN
AI::NeuralNet::Hopfield
AI::ParticleSwarmOptimization
AIX::LVM
AIX::ODM
AIX::Perfstat
Aard
Acme::Buffy
Acme::Enc
Acme::Floral
Acme::GuessNumber
Acme::Homer
Acme::Hyde
Acme::MetaSyntactic::buzzwords
Acme::Morse::Audible
Acme::PIA::Export
Acme::Phlegethoth
Acme::Pythonic
Acme::Scripticide
Acme::ScriptoPhrenic
Acme::Test::Weather
Acme::Tie::Eleet
Acme::URM
Acme::Umlautify
Acme::Void
Acme::Wabby
Algorithm::BaumWelch
Algorithm::BinPack
Algorithm::ContextVector
Algorithm::CurveFit
Algorithm::DistanceMatrix
Algorithm::ExpectationMaximization
Algorithm::Functional::BFS
Algorithm::GoldenSection
Algorithm::Graphs::TransitiveClosure
Algorithm::Hamming::Perl
Algorithm::Knapsack
Algorithm::LeakyBucket
Algorithm::Line::Bresenham
Algorithm::Merge
Algorithm::NGram
Algorithm::NeedlemanWunsch
Algorithm::Networksort
Algorithm::Numerical::Shuffle
Algorithm::PageRank::XS
Algorithm::Pair::Swiss
Algorithm::SISort
Algorithm::SVMLight
Algorithm::SixDegrees
Algorithm::SpiralSearch
Algorithm::Step
Algorithm::TokenBucket
Algorithm::VSM
Algorithm::WordLevelStatistics
Alias
Alien::Gnuplot
Alien::IUP
Alien::Jerl
Alien::LibANN
Alien::LibUSBx
Alien::QtSmoke
Alien::SDL2
Alien::TALib
Alien::VideoLAN::LibVLC
Alien::scriptaculous
AltaVista::PerlSDK
Amon2::Plugin::Web::FormValidator::Simple
Anansi::Actor
Anansi::Class
Anansi::Component
Anansi::ComponentManager
Anansi::Database
Anansi::Database::MySQL
Anansi::Database::Oracle
Anansi::Database::PostgreSQL
Anansi::DatabaseComponent
Anansi::Library
Anansi::ObjectManager
Anansi::Script
Anansi::Script::CGI
Anansi::Script::Shell
Anansi::Singleton
Any::Renderer::Data::Printer
AnyDBM_File::Importer
AnyEvent::FreeSWITCH
AnyEvent::HTTPD::CookiePatch
AnyEvent::MultiDownload
AnyEvent::POE_Reference
AnyEvent::XMLRPC
AnyEvent::Yubico
Apache::AddHostPath
Apache::Archive
Apache::AuthCAS
Apache::AuthChecker
Apache::AuthCookieDBI
Apache::AuthCookieLDAP
Apache::AuthExpire
Apache::AuthLDAP
Apache::AuthPOP3
Apache::AuthPerLDAP
Apache::AuthTkt
Apache::Authen::Program
Apache::AuthenCache
Apache::AuthenPasswdSrv
Apache::AuthzSplitDomainUser
Apache::AutoIndex
Apache::AutoLogin
Apache::Backhand
Apache::Compress
Apache::DBILogConfig
Apache::DBILogger
Apache::DBILogin
Apache::DebugInfo
Apache::Dynagzip
Apache::EmbeddedPerl::Lite
Apache::FakeCookie
Apache::ForwardedFor
Apache::GTopLimit
Apache::Gateway
Apache::JemplateFilter
Apache::Layer
Apache::LogIgnore
Apache::MP3::Skin
Apache::MimeXML
Apache::Motd
Apache::NNTPGateway
Apache::OWA
Apache::PHLogin
Apache::ParseLog
Apache::PrettyText
Apache::ProxyPass
Apache::RandomLocation
Apache::RequestNotes
Apache::SessionManager
Apache::SharedMem
Apache::SimpleReplace
Apache::Storage
Apache::TS::AdminClient
Apache::TempFile
Apache::TimedRedirect
Apache::Traffic
Apache::TransLDAP
Apache::UpnpImgBrowser
Apache::Usertrack
Apache::VMonitor
Apache::Watchdog::RunAway
Apache::Yaalr
Apache::iTunes
Apache2::Ajax
Apache2::AuthColloquy
Apache2::AuthCookieDBI
Apache2::AuthCookieLDAP
Apache2::AuthNetLDAP
Apache2::AuthZLDAP
Apache2::Authen::Passphrase
Apache2::AuthenDBMCache
Apache2::AuthenMSAD
Apache2::AuthenSmb
Apache2::Autocomplete
Apache2::FileManager
Apache2::Filter::GoogleAnalytics
Apache2::Filter::Minifier::CSS
Apache2::Filter::Minifier::JavaScript
Apache2::Filter::TagAware
Apache2::ModProxyPerlHtml
Apache2::RequestRec::Time
Apache2::Response::FileMerge
Apache2::WebApp::Plugin::CGI
Apache2::WebApp::Plugin::Cookie
Apache2::WebApp::Plugin::DBI
Apache2::WebApp::Plugin::DateTime
Apache2::WebApp::Plugin::File
Apache2::WebApp::Plugin::Filters
Apache2::WebApp::Plugin::Mail
Apache2::WebApp::Plugin::Session
Apache2::WebApp::Plugin::Session::File
Apache2::WebApp::Plugin::Session::MySQL
Apache2::WebApp::Plugin::Validate
Apache2::xForwardedFor
Apache::Cookie::Encrypted
Apache::Mysql
App::AutoBuild
App::Devbot
App::EUMM::Migrate
App::EUMM::Upgrade
App::Git::Ribbon
App::Git::Spark
App::GitGerrit
App::MediaWiki2Git
App::MusicExpo
App::Options
App::Pastebin::sprunge
App::Pm2Port
App::PrereqGrapher
App::Reg
App::Smbxfer
App::St
App::TarColor
App::Unix::RPasswd
App::XMMS2::Notifier
App::perlhl
App::psst
App::tkiv
AppConfig::Std
Archive::Chm
Archive::Probe
Archive::StringToZip
Archive::Tar::Stream
Archive::Tyd
Archive::Unrar
Archive::ZZip
Array::APX
Array::AsObject
Array::Columnize
Array::Compare
Array::CompareAndFilter
Array::DeepUtils
Array::GroupBy
Array::KeepGrepped
Array::LineReader
Array::PrintCols
Array::To::Moose
Asm::X86
Asm::Z80::Table
Astro::Cosmology
Astro::MoonPhase
Astro::SLA
Astro::SpaceElevator
Astro::SpaceTrack
Astro::SunTime
Async::Group
Attribute::Args
Attribute::Deprecated
Attribute::Property
Audio::Ardour::Control
Audio::Ardour::Irc
Audio::Audacious
Audio::CD
Audio::Cuefile::Parser
Audio::Ecasound
Audio::FLAC::Decoder
Audio::FLAC::Header
Audio::GSM
Audio::Mixer
Audio::OSS
Audio::Radio::Sirius
Audio::Scrobbler2
Authen::ACE
Authen::CyrusSASL
Authen::Krb5::Easy
Authen::Krb5Password
Authen::OATH
Authen::OATH::OCRA
Authen::PIN
Authen::Passphrase::SaltedSHA512
Authen::Simple::IMAP
Authen::Users
AutoRole
B::CodeLines
B::Fathom
B::Graph
BBDB
BIE::App::PacBio
BIE::Data::HDF5
BIE::Data::HDF5::Data
BIE::Data::HDF5::File
BIE::Data::HDF5::Path
BS2000::LMS
BSD::Ipfwgen
BSD::Resource
BSD::Socket::Splice
BSD::Sysctl
Backup::Duplicity::YADW
Bad::Words
Barcode::Code128
CGI::Session::Serialize::Base64
Be::Attribute
Be::Query
Benchmark::Forking
BerkeleyDB::Locks
Bhagavatgita
Biblio::Citation::Compare
Biblio::Thesaurus
BigIP::ParseConfig
Binutils::Objdump
Bio::Align::Subset
Bio::DB::NextProt
Bio::Das::Lite
Bio::ECell
Bio::EasyYang
Bio::Glite
Bio::IlluminaSAV
Bio::MaxQuant::Evidence::Statistics
Bio::Tools::Alignment::Overview
Bio::Trace::ABIF
Bloom::Faster
BlueCoat::SGOS
Bot::BasicBot::Pluggable::Module::Gitbot
Bot::BasicBot::Pluggable::Module::PasteBin
Bot::BasicBot::Pluggable::Module::Shutdown
Bot::BasicBot::Pluggable::Module::XKCD
Bundle::Atoll
Bundle::Bugzilla
Bundle::DBWIZ
Bundle::Ensembl
Bundle::Gnome2
Bundle::Knetrix
Bundle::OpenXPKI
Bundle::POPFile
Bundle::Rose
Bundle::ePortal
Business::AU::ACN
Business::AU::TFN
Business::CUSIP::Random
Business::Cashcow
Business::FedEx::RateRequest
Business::HK::IdentityCard
Business::ISSN
Business::KontoCheck
Business::LCCN
Business::NoChex
Business::OnlinePayment::SynapseGateway
Business::Stripe
Business::UPC
Business::US::USPS::IMB
Business::US_Amort
Business::WorldPay::Junior
Schedule::ByClock
C::TCC
CDB_File::Generator
CDDB
CGI::Alert
CGI::Application::Demo::Ajax
CGI::Application::Plugin::AbstractCallback
CGI::Application::Plugin::AnyCGI
CGI::Application::Plugin::CHI
CGI::Application::Plugin::CompressGzip
CGI::Application::Plugin::Config::Any
CGI::Application::Plugin::DBIC::Schema
CGI::Application::Plugin::DebugMessage
CGI::Application::Plugin::Eparam
CGI::Application::Plugin::HtmlTidy
CGI::Application::Plugin::Mason
CGI::Application::Plugin::MessageStack
CGI::Application::Plugin::Routes
CGI::Application::Plugin::Stream
CGI::Application::Plugin::SuperForm
CGI::ArgChecker
CGI::Auth::Basic
CGI::AuthRegister
CGI::Authent
CGI::Browse
CGI::Buffer
CGI::Cookie::XS
CGI::Debug
CGI::Deurl
CGI::Echo
CGI::Enurl
CGI::Ex::Template::XS
CGI::ExtDirect
CGI::FormBuilder::Mail::FormatMultiPart
CGI::FormBuilder::Source::YAML
CGI::FormMagick
CGI::Getopt
CGI::Info
CGI::Lazy::ModPerl
CGI::Lingua
CGI::List
CGI::Minimal
CGI::MultiValuedHash
CGI::NoPoison
CGI::Pager
CGI::PathInfo
CGI::Persistent
CGI::QuickForm
CGI::SSI_Parser
CGI::SecureState
CGI::Session::Driver::odbc
CGI::Session::Driver::oracle
CGI::Session::ExpireSessions
CGI::Session::MembersArea
CGI::Session::Plugin::Redirect
CGI::Session::Serialize::php
CGI::Snapp
CGI::Snapp::Demo::One
CGI::Snapp::Demo::Three
CGI::Snapp::Demo::Two
CGI::State
CGI::Struct
CGI::Template
CGI::Untaint::CountyStateProvince
CGI::Untaint::CountyStateProvince::GB
CGI::Untaint::CountyStateProvince::US
CGI::Untaint::Facebook
CGI::Untaint::Twitter
CGI::Untaint::us_date
CGI::UploadEasy
CGI::Validate
CGI::Wiki::Store::Mediawiki
CGI::XML
CLI::Application
CLI::Startup
CLucene
COPS::Client
CORBA::IDLtree
CPAN::AutoINC
CPAN::Mini::Inject::Remote
CPAN::Search::Author
CPAN::Search::Tester
CSS::Adaptor::Whitelist
CSS::LESS
CSS::Minifier
Cache::Benchmark
Cache::Bounded
Cache::Memcached::Queue
Cache::Memcached::Tie
Cache::Memcached::XS
Cache::Mmap
Cache::Weak
Calendar::CSA
Calendar::Persian
Calendar::Saka
Callback
Carp::Notify
Cartography::Projection::GCTP
Catalyst::Authentication::Credential::Facebook
Catalyst::Controller::MovableType
Catalyst::Plugin::Authentication::Credential::PAM
Catalyst::Plugin::Authorization::Abilities
Catalyst::Plugin::Authorization::CDBI::GroupToken
Catalyst::Plugin::AutoSession
Catalyst::Plugin::ClamAV
Catalyst::Plugin::ConfigLoader::MultiState
Catalyst::Plugin::DBIC::Schema::Profiler
Catalyst::Plugin::DateTime
Catalyst::Plugin::Email::Page
Catalyst::Plugin::FormBuilder
Catalyst::Plugin::FormValidator::Simple::OwnCheck
Catalyst::Plugin::I18N::DBIC
Catalyst::Plugin::Imager
Catalyst::Plugin::MortalForward
Catalyst::Plugin::Session::Store::Memcached::Fast
Catalyst::View::Component::jQuery
CatalystX::Menu::Suckerfish
CatalystX::Menu::Tree
CatalystX::Menu::mcDropdown
Chart::GRACE
Chart::Plot
Chart::Plot::Tagged
Chart::Scientific
Chart::XMGR
Chemistry::Elements
Apache::ChildExit
Chipcard::CTAPI
Cisco::IPPhone
Cisco::Management
Cisco::Reconfig
Cisco::Version
Class::Accessor::WithDefault
Class::AutoAccess
Class::AutoloadCAN
Class::BlackHole
Class::Classless
Class::Classless::C3
Class::Classless::DBI
Class::CompiledC
Class::DBI::DB2
Class::DBI::Loader::DB2
Class::DBI::Plugin::CountSearch
Class::DBI::Plugin::DeepAbstractSearch
Class::DBI::Plugin::DeepAbstractSearchPager
Class::DBI::Storable
Class::DBI::Test::TempDB
Class::DBI::mysql
Class::DataStore
Class::Decorator
Class::Delegate
Class::EHierarchy
Class::Enum
Class::Facade
Class::Handler
Class::Inheritance
Class::Method::Delegate
Class::MethodMapper
Class::Mix
Class::Mixer
Class::Modular
Class::Multimethods
Class::Mutator
Class::NamedParms
Class::ObjectTemplate
Class::ObjectTemplate::DB
Class::ParamParser
Class::ParmList
Class::Pluggable
Class::Std::Slots
Class::Superclasses
Class::Unique
Class::WhiteHole
Class::XPath
Class::orMapper
Class::orMapper::Memcached
Classic::Perl
Clone::Closure
Closure::Loop
Cluster::Similarity
Cmenu
Cobalt::LCD
Code::Class::C
Color::Fade
Color::Mix
Color::Model::Munsell::Util
Color::Model::RGB
Combinator
Commands::Guarded
Compass::Bearing
Compellent::CompCU
Compress::AsciiFlate
Compress::LZO
Compress::PPMd
Config::Augeas::Exporter
Config::Column
Config::File
Config::FreeForm
Config::Hosts
Config::IniRegEx
Config::Interactive
Config::JSON
Config::Model::Backend::Augeas
Config::Perl::V
Config::Plugin::Tiny
Config::Plugin::TinyManifold
Config::Source
Config::TOML
Config::TT2
Config::Tiny::Ordered
Config::Validator
Config::Versioned
Config::YAARG
Config::Yacp
Contextual::Return::Wrapper
Continuus
Control::CLI
ControlX10::CM11
ControlX10::CM17
Convert::ASN1
Convert::Addressbook::Mozilla2Blackberry
Convert::Bencode
Convert::DUDE
Convert::EBCDIC
Convert::MIL1750A
Convert::Number::Greek
Convert::RACE
Convert::Recode
Convert::SciEng
Convert::Translit
Convert::X509
Convert::XText
CopyTree::VendorProof
CopyTree::VendorProof::LocalFileOp
CouchDB::ExternalProcess
CryoTel::CryoCon
Crypt::AllOrNothing
Crypt::AllOrNothing::Util
Crypt::Anubis
Crypt::Blowfish
Crypt::Blowfish_PP
Crypt::CBCeasy
Crypt::Caesar
Crypt::CipherSaber
Crypt::ECB
Crypt::Khazad
Crypt::Loki97
Crypt::Misty1
Crypt::NULL
Crypt::Noekeon
Crypt::OTP
Crypt::OpenSSL::AES
Crypt::OpenSSL::PBKDF2
Crypt::OpenSSL::PKCS12
Crypt::OpenSSL::X509
Crypt::PGP5
Crypt::PGPSimple
Crypt::PW44
Crypt::PassGen
Crypt::Passwd
Crypt::Present
Crypt::RC4
Crypt::RC6
Crypt::Rabbit
Crypt::Rainbow
Crypt::Rijndael::MySQL
Crypt::Rijndael_PP
Crypt::Rot47
Crypt::SEAL2
Crypt::SHAVS
Crypt::SKey
Crypt::SMIME
Crypt::SMimeEngine
Crypt::Serpent
Crypt::Shark
Crypt::SimpleGPG
Crypt::Skip32
Crypt::Skipjack
Crypt::SmbHash
Crypt::Smithy
Crypt::Solitaire
Crypt::Square
Crypt::TEA
Crypt::URandom
Crypt::UnixCrypt
Crypt::UnixCrypt_XS
Crypt::Vigenere
Crypt::XXTEA::CImpl
Curses::UI::POE
Curses::Application
DB::AsKVS
DBD::Neo4p
DBIx::Abstract
DBIx::Admin::BackupRestore
DBIx::Admin::CreateTable
DBIx::Admin::DSNManager
DBIx::Admin::TableInfo
DBIx::BabelKit
DBIx::Brev
DBIx::BulkLoader::Mysql
DBIx::CGITables
DBIx::Class::CompressColumns
DBIx::Class::DynamicSubclass
DBIx::Class::FormTools
DBIx::Class::InflateColumn::Boolean
DBIx::Class::InflateColumn::ISBN
DBIx::Class::InflateColumn::Markup::Unified
DBIx::Class::InflateColumn::Math::Currency
DBIx::Class::InflateColumn::Time
DBIx::Class::InflateColumn::URI
DBIx::Class::Storage::DBI::mysql::backup
DBIx::CodeKit
DBIx::Copy
DBIx::CopyRecord
DBIx::Counter
DBIx::EnumConstraints
DBIx::Factory
DBIx::File2do
DBIx::FileSystem
DBIx::HTML::ClientDB
DBIx::HTML::LinkedMenus
DBIx::HTML::PopupRadio
DBIx::Hash2Table
DBIx::JCL
DBIx::MoCo::Pageset
DBIx::MySperql
DBIx::Mysql::InformationSchema
DBIx::OracleSequence
DBIx::Password
DBIx::Pg::CallFunction
DBIx::Report::Excel
DBIx::Sequence
DBIx::SimpleGoBetween
DBIx::SimplePerl
DBIx::Table2Hash
DBIx::TableReferences::MSSQL
DBIx::Timeout
DBIx::VersionedSchema
DBIx::Wrapper::Config
DBIx::XHTML_Table
DBIx::XML_RDB
DBIx::glueHTML
DBM::DBass
DB_File::DB_Database
DB_File::Lock
DCOP
DCOP::Amarok
DCOP::Amarok::Player
DCOP::Amarok::Playlist
DDL::Oracle
DFA::Kleene
DCE::DFS
DHTMLX::Connector
DMTF::CIM::MOF
Daemon::Simple
Daemon::Whois
Dancer::Logger::Pipe
Dancer::Plugin::Auth::Basic
Dancer::Plugin::Auth::Htpasswd
Dancer::Plugin::Auth::Krb5
Dancer::Plugin::DirectoryView
Dancer::Plugin::I18N
Dancer::Plugin::KossyValidator
Dancer::Plugin::Legacy::Routing
Dancer::Plugin::Preprocess::Markdown
Dancer::Plugin::Preprocess::Sass
Dancer::Plugin::SporeDefinitionControl
Dancer::Session::Redis
Dancer2::Plugin::RoutePodCoverage
Dancer2::Template::MojoTemplate
Data::Abridge
Data::Binder
Data::BitMask
Data::Buffer
Data::ChipsChallenge
Data::CompactDump
Data::Compare::Plugins::JSON
Data::Compare::Plugins::Set::Object
Data::Deep
Data::Denter
Data::Describe
Data::Diff
Data::Dmap
Data::Dumper::HTML
Data::Dumper::LispLike
Data::Favorites
Data::Float
Data::Form::Elements
Data::Generate
Data::Google::Visualization::DataTable
Data::HashArray
Data::HexDump
Data::Hexdumper
Data::Hierarchy::Traverser
Data::ID::Exim
Data::IPV4::Range::Parse
Data::Integer
Data::Iterator
Data::Lazy
Data::Locations
Data::MaskPrint
Data::MultiValuedHash
Data::NestedSet
Data::PABX::ParseLex
Data::Page::Balanced
Data::Page::Viewport
Data::Paginate
Data::Pareto
Data::Password::Entropy
Data::Peek
Data::Queue::Persistent
Data::Range::Compare
Data::Rlist
Data::RoundRobinShared
Data::SExpression::Xen
Data::Scroller
Data::Search
Data::Sheet
Data::SimplePassword
Data::Stack
Data::Table
Data::Table::Excel
Data::Traverse
Data::TreeDraw
Data::Validate
Data::Variant
Data::Walker
Data::XHash
Database::Format::Text
Date::Chinese
Date::CommonFormats
Date::Components
Date::Convert::French_Rev
Date::Darian::Mars
Date::Discordian
Date::Easter
Date::HijriDate
Date::Holidays::AT
Date::Holidays::AU
Date::Holidays::CA
Date::Holidays::CZ
Date::ISO
Date::MSAccess
Date::MSD
Date::Roman
Date::Say::Czech
Date::Simple::Month
Date::Simple::Range
Date::SundayLetter
Date::Tolkien::Shire
DateTime::Calendar::Mayan
DateTime::Duration::Fuzzy
DateTime::Fiscal::Retail454
DateTime::Format::Czech
DateTime::TimeZone::SystemV
DateTime::TimeZone::Tzfile
DateTimeX::AATW
DateTimeX::Fiscal::Fiscal5253
DateTimeX::ymdhms
Db::Ctree
Db::Mediasurface
Debug::Message
Debug::LTrace
Debug::Runopt
Debug::Trace
Debug::Xray
Text::DelimMatch
Devel::CoreStack
Devel::DumpSizes
Devel::Fail::Make
Devel::Fail::MakeTest
Devel::FindGlobals
Devel::Leak
Devel::LeakTrace
Devel::LineName
Devel::Malloc
Devel::Messenger
Devel::Plumber
Devel::RegExp
Devel::SlowBless
Devel::Trace::Method
Devel::TraceMethods
Devel::TrackObjects
Devel::Valgrind::Massif::OutputParser
Device::Arduino::LCD
Device::BCM2835::LCD
Device::CableModem::SURFboard
Device::CableModem::Zoom5341
Device::DSE::Q1573
Device::Delcom::VSI
Device::Dynamixel
Device::ELM327
Device::Gsm
Device::Kiln
Device::Kiln::Orton
Device::MatrixOrbital::GLK
Device::Modem::GSM
Device::PiGlow
Device::Plugwise
Device::Serdisp
Device::USB::MissileLauncher::RocketBaby
Device::Velleman::K8055::Client
Device::Velleman::K8055::Fuse
Device::Velleman::K8055::Server
Device::Velleman::PPS10
Device::Video::PWC
Device::WH1091
Device::WxM2
Diamond
String::DiffLine
Digest::BubbleBabble
Digest::CRC
Digest::DMAC
Digest::EMAC
Digest::Elf
Digest::FP56x1xor
Digest::Haval256
Digest::MD2
Digest::MD4
Digest::MD5
Digest::MD5::File
Digest::MD5::Reverse
Digest::ManberHash
Digest::Perl::MD5
Digest::SHA
Digest::SHA::PurePerl
Digest::SHA3
Digest::Skein
Digest::UserSID
Digest::combined
Digest::ssdeep
Dir::Iterate
Dir::Purge
Dir::Rocknroll
Dir::Which
Directory::Iterator
Dispatch::Profile
Dispatch::Profile::CodeStore
Dispatch::Profile::Dispatcher
Dispatch::Profile::Forwarder
Dist::Zilla::Plugin::ChangelogFromGit
Dist::Zilla::Plugin::MojibakeTests
Dist::Zilla::Plugin::Rsync
Dist::Zilla::Plugin::SpellingCommonMistakesTests
Dist::Zilla::Plugin::WSDL
Dist::Zilla::PluginBundle::Author::LXP
Dist::Zilla::PluginBundle::TestingMania
Domain::Register::DomainShare
Domain::Register::TK
Encode::BetaCode
Encode::Detect::CJK
Encode::DosHebrew
Encode::EUCJPMS
Encode::Guess::Educated
Encode::HEBCI
Encode::TECkit
End
Enterasys::NetSight
Enumeration
Env::Bash
Env::Modulecmd
Env::Path
Errno::AnyString
Evented::Configuration
Example::XS::FasterHashes
Excel::Table
Excel::Template::Element::Cell::AutoSize
Exception::Base
Exception::Class::Nested
Exception::System
Exherbo::Packager
Exporter::Tidy
ExtUtils::DynaGlue
ExtUtils::configPL
FCGI::Daemon
FCGI::EV
FCGI::IIS
FCGI::ProcManager::Dynamic
FLV::AudioExtractor
FSM::Simple
FUSE::Client
FUSE::Server
FWS::Lite
Festival::Client
Festival::Client::Async
File::BSDGlob
File::Basename::Object
File::BasicFlock
File::CacheDir
File::CachingFind
File::Canonicalizer
File::Copy::Recursive
File::CounterFile
File::Data
File::FilterFuncs
File::Find::Closures
File::Find::Node
File::Find::Rule::XPath
File::Glob::Windows
File::Index
File::LckPwdF
File::lockf
File::Monitor::Lite
File::MultilineGrep
File::MultipleDiff
File::PlainPath
File::Queue
File::RandomGenerator
File::RelDir
File::Remote
File::Repl
File::Rsync
File::Searcher
File::Searcher::Interactive
File::Signature
File::Sort
File::Stat::Trigger
File::Stream
File::Tail
File::Tail::App
File::Tail::Multi
File::UStore
File::Unpack
File::VirtualPath
File::Xcopy
File::chmod
Filesys::Df
Filesys::DfPortable
Filesys::DiskFree
Filesys::DiskSpace
Filesys::Ext2
Filesys::SamFS
Filesys::SmbClientParser
Filesys::Statvfs
Filesys::Tree
Filter::Arguments
Filter::BoxString
Filter::CommaEquals
Filter::PerlTags
Filter::PerlTags::Extra
Filter::QuasiQuote
Filter::Trigraph
Filter::Unpound
Finance::Amortization
Finance::Bank::DE::DTA::Create
Finance::Bank::DE::NetBank
Finance::Bank::US::INGDirect
Finance::BankVal::UK
Finance::Currency::Convert::BChile
Finance::Currency::Convert::Custom
Finance::Currency::Convert::DnB
Finance::FXCM::Simple
Finance::InteractiveBrokers::TWS
Finance::OFX::Parse::Simple
Finance::Performance::Calc
Finance::Quote::Sberbank
Finance::QuoteOptions
Finance::RawMaterialPrice
Finance::SE::OMX
Finance::TA
Finance::TickerSymbols
Finance::btce
Find::Lib
FindBin::libs
Font::FNT
Font::GlyphNames
Font::TFM
For::Else
FormValidator::Simple::Plugin::Math
Format::Human::Bytes
Format::LongNumber
Fortran::Namelist
Funifs
GD::3DBarGrapher
GD::Barcode::Code93
GD::Barcode::Image
GD::Graph::Polar
GD::Image::AnimatedGif
GD::Image::CopyIFS
GD::Image::Orientation
GD::Image::Thumbnail
GD::Map
GD::Persian
GD::Tab::Ukulele
GD::Thumbnail
GD::Window
GDS2
GMail::Checker
GPS::Babel
GPS::Garmin::Connect
GPS::SpaceTrack
GSM::Nbit
Games::Alak
Games::Baseball::Scorecard
Games::Cards::Poker
Games::Dice
Games::Dice::Probability
Games::Dissociate
Games::FEAR::Log
Games::Go::AGATourn
Games::Hack::Live
Games::Hack::Patch::i686
Games::Hack::Patch::x86_64
Games::Multiplayer::Manager
Games::Roguelike::Caves
Games::SGF::Tournament
Games::Score
Games::Sudoku::CPSearch
Games::Sudoku::General
Games::Sudoku::Solver
Games::WordFind
Ganglia::Gmetric
GappX::FileTree
Gas::Prices
News::Gateway
Geo::BUFR
Geo::CEP
Geo::Caching
Geo::Calc
Geo::Coder::Cloudmade
Geo::Coder::YahooJapan
Geo::Converter::dms2dd
Geo::Coordinates::Convert
Geo::Coordinates::ETRSTM35FIN
Geo::Coordinates::Parser
Geo::Coordinates::Transform
Geo::Coordinates::UTM
Geo::Distance
Geo::ECEF
Geo::Ellipsoids
Geo::Google::MapObject
Geo::Google::StaticMaps
Geo::IATA
Geo::ICAO
Geo::IP2Location
Geo::Inverse
Geo::PostalAddress
Geo::Query
Geo::Spline
Geo::SypexGeo
Geo::WeatherNOAA
Geography::Countries::LatLong
Geography::States
Geometry::Formula
Gerrit::REST
Getargs::Mixed
Getopt::ArgvFile
Getopt::CommandLineExports
Getopt::EvaP
Getopt::FileConfig
Getopt::GUI::Long
Getopt::GetArgs
Getopt::Mixed
Getopt::Mixed::Help
Getopt::Regex
Getopt::Simple
Getopt::Tabular
Getopt::Tiny
Getopt::XML
GitHub::Jobs
Google::GeoCoder::Smart
Google::SAML::Request
Google::SAML::Response
GoogleIDToken::Validator
Graph::ChartSVG
Graph::Clique
Graph::Kruskal
Graph::Matching
Graph::Writer::Cytoscape
Graphics::ColorPicker
Graphics::HotMap
Graphics::MNG
Graphics::Plotter
Grid::Transform
Growl::GNTP
Gtk2::Ex::FormFactory::TimeEntry
Gtk2::GladeXML::OO
Gtk2::ImageView
Gtk2::SourceView
Gtk2::TrayManager
Gtk2::Unique
Guitar::Scale
HPUX::LVM
HPUX::Pstat
HPUX::SDUX
HTML::ActiveLink
HTML::AsText::Fix
HTML::BBReverse
HTML::BarGraph
HTML::Breadcrumbs
HTML::CalendarMonthDB
HTML::ContentExtractor
HTML::Copy
HTML::Dashboard
HTML::Debug
HTML::DragAndDrop
HTML::Embellish
HTML::Encoding
HTML::Entities::ImodePictogram
HTML::Entities::Interpolate
HTML::Entities::Recursive
HTML::EntityReference
HTML::ExtractMain
HTML::FormHandlerX::Form::Contact
HTML::FormHandlerX::Form::Login
HTML::FormTemplate
HTML::Formulate
HTML::FromArrayref
HTML::HTML5::Sanity
HTML::LinkExtractor
HTML::Menu::TreeView
HTML::Miner
HTML::PopupTreeSelect::Dynamic
HTML::QuickCheck
HTML::Revelation
HTML::ScriptLoader
HTML::SimpleLinkExtor
HTML::SimpleParse
HTML::SocialMedia
HTML::StripTags
HTML::Subtext
HTML::Table
HTML::Tabulate
HTML::TagTree
HTML::TagUtil
HTML::Tagset
HTML::Template::Compiled::Plugin::Comma
HTML::Template::Compiled::Plugin::LineBreak
HTML::Template::Convert::TT
HTML::Template::Set
HTML::Timeline
HTML::Tooltip::Javascript
HTML::WidgetValidator::Widget::PixivEmbedFeature
HTML::WidgetValidator::Widget::TegakiBlog
HTML::WikiConverter::GoogleCode
HTML::WikiConverter::Txt2tags
HTML::WikiConverter::Wikispaces
HTML::WikiConverter::XWiki
HTTP::Body::MultiPart::Extend
HTTP::Browscap
HTTP::Cache::Transparent
HTTP::Cookies::Find
HTTP::Cookies::Omniweb
HTTP::Cookies::Safari
HTTP::Cookies::iCab
HTTP::CryptoCookie
HTTP::DAV::Nginx
HTTP::GHTTP
HTTP::HeaderParser::XS
HTTP::ProxyTest
HTTP::QuickBase
HTTP::Request::Form
HTTP::Response::CGI
HTTP::Sessioniser
HTTP::SimpleLinkChecker
HTTP::Size
HTTP::Tiny::SPDY
HTTP::WebTest::Plugin::Sticky
HTTPD::Log::Filter
Hadoop::Admin
Ham::APRS::DeviceID
Ham::APRS::LastPacket
Ham::Locator
Ham::Packet::DXSpider
Ham::Reference::Callook
Ham::Reference::Phonetics
Ham::Reference::QRZ
Ham::Reference::Qsignals
Ham::Reference::Solar
Hardware::SensorsParser
Hardware::Simulator::MIX
Hardware::Vhdl::Lexer
Hash::AsObject
Hash::CoerceToArray
Hash::Identity
Hash::NoVivify
Hash::Transform
Heap::MinMax
Hey::heyPass
Hook::Scope
Hook::PrePostCall
Hostfile::Manager
I18N::Charset
IBM::LoadLeveler
ICS::Simple
IMAP::Admin
IMAP::Client
IO::BufferedSelect
IO::EventMux
IO::File::Cycle
IO::File::WithFilename
IO::NestedCapture
IO::Pipe::Producer
IO::Prompt::Hooked
IO::React
IO::Simple
IO::Socket::ByteCounter
IO::Socket::INET::Daemon
IO::Socket::PortState
IO::Socket::PortState::cPanel
IO::Stream::Crypt::RC4
IO::Stream::Proxy::HTTPS
IO::Tee
IO::Zlib
IP::Anonymous
IP::Location
IP::World
IPC::Filter
IPC::Mmap::Share
IPC::Semaphore::Concurrency
IPC::Session
IPC::SharedCache
IPC::Shm::Simple
IPC::Signal
IPC::XPA
IPDevice::Allnet::ALL4000
IPTables::libiptc
IPsonar
Image::BMP
Image::DCMTK
Image::DeAnim
Image::Dot
Image::EXIF::DateTime::Parser
Image::Empty
Image::GD::Thumbnail
Image::IPTCInfo
Image::Imlib2
Image::Index::LaTeX
Image::Info::XS
Image::Kimdaba
Image::Magick::NFPADiamond
Image::Magick::Square
Image::Magick::Thumbnail::NotFound
Image::Magick::Tiler
Image::Maps::Plot::FromLatLong
Image::Maps::Plot::FromPostcode
Image::Mate
Image::MetaData::GQview
Image::ParseGIF
Image::Placeholder
Image::Resize::OpenCV
Image::Size
Image::SubImageFind
Image::Thumbnail
Image::Tileset
Image::Timeline
Image::ValidJpeg
Image::WebP
Image::XWD
Image::Xbm2bmp
Imager::TimelineDiagram
Ingres::Utility::IIMonitor
Ingres::Utility::IINamu
Ingres::Utility::Netutil
Inline::Befunge
Inline::WSC
InterMine::TypeLibrary
Ipmitool
Iterator::ToArray
JIRA::Client::Automated
JIRA::REST
JSONP
Jabber::PubSub::JEAI
Jabber::RPC::HTTPgate
Jamila
JavaScript::Console
JavaScript::Sprockets
JavaScript::Squish
Javascript::Closure
Javascript::MD5
Javascript::SHA1
Geo::KML::PolyMap
LEGO::RCX
LJ::GetCookieSession
LSF::Hosts
LW4::Reader
LWP::UserAgent::Anonymous
LWP::UserAgent::ExponentialBackoff
LWP::UserAgent::RandomProxyConnect
Language::Befunge::Vector::XS
Language::DATR::DATR2XML
Language::Dashrep
Language::Frink::Eval
Language::MPI
Language::Ook
Language::Prolog::Sugar
Lemonldap::NG::Cli
Lemonldap::Portal::Authntsso
Lemonldap::Portal::CAS
Lemonldap::Portal::Cda
Lemonldap::Portal::Session
Lemonldap::Portal::Sslsso
Lexical::Persistence
LightWaveRF
Lingua::AF::Numbers
Lingua::AFR::Numbers
Lingua::AFR::Word2Num
Lingua::AR::Abgad
Lingua::Any::Numbers
Lingua::CES::Num2Word
Lingua::CES::Word2Num
Lingua::ConText
Lingua::DE::Tagger
Lingua::DE::TypoGenerator
Lingua::DE::Wortschatz
Lingua::DEU::Num2Word
Lingua::DEU::Word2Num
Lingua::DxExtractor
Lingua::EL::Poly2Mono
Lingua::EN::AR
Lingua::EN::BioLemmatizer
Lingua::EN::Conjugate
Lingua::EN::Fathom
Lingua::EN::Infinitive
Lingua::EN::Inflect
Lingua::EN::MatchNames
Lingua::EN::Namegame
Lingua::EN::Nickname
Lingua::EN::Numbers::Ordinate
Lingua::EN::Nums2Words
Lingua::EN::Sentence::Offsets
Lingua::EN::StopWordList
Lingua::EN::TitleParse
Lingua::EN::Tokenizer::Offsets
Lingua::ENG::Inflect
Lingua::ENG::Numbers
Lingua::ENG::Word2Num
Lingua::EO::Supersignoj
Lingua::ES::Numeros
Lingua::EUS::Numbers
Lingua::EUS::Word2Num
Lingua::FI::Inflect
Lingua::FR::Numbers
Lingua::FRA::Nums2Words
Lingua::FRA::Word2Num
Lingua::HU::Numbers
Lingua::IND::Nums2Words
Lingua::IND::Words2Nums
Lingua::ITA::Numbers
Lingua::ITA::Word2Num
Lingua::Ident
Lingua::Identify::Blacklists
Lingua::Ispell
Lingua::JA::Moji
Lingua::JA::Number
Lingua::JA::Sort::JIS
Lingua::JPN::Number
Lingua::JPN::Word2Num
Lingua::KO::Romanize::Hangul
Lingua::Lexicon::IDP
Lingua::ManagementSpeak
Lingua::NL::Numbers
Lingua::NL::Numbers::GroeneBoekje
Lingua::NLD::Numbers
Lingua::NLD::Word2Num
Lingua::NOR::Num2Word
Lingua::NOR::Word2Num
Lingua::NegEx
Lingua::Orthon
Lingua::POL::Numbers
Lingua::POL::Word2Num
Lingua::POR::Nums2Words
Lingua::POR::Words2Nums
Lingua::PT::Hyphenate
Lingua::PT::Inflect
Lingua::PT::Words2Nums
Lingua::Preferred
Lingua::RO::Numbers
Lingua::RU::Antimat
Lingua::RU::Charset
Lingua::RU::Inflect
Lingua::RU::Sklon
Lingua::RUS::Number
Lingua::RUS::Word2Num
Lingua::Romana::Perligata
Lingua::SA
Lingua::SPA::Numeros
Lingua::SPA::Word2Num
Lingua::SV::Numbers
Lingua::SWE::Num2Word
Lingua::SWE::Word2Num
Lingua::Sentence
Lingua::Stem::Fr
Lingua::Stem::Snowball::Da
Lingua::Stem::Snowball::Lt
Lingua::TH::Segmentation
Lingua::TR::Hyphenate
Lingua::TR::Numbers
Lingua::Translate::Bing
Lingua::Translate::Google
Lingua::UK::Translit
Lingua::Word2Num
Lingua::ZH::CCDICT
Lingua::ZH::HanConvert
Lingua::ZH::MMSEG
Lingua::ZH::WordSegment
Lingua::ZHO::Numbers
Lingua::ZHO::Word2Num
Lingua::Zompist::Barakhinei
Lingua::Zompist::Cadhinor
Lingua::Zompist::Cuezi
Lingua::Zompist::Kebreni
Lingua::Zompist::Verdurian
Linux::ACL
Linux::DVB::DVBT::TS
Linux::DesktopFiles
Linux::Ext2::Attributes
Linux::KernelSort
Linux::MemInfo
Linux::Pid
Linux::SysInfo
Linux::hddtemp
List::Comprehensions
List::Flatten::Recursive
List::Intersperse
List::MRU
List::Pairwise
List::Part
List::Rotation::Cycle
List::Util::Superpositions
List::Util::WeightedChoice
List::Util::WeightedRoundRobin
Livelink::DAV
Locale::CA
Locale::Currency::Format
Locale::Maketext::Lexicon::DBI
Locale::Nationality::en
Locale::PGetText
Log::Accounting
Log::Accounting::Sendmail
Log::Any::Adapter::FileHandle
Log::Any::Adapter::Mojo
Log::AutoDump
Log::Dispatch::Email::Sendmail
Log::Dispatch::FogBugz
Log::Dispatch::Jabber
Log::Dispatch::ZMQ
Log::Facile
Log::JSON
Log::Localized
Log::Log4perl::Appender::Fluent
Log::Log4perl::Appender::Socket::UNIX
Log::Log4perl::Appender::SpreadSession
Log::Rolling
Log::SelfHistory
Log::Statistics
Log::Topics
Log::TraceMessages
Log::WithCallbacks
Log4Perl::ImportHandle
CGI::LogCarp
Logfile::Read
Logfile::Tail
Logger::Simple
Loop::Flow::Object
Lucene
Lucene::Search::Highlight
Lyrics::Fetcher::Google
Lyrics::Fetcher::LyricsDownload
MIDI::ALSA
MIDI::Praxis::Variation
MIDI::Tweaks
MIME::Lite::TT::Japanese
MIME::Multipart::Parse::Ordered
MLDBM::TinyDB
MP3::ID3v1Tag
MP3::M3U
MP3::Merge
MP4::Info
MRTG::Config
MRTG::Parse
MSDOS::Attrib
MSDOS::Descript
MVS::VBFile
Mac::AppleEvents::Simple
Mac::Apps::Anarchie
Mac::Apps::Launch
Mac::Apps::MacPGP
Mac::Apps::PBar
Mac::Comm::OT_PPP
Mac::Errors
Mac::FileSpec::Unixish
Mac::Growl
Mac::OSVersion
Mac::Pasteboard
Mac::PropertyList::XS
Mac::SysProfile
Mac::iPhoto::Shell
MacOSX::Alias
Mafia
Mail::Alias
Mail::Box::Parser::C
Mail::Convert::Mbox::ToEml
Mail::Field::Received
Mail::IMAP2SMS
Mail::POP3Client
Mail::Postfixadmin
Mail::Procmail
Mail::QmailRemote
Mail::QmailSend::MultilogParser
Mail::RoundTrip
Mail::SPF::Iterator
Mail::Sendmail
Mail::Transport::Dbx
Mail::Verify
Mail::Vmailmgr
Markdown::Foswiki
Markup::Unified
Math::Amoeba
Math::Approx
Math::Approx::Symbolic
Math::BaseCalc
Math::Bezier
Math::Bezier::Convert
Math::Business::BlackScholes
Math::CDF
Math::Calc::Euro
Math::CheckDigits
Math::ContinuedFraction
Math::ConvexHull
Math::ErrorPropagation
Math::Evol
Math::Fibonacci::Phi
Math::Fleximal
Math::Fractal::Curve
Math::FresnelZone
Math::Function::Roots
Math::GSL::Linalg::SVD
Math::Geometry
Math::Geometry::GPC
Math::Geometry::Multidimensional
Math::Geometry::Planar
Math::Geometry::Voronoi
Math::GoldenBigMath
Math::Gradient
Math::Group::Thompson
Math::Libm
Math::Logic
Math::Logic::Predicate
Math::Lsoda
Math::MagicSquare::Generator
Math::Matrix
Math::MatrixBool
Math::MatrixReal
Math::MatrixReal::Ext1
Math::MultiplicationTable
Math::NoCarry
Math::Orthonormalize
Math::Pandigital
Math::PercentChange
Math::Polygon::Tree
Math::Polyhedra
Math::Polynomial::Multivariate
Math::Polynomial::Solve
Math::Prime::FastSieve
Math::Prime::TiedArray
Math::Project
Math::Project3D::Plot
Math::Quaternion
Math::Random::Brownian
Math::Random::SkewNormal
Math::Random::TT800
Math::Round
Math::SigFigs
Math::SparseMatrix::Operations
Math::Spline
Math::SymbolicX::Inline
Math::TamuAnova
Math::Taylor
Math::Telephony::ErlangB
Math::Telephony::ErlangC
Math::VecStat
Math::VectorReal
Math::ematica
MathML::Entities
MediaWiki::API
MediaWiki::Bot::Shell
Mediainfo
Palm::Memo32
Memoize::ExpireLRU
Memoize::Memcached
PDL::Meschach
Message::Passing::Output::PocketIO
Mewsoft::Pagination
Minecraft::RCON
Mobile::Messaging::ParlayX
Mobile::Wurfl
ModPerl::PackageRegistry
Model3D::Poser::GetStringRes
Model3D::WavefrontObject
Modem::Vgetty
Module::AutoINC
Module::Build::PM_Filter
Module::ConfigureRequires
Module::DynamicSubModule
Module::Install::DBICx::AutoDoc
Module::Install::Debian
Module::Metadata::Changes
Module::Pragma
Module::Recursive::Require
Module::Release::Git
Module::Selector
Module::Starter::Plugin::DebPackage
Module::Versions
MojoX::Auth::Simple
MojoX::JSON::XS
MojoX::Log::Declare
MojoX::Log::Dispatch
MojoX::Moose::Controller
MojoX::Redis
MojoX::Renderer::HTP
MojoX::Session::Store::Libmemcached
MojoX::ValidateHeadLinks
Mojolicious::Command::generate::bootstrap
Mojolicious::Plugin::Authorization
Mojolicious::Plugin::BasicAuth
Mojolicious::Plugin::BasicAuthPlus
Mojolicious::Plugin::ConfigRoutes
Mojolicious::Plugin::DBIxTransactionManager
Mojolicious::Plugin::Directory
Mojolicious::Plugin::Human
Mojolicious::Plugin::Mason1Renderer
Mojolicious::Plugin::Mason2Renderer
Mojolicious::Plugin::Message::Locale
Mojolicious::Plugin::Mobi
Mojolicious::Plugin::Redis
Mojolicious::Plugin::SMS
Mojolicious::Plugin::SQLMaker
Mojolicious::Plugin::ServerSession
Mojolicious::Plugin::TimeAgo
Mojolicious::Plugin::ToolkitRenderer
Mojolicious::Plugin::YamlConfig
MonetDB::CLI
MonetDB::CLI::MapiXS
MoneyWorks
MongoDB::Admin
Monotone::AutomateStdio
MooseX::CachingProxy
MooseX::CoercePerAttribute
MooseX::Documenter
MooseX::Role::Flyweight
MooseX::Struct
MooseX::Types::IPv4
MooseX::Types::XMLSchema
MouseX::Params::Validate
Mozilla::ConsoleService
Mozilla::DOM::ComputedStyle
Mozilla::ObserverService
Mozilla::PromptService
Mozilla::nsID
Locale::Msgcat
Music::Chord::Namer
MySQL::Backup
MySQL::Handler
MySQL::Log::ParseFilter
MySQL::Packet
MySQL::QueryMulti
MySQL::TableInfo
Mysql::DBLink
Mysql::PrettyPrinter
NCBIx::BigFetch
Nagios::Plugin::SNMP
Net::AOLIM
Net::ASN
Net::Abuse::Utils
Net::Address::Ethernet
Net::Akismet
Net::Amazon::AWSSign
Net::Amazon::S3::Tools
Net::Amazon::Thumbnail
Net::Axigen
Net::Blacklist::Client
Net::CIDR
Net::CIDR::Compare
Net::CIDR::ORTC
Net::Camera::Edimax::IC1500
Net::CascadeCopy
Net::Clickatell
Net::DHCP::Watch
Net::DHCPClient
Net::DHCPv6::DUID::Parser
Net::DLookup
Net::DNS::CloudFlare::DDNS
Net::DNS::DurableDNS
Net::DNS::DynDNS
Net::DNS::Dynamic::Adfilter
Net::DNS::Nslookup
Net::DNS::SEC::Validator
Net::DNS::ValueDomain::DDNS
Net::Dnet
Net::Dogstatsd
Net::EMI::Common
Net::FTP::File
Net::FTP::Versioning
Net::Goofey
Net::GrowlClient
Net::HTTPTunnel
Net::Hesiod
Net::ICB
Net::ICQV5
Net::ICQV5CD
Net::ILO
Net::IMAP::Simple::Gmail
Net::IP::LPM
Net::IP::Match::XS
Net::IP::Util
Net::IP::XS
Net::IPAddress::Filter
Net::IPAddress::Filter::IPFilterDat
Net::IRR
Net::Jabber::Bot
Net::LDAP::Filter::SQL
Net::LMTP
Net::LPR
Net::LibIDN
Net::LibIDN2
Net::Lookup::DotTel
Net::MAC::Vendor
Net::Milter
Net::NAT::PMP
Net::NTPTime
Net::Nessus::ScanLite
Net::Nessus::XMLRPC
Net::NetSend
Net::Netmask
Net::OpenSRS::Email_APP
Net::OpenVPN::Manage
Net::PJLink
Net::Pavatar
Net::Printer
Net::QMQP
Net::QMTP
Net::RGTP
Net::RULI
Net::Radius::Client
Net::Random::QRBG
Net::SMS::160By2
Net::SMS::2Way
Net::SMS::BulkSMS
Net::SMS::CSNetworks
Net::SMS::Clickatell
Net::SMS::MessageNet
Net::SMS::MunduSMS
Net::SMS::O2_DE
Net::SMS::TMobile::UK
Net::SMS::TextMagic
Net::SMS::WAY2SMS
Net::SMTP::IPMM
Net::SMTP::Pipelining
Net::SMTP::TLS
Net::SNMP::Util
Net::SNMP::Vendor
Net::SSH
Net::SSH::Expect
Net::Server::Mail::ESMTP::STARTTLS
Net::Snarl
Net::Squid::Auth::Plugin::SimpleLDAP
Net::Stomp::Receipt
Net::SynchroEdit::Service
Net::Syslog
Net::Syslogd
Net::TCP::PtyServer
Net::Telnet
Net::Telnet::Cisco::IOS
Net::Telnet::Trango
Net::Traceroute
Net::Traceroute6
Net::TrackUPS
Net::UKDomain::Nominet::Automaton
Net::UPCDatabase
Net::Vypress::Chat
Net::WebCL
Net::Whois::IP
Net::ZooKeeper::Semaphore
Net::addrinfo
Net::eBay
Net::iContact
Net::uwsgi
NetAddr::IP::Find
NetAthlon2::RAW
NetDNA
NetServer::Generic
News::Article::NoCeM
News::NNTP
News::Newsrc
News::Search
NexStarCtl
Nginx::Log::Entry
Nginx::Log::Statistics
Nginx::Module::Gallery
Noid
Novel::Robot
Number::Encode
Number::Format
Number::Object::Plugin::Tax::AU::GST
Number::Phone::Normalize
Number::Phone::PT
Number::Phone::US
Number::WithError
Number::WithError::LaTeX
OAuth::Consumer
OAuth::Simple
OCS::Client
OO::InsideOut
OS2::FTP
OSDial
Kernel::Modules::TicketAutoAssignment
Object::AutoAccessor
Object::GlobalContainer
Object::Import
Object::New
Object::Realize::Later
Object::Signature::Portable
Ogg::LibOgg
Ogg::Theora::LibTheora
Ogg::Vorbis::Header
Omega::DP41::Data::Current
Opcodes
Apache::OpenIndex
OpenMuseum
OpenOffice::PerlPoint
Oracle::DML
Oracle::Debug
Oracle::Loader
Oracle::SQLLoader
Oracle::Schema
Oracle::Sqlldr
Oracle::Trigger
Orignal
Number::OutlineNumber
OzDB
P
PCL::Simple
PDF::FDF::Simple
PDF::Haru
PDF::Kit
PDL::IO::Nifti
PDL::NetCDF
PGObject
PGObject::Simple
PGObject::Simple::Role
PGObject::Type::BigFloat
PGObject::Type::DateTime
PGP::Sign
PGPLOT
PGPLOT::Simple
PHP::Serialization::XS
PHP::Session::DB
Finance::Bank::PNC
POD2::ES
POE::API::Hooks
POE::Component::Client::SMTP
POE::Component::Daemon::Win32
POE::Component::Enc::Flac
POE::Component::Enc::Ogg
POE::Component::Growl
POE::Component::IRC::Plugin::Hello
POE::Component::IRC::Plugin::Infobot
POE::Component::IRC::Plugin::Logger::Irssi
POE::Component::IRC::Plugin::Seen
POE::Component::IRC::Plugin::WWW::Reddit::TIL
POE::Component::IRC::Plugin::WWW::Weather::US
POE::Component::IRC::Plugin::WubWubWub
POE::Component::Pool::Thread
POE::Component::RSS
POE::Component::SubWrapper
POE::Component::UserBase
POE::Filter::ErrorProof
POE::Filter::FSSocket
POE::Filter::LZW::Progressive
POE::Filter::SSL
POSIX::SchedYield
POSIX::Socket
Package::Data::Inheritable
Palm::Keyring
Palm::ListDB::Writer
Palm::ThinkDB
Panda::Export
Parallel::DataPipe
Parallel::Fork::BossWorkerAsync
Parallel::Queue
Parallel::Supervisor
Parallel::parallel_map
Params::Attr
Params::Dry::Declare
Parse::AccessLog
Parse::Apache::ServerStatus
Parse::Arcconf
Parse::CPinfo
Parse::Colloquy::Bot
Parse::Flash::Cookie
Parse::GEDA::Gschem
Parse::HP::ACU
Parse::ISF
Parse::Nessus::ENX
Parse::Nessus::NBE
Parse::Nessus::Plugin
Parse::PlainConfig
Parse::RPN
Parse::SSH2::PublicKey
Parse::Snort
Parse::Syslog
Parse::Tektronix::ISF
Parse::Tokens
Parse::YARA
Parse::cfggen
Parser::Combinators
Parser::IPTables::Save
Passwd::Samba
Passwd::Unix
PayflowPro
Penguin::Easy
Perf::ARM
Perl::Critic::Policy::CodeLayout::ProhibitSpaceIndentation
Perl::ImportReport
Perl6::Classes
Perl6::Feeds
Perl6::Interpolators
Perl6::Parameters
Perl6::Slurp::Interpret
Perl6::Variables
PerlIO::gzip
PerlIO::locale
PerlIO::unicodeeol
PerlIO::via::CBC
PerlIO::via::Logger
PerlIO::via::SeqIO
PerlIO::via::gzip
Image::Magick
PerlMongers::Bangalore
PerlMongers::Warszawa
PerlX::QuoteOperator
Persistent::DBI
Persistent::LDAP
Persistent::MySQL
Persistent::Oracle
Persistent::Sybase
Persistent::mSQL
Pg::BulkCopy
Pg::hstore
Physics::Particles
Physics::Springs
Physics::Springs::Friction
Pickles::Dispatcher::Auto
PidFile
Pingdom::Client
Plack::App::Gearman::Status
Plack::App::OpenVPN::Status
Plack::Middleware::AMF
Plack::Middleware::Access
Plack::Middleware::AccessLog::Structured
Plack::Middleware::AccessLog::Structured::ZeroMQ
Plack::Middleware::Debug::Log4perl
Plack::Middleware::ESI
Plack::Middleware::GitStatus
Plack::Middleware::JSON::ForBrowsers
Plack::Middleware::Session::SerializedCookie
Pod::HTML2Pod
Pod::InDesign::TaggedText
Pod::InDesign::TaggedText::TPR
Pod::LaTeX
Pod::POM::View::Restructured
Pod::Pdf
Pod::ROBODoc
Pod::Simple::Wiki::Wikka
Pod::Snippets
Pod::Stupid
Pod::Weaver::Plugin::StopWords
Pod::Weaver::PluginBundle::Author::LXP
Pod::Weaver::Section::Requires
Pod::WikiText
Pod::Rtf
Polycom::Config::File
PostScript::Calendar
PostScript::Simple::Table
Postgres::Handler
PowerDNS::Backend::MySQL
PowerDNS::Control::Client
PowerDNS::Control::Server
PrimeTime::Report
Printer::HP::Display
Proc::Fork
Proc::Forkfunc
Proc::Forking
Proc::Forkmap
Proc::PID::File::Fcntl
Proc::ParallelLoop
Proc::Queue
Proc::Reliable
Proc::SafePipe
Proc::Short
Proc::Simple
Proc::Spawn
Proc::SyncExec
Proc::Wait3
ProgressBar::Stack
Proliphix
Prolog::Utility::FromPerl
Ptty
Puppet::Any
Puppet::Log
Puppet::Tidy
Quantum::Usrn
Queue::Beanstalk
Queue::Worker
Quota
Quota::OO
RADIUS::UserFile
RADIUS::XMLParser
RAS::AS5200
RAS::HiPerARC
RAS::PortMaster
RDF::Query::Client
RDF::Trine::Serializer::SparqlUpdate
RDF::TrineX::RuleEngine::Jena
REST::Google::Apps::EmailSettings
REST::Google::Apps::Provisioning
RFID::ISO15693::Tag
RNA::HairpinFigure
RPC::EPC::Service
RPC::Oracle
RPC::XML::Deparser::XS
RPC::XML::Parser::XS
RPG::Dice
RPM::Make::DWIW
RRD::Editor
RT::Action::UpdateIcestack
RT::Authen::Federation
RT::Extension::MandatoryFields
RT::Extension::SkipQuotes
RTF::Tokenizer
RTG::Report
RTMP::Client
RTSP::Lite
RTx::AttachmentZip
RTx::BecomeUser
Rcs
Redis::Bayes
Redis::Queue
Redis::hiredis
Redmine::Stat
Regexp::Common::debian
Regexp::ERE
Regexp::Keywords
Regexp::NumRange
Regexp::Shellish
Regexp::Tr
Regexp::Wildcards
Relations
ReleaseAction
Religion::Islam::PrayTime
Religion::Islam::PrayerTimes
Religion::Islam::Qibla
Religion::Islam::Quran
Remedy::ARSTools
Replication::Recall::DBServer
Resources
Robotics::IRobot
Roman
Rose
Rose::DBx::Object::Cached::CHI
Rose::DBx::Object::Cached::FastMmap
Rose::DBx::RegistryConfig
Rose::URI
SymObj
SCUBA::Table::NoDeco
SGI::FAM
SMS::Send::DE::Sipgate
SMS::Send::RedOxygen
SMS::Send::Smstrade
SMS::Send::TW::HiAir
SMS::Send::TW::PChome
SMS::Send::TW::Qma
SMS::Send::TW::ShareSMS
SMS::Send::UK::Kapow
SMS::Send::US::TMobile
SMS::Send::Wadja
SMS::Server::Tools
SNMP::Agent
SNMP::BridgeQuery
SNMP::Persist
SOAP::UMRA
SQL::Abstract::Complete
SQL::Beautify
SQL::Object::Interp
SQL::Smart
SQLib
SVG::Calendar
SVG::Metadata
SVG::Template::Graph
SVN::Dumpfilter
SVN::Notify::Filter::AuthZMail
SVN::Notify::Filter::EmailFlatFileDB
SWF::ForcibleConverter
SWIFT::Factory::ApplicationHeader
SWIFT::Factory::BasicHeader
SWIFT::Factory::Tag::Tag15
SWIFT::Factory::Tag::Tag17
SWIFT::Factory::Tag::Tag17A
SWIFT::Factory::Tag::Tag17T
SWIFT::Factory::Tag::Tag17U
SagePay::XORForm
Scalar::Number
Scalar::Vec::Util
Schedule::At
Schedule::Cron
Schedule::Match
Schedule::Week
Scope::Upper
Script::Daemonizer
Search::ContextGraph
Search::InvertedIndex::Simple
Search::InvertedIndex::Simple::BerkeleyDB
Search::VectorSpace
Search::WuManber
AltaVista::SearchSDK
Security::CVSS
Sendmail::AccessDB
Sendmail::Milter
Ser::BinRPC
Set::Crontab
Set::CrossProduct
Set::DynamicGroups
Set::Files
Set::Formula
Set::Functional
Set::Groups
Set::IntRange
Set::IntSpan
Set::IntSpan::Island
Set::IntervalTree
Set::Partition
Set::Window
SharePoint::SOAPHandler
Shell::Cmd
Shell::POSIX::Select
Shell::Parser
Shell::Source
ShellScript::Env
Signal::StackTrace
Silly::StringMaths
Slay::Makefile::Gress
Sledge::Plugin::BeforeOutput
Sledge::Plugin::DebugLeakChecker
Sledge::Plugin::Prototype
Sledge::Plugin::QueryHash
Sledge::Template::ClearSilver::I18N
SmarTalk
Soar::WM::Grapher
Socket::Mmsg
Socket::PassAccessRights
Socket6
Softref
Solaris::ACL
Solaris::Lgrp
Solaris::Modinfo
Sort::ArbBiLex
Sort::Bucket
Sort::DataTypes
Sort::External
Sort::Hash::Values
Sort::Radix
Spectrum::CLI
Sphinx::Search
Sport::Analytics::SimpleRanking
Spreadsheet::Read
Spreadsheet::ReadSXC
Spreadsheet::WriteExcel::Worksheet::SheetProtection
Spreadsheet::XML_to_XLS
Spreadsheet::XlateExcel
Sprite
Stat::lsMode
Statistics::Autocorrelation
Statistics::Benford
Statistics::CalinskiHarabasz
Statistics::Cluto
Statistics::Data
Statistics::Distributions
Statistics::Distributions::Ancova
Statistics::Distributions::Bartlett
Statistics::Distributions::GTest
Statistics::FactorAnalysis
Statistics::FisherPitman
Statistics::Forecast
Statistics::Gap
Statistics::Gtest
Statistics::Hartigan
Statistics::KernelEstimation
Statistics::MVA::Bartlett
Statistics::MVA::BayesianDiscrimination
Statistics::MVA::HotellingTwoSample
Statistics::Normality
Statistics::OLS
Statistics::OnLine
Statistics::PCA
Statistics::PCA::Varimax
Statistics::QuickMedian
Statistics::ROC
Statistics::RVector
Statistics::RatioVariance
Statistics::Reproducibility
Statistics::SDT
Statistics::SPC
Statistics::Sequences
Statistics::Sequences::Joins
Statistics::Sequences::Pot
Statistics::Sequences::Runs
Statistics::Sequences::Turns
Statistics::Sequences::Vnomes
Statistics::Smoothing::SGT
Statistics::SocialNetworks
Statistics::Suggest
Statistics::Test::WilcoxonRankSum
Statistics::TheilSenEstimator
Statistics::Zed
Statistics::embedR
StormX::Query::DeleteWhere
Sun::Solaris::Ucred
Sunpower::Cryocooler
Sx
Sybase::Metadata
Symbol::Values
Syntax::Highlight::HTML
Syntax::Highlight::Perl
Syntax::Highlight::Shell
Syringe
Sys::CpuAffinity
Sys::Gamin
Sys::Hostname::Long
Sys::Mlockall
Sys::PortIO
Sys::SigAction
Sys::Syslog::OO
Sys::Uptime
SysConf
System::Timeout
System2
TAIR::Blast
TAIR::GeneDescriptions
TAP::Formatter::JUnit
TBX::Checker
TFTP
TL1::Toolkit
Taint::Runtime
Task::BeLike::LESPEA
Task::DualLived
Task::XNLSoar::Graphing
Tasks
Telephony::CountryDialingCodes
Template::Directive::XSSAudit
Template::Plugin::ASCIITable
Template::Plugin::AutoLink
Template::Plugin::Bootstrap::Pagination
Template::Plugin::ByDate
Template::Plugin::Config::General
Template::Plugin::Data::HTMLDumper
Template::Plugin::Devel::StackTrace
Template::Plugin::Filter::ANSIColor
Template::Plugin::HTML::BBCode
Template::Plugin::HTTP::UserAgent
Template::Plugin::JA::Fold
Template::Plugin::JSON::Escape
Template::Plugin::LLHash
Template::Plugin::ListOps
Template::Plugin::Next
Template::Plugin::NoFollow
Template::Plugin::SSI
Template::Plugin::StickyQuery
Template::Plugin::Trac
Template::Plugin::Translit::RU
Template::Plugin::UTF8toANSI
Template::Plugin::WikiCreole
Template::Plugin::YUI2::Loader
Template::Replace
Template::Twostep
Teradata::BTET
Term::ANSIColor
Term::Activity
Term::BashTab
Term::Chart
Term::Info
Term::Interact
Term::Menu
Term::Menu::Hierarchical
Term::Menus::FromFile
Term::RawInput
Term::ReadLine::Event
Term::TUI
Term::Twiddle
Term::VT102
Test::AnyEvent::Time
Test::Bitcoin::Daemon
Test::BoostUnit
Test::Builder::Clutch
Test::CheckChanges
Test::Config::System
Test::ConsistentVersion
Test::DBIx::Class::Factory
Test::Structures::Data
Test::DataLoader::MySQL
Test::Env
Test::Excel
Test::Files
Test::GreaterVersion
Test::Groonga
Test::HTML::W3C
Test::HTTPStatus
Test::LWP::UserAgent
Test::Mail
Test::Manifest
Test::Mock::Alarm
Test::Mock::LWP::Dispatch
Test::Mock::Net::SNMP
Test::MockTime
Test::Mojibake
Test::Mojo::Session
Test::More::Hooks
Test::NoPlan
Test::Numeric
Test::Perl::Metrics::Simple
Test::Pod::Content
Test::RandomResults
Test::Reporter::Transport::Net::SMTP::Authen
Test::Reporter::Transport::Net::SMTP::SSL
Test::SFTP
Test::SVN::Repo
Test::Singleton
Test::Slow
Test::Subs
Test::TempDatabase
Test::TestCoverage
Test::URI
Test::UseAllModules
Test::Varnish
Test::WWW::Mechanize::CGIApp
Test::XML::Element
Test::XML::Order
Test::XMLElement
Text::Authinfo
Text::BarGraph
Text::Bastardize
Text::Beautify
Text::BibTeX::BibStyle
Text::CSV::Merge
Text::CSV::UniqueColumns
Text::CSV_PP::Iterator
Text::CSV_XS
Text::Cipher
Text::Contraction
Text::Convert::ToImage
Text::DoubleMetaphone
Text::DoubleMetaphone_PP
Text::EditTranscript
Text::Embed
Text::FastTemplate
Text::FillIn
Text::FindLinks
Text::FixEOL
Text::Format::Screenplay
Text::Fracture
Text::Header
Text::Iconv
Text::LAS::Parser
Text::LineNumber
Text::Lossy
Text::Macros
Text::Median
Text::Metaphone
Text::Names
Text::Netstring
Text::OutputFilter
Text::Patch::Rred
Text::Printf
Text::Record::Deduper
Text::Report
Text::ScriptTemplate
Text::Scws
Text::SenseClusters
Text::Shift
Text::SimpleTemplate
Text::SpellChecker
Text::Starfish
Text::Statistics::Cyrillic
Text::Statistics::GreekAndCoptic
Text::Statistics::Latin
Text::StripAccents
Text::TagTemplate
Text::TemplateLite::Standard
Text::Templet
Text::Textile
Text::Tidx
Text::Tokenizer
Text::TreeFile
Text::Trie
Text::Unaccent::PurePerl
Text::Undiacritic
Text::Vpp
Text::WikiCreole
Text::XmlMatch
Text::vFile::toXML
Text::xSV
Thread::IID
Thread::Pool::Simple
Thread::RWLock
Thread::Workers
Tie::AliasHash
Tie::Array::AsHash
Tie::Array::Atomic
Tie::Array::Cavity
Tie::Array::QueueExpire
Tie::Array::Random
Tie::CPHash
Tie::Cache
Tie::Cache::Autoupdater
Tie::Concurrent
Tie::Constrained
Tie::CountLoop
Tie::Cvs
Tie::Cycle
Tie::Cycle::Sinewave
Tie::DBIx::Class
Tie::DB_Lock
Tie::Dir
Tie::DxHash
Tie::File::Hashify
Tie::FileLRUCache
Tie::FlatFile::Array
Tie::GHash
Tie::Hash::Identity
Tie::Hash::ImmutableKeys
Tie::Hash::MultiValue
Tie::Hash::Regex
Tie::Hash::RegexKeys
Tie::Hash::Sorted
Tie::HashDefaults
Tie::LevelDB
Tie::ListKeyedHash
Tie::Multidim
Tie::OffsetArray
Tie::Proxy::Changes
Tie::Queue
Tie::ShadowHash
Tie::StoredOrderHash
Tie::StrictHash
Tie::TextDir
Tie::Tk::Listbox
Tie::Tk::Text
Tie::Toggle
Tie::TransactHash
Tie::Wx::Widget
Time::Avail
Time::Checkpoint
Time::Clock
Time::Duration::sv
Time::Elapse
Time::Fuzzy
Time::LST
Time::Normalize
Time::Object
Time::Piece::Adaptive
Time::Piece::DB2
Time::Piece::MySQL
Time::Simple::Range
Time::Skew
Time::Stamp
Time::Stopwatch
Time::UTC::Now
Time::Unix
Time::Vector
Timer::Simple
Timestamp::Simple
Tk::ApplicationNest
Tk::Autoscroll
Tk::Canvas::GradientColor
Tk::Clock
Tk::CollapsableFrame
Tk::ColoredButton
Tk::Copy::Mac
Tk::CursorControl
Tk::DateEntry
Tk::DatePick
Tk::DiffText
Tk::DoCommand
Tk::Dressing
Tk::DynaTabFrame
Tk::Enscript
Tk::ErrorDump
Tk::ExecuteCommand
Tk::FileDialog
Tk::FmtEntry
Tk::FontDialog
Tk::FullKeypad
Tk::Getopt
Tk::Gpack
Tk::Graph
Tk::GridColumns
Tk::HyperText
Tk::IPEntry
Tk::Image::Cut
Tk::LCD
Tk::LineGraph
Tk::LineNumberText
Tk::LockDisplay
Tk::MARC::Editor
Tk::MIMEApp
Tk::MIMEApp::DataToTk
Tk::Markdown
Tk::MarkdownTk
Tk::MatchEntry
Tk::MinMaxScale
Tk::Mirror
Tk::NumKeypad
Tk::ObjScanner
Tk::PerlInheritanceTree
Tk::PerlMethodList
Tk::Playlist
Tk::PlotDataset
Tk::ProgressBar::Mac
Tk::ROSyntaxText
Tk::RotCanvas
Tk::RotatingGauge
Tk::Schedule
Tk::SevenSegmentDisplay
Tk::SlideSwitch
Tk::Spectrum
Tk::StyledButton
Tk::TIFF
Tk::TOTD
Tk::Thumbnail
Tk::TimePick
Tk::TipEntry
Tk::Tree::JSON
Tk::Tree::XML
Tk::TreeGraph
Tk::WaitBox
Tk::XMLViewer
Tk::autobind
Tkx::FindBar
Tkx::ImageButton
Tkx::ROText
Tkx::Scrolled
Tkx::SplashScreen
ToolSet::y
Tree::AVL
Tree::Nary
Tree::Suffix
Tree::Ternary
Tree::Ternary_XS
Tree::Trie
Tribunais::TJES
Tribunais::TRTES
Twitter::Badge
UML::Class::Simple
UML::State
URI::Based
URI::ParseSearchString
URI::Sequin
URL::Normalize
UTM5::URFAClient
UTM5::URFAClient::Daemon
UUID::Tiny
Ubic::Service::Hypnotoad
UkrMoney::API
Unicode::Casing
Unicode::Escape
Unicode::Lite
Unicode::Map8
Unicode::MapUTF8
Unicode::Property::XS
Unicode::UTF8simple
Unix::Login
Unix::Mknod
Unix::PID
Unix::Syslog
Upp::Reader
User::Utmp
VCS::SCCS
VCS::StarTeam
VK::App
VMS::Logical
VMS::Time
VMware::LabManager
Validate::Tiny
Variable::Magic
Verilog::Readmem
Verilog::VCD
Video::Dumper::QuickTime
Video::Flvstreamer
Video::ZVBI
VideoLan::Client
Voicent
Vonage::Click2Call
WSDL::XML::Generator
WWW::AfinimaKi
WWW::Alexa::API
WWW::Alexa::TrafficRank
WWW::Asg
WWW::BBSWatch
WWW::BF2Player
WWW::BF2S
WWW::Bleep
WWW::Blog::Identify
WWW::Bugzilla3
WWW::BurrpTV
WWW::Correios::CEP
WWW::Coursera
WWW::Curl::TraceAscii
WWW::Dilbert
WWW::Extractor
WWW::Fimfiction
WWW::FreshBooks::API
WWW::Fuel::US::Prices
WWW::GameMonitor
WWW::Google::PageRank
WWW::Google::Translate
WWW::HarWalk
WWW::Honeypot::httpBL
WWW::Indeed
WWW::Instapaper::Client
WWW::Kinghost::Painel
WWW::KrispyKreme
WWW::KrispyKreme::HotLight
WWW::LaQuinta::Returns
WWW::LargeFileFetcher
WWW::Mechanize::Meta
WWW::Mechanize::Plugin::FollowMetaRedirect
WWW::MediaTemple
WWW::MovieReviews::NYT
WWW::MyNewsletterBuilder
WWW::Netflix
WWW::Offliberty
WWW::Offline::Toolkit
WWW::Pixelletter
WWW::PkgFind
WWW::RSSFeed
WWW::RenRen
WWW::RottenTomatoes
WWW::SEOGears
WWW::Salesforce::Report
WWW::Scraper::F1
WWW::Scraper::ISBN::LibUniIt_Driver
WWW::Scraper::Typo3
WWW::Search::AlltheWeb
WWW::Search::FirstGov
WWW::Search::Go
WWW::Search::ISBNDB
WWW::Search::RpmFind
WWW::Search::UrbanDictionary
WWW::Selenium::NetworkCapture
WWW::Shorten::Bitly
WWW::Shorten::Digg
WWW::Shorten::URLchen
WWW::Shorten::Yourls
WWW::Simpy
WWW::Socrata
WWW::Sucksub::Attila
WWW::Sucksub::Extratitles
WWW::Sucksub::Frigo
WWW::Sucksub::Vostfree
WWW::TinySong
WWW::Translate::Apertium
WWW::Translate::interNOSTRUM
WWW::Twittervision
WWW::Txodds
WWW::URLToys
WWW::VirtualPBX
WWW::Weebly
WWW::Wuala
WWW::Yahoo::InboundLinks
WWW::Yahoo::Smushit
WWW::Yandex::MailForDomain
WWW::eiNetwork
Waft::JSON
Warn::Colorful
Weather::Airport
Weather::Google
Weather::NOAA::Alert
Weather::NOAA::GFS
Weather::Underground::StationHistory
Web::Scaffold
WebCache::Digest
WebService::Antispam
WebService::Basecamp
WebService::Connpass
WebService::E4SE
WebService::EditDNS
WebService::Embedly
WebService::FileCloud
WebService::Futu
WebService::Google::Contact
WebService::Gravatar
WebService::Hatena::Bookmark::Lite
WebService::Hatena::BookmarkCount
WebService::Jamendo::RSS
WebService::Kaolabo
WebService::KuronekoYamato
WebService::MobileMe
WebService::NZBMatrix
WebService::NiigataUnyu
WebService::Pastefire
WebService::Pushover
WebService::Rajce
WebService::SEOmoz::FreeAPI
WebService::SagawaKyubin
WebService::Scriptogram
WebService::ShiftPlanning
WebService::Soundcloud
WebService::Sprint
WebService::Uptrack
WebService::Validator::HTML::W3C::Fast
WebService::Viddler
WebService::YQL
WebService::Zoopla::API
WebService::Zusaar
WebSphere::Payment
Webalizer::Hist
Weblogic::UserAdmin
Weblogic::WLST
Whisper
Whitespace
Wiki::Gateway
Wiki::Toolkit::Formatter::XHTMLMediaWiki
Wiki::Toolkit::Store::Mediawiki
Win32::ADO
Win32::AbsPath
Win32::CheckDotNet
Win32::Console::ANSI
Win32::Daemon::Simple
Win32::DirSize
Win32::DriveInfo
Real::Encode
Win32::Env
Win32::FTDI::FTD2XX
Win32::FetchCommand
Win32::Filenames
Win32::GUI::HyperLink
Win32::GetDefaultBrowser
Win32::GlobalHotkey
Win32::HideConsole
Win32::HostExplorer
Win32::IIS::Admin
Win32::IdentifyFile
Win32::IntAuth
Win32::InternetShortcut
Win32::JobAdd
Win32::LockWorkStation
Win32::LongPath
Win32::MSAgent
Win32::MSI::HighLevel
Win32::MediaPlayer
Win32::Monitoring::Session
Win32::Monitoring::WindowPing
Win32::Outlook::IAF
Win32::PEFile
Win32::PerfMon
Win32::PerlExe::Env
Win32::Process::Critical
Win32::Process::Hide
Win32::Process::Kill
Win32::Process::Suspend
Win32::RASE
Win32::RemoteTOD
Win32::SearchPath
Win32::SharedFileOpen
Win32::SoundRec
Win32::StreamNames
Win32::SysPrivilege
Win32::SysTray
Win32::SystemInfo
Win32::UTCFileTime
Win32::Unicode::InternetShortcut
Win32::Unicode::Shortcut
Win32::WebBrowser
Win32API::File::Time
Win32API::GUID
Win32::GUI::Carp
Win32::AdminMisc
Winamp::Controller
Word::Anagram
WordNet::BestStem
WordNet::SenseRelate::AllWords
Workflow::XPDL
Wx::WidgetMaker
X::Osd
X11::Aosd
X11::FreeDesktop::DesktopEntry
X11::IdleTime
X11::Wcl
XML::API::WIX2
XML::ApacheFOP
XML::Atom::Ext::Inline
XML::CSV
XML::Canonical
XML::Constructor
XML::DTDParser
XML::Descent
XML::Edifact
XML::Excel
XML::FromArrayref
XML::GDOME::XSLT
XML::GenericJSON
XML::Handler::EasyTree::Generator
XML::Hash::XS
XML::Merge
XML::OPML
XML::Parser::Nodes
XML::Quick
XML::Registry
XML::Rules
XML::SAXDriver::CSV
XML::SAXDriver::Excel
XML::Simple
XML::Table2XML
XML::Tidy
XML::TreePP::XMLPath
XML::Writer::String
XMail::Install
XPanel
XRD::Parser
Xbase
Xen::API
Xfce4
Xymon
Xymon::Client
Xymon::Monitor::Informix
YAMC
YAML::Accessor
Yahoo::Weather
Zabbix::Sender
App::Anarch
autobox::List::Util
autobox::String::Inflector
autobox::dump
cPanel
cPanel::nginx
Data::Trie
fields::aliased
iCal::Parser
iCal::Parser::HTML
iCal::Parser::SAX
Text::iPerl
Bio::mGen
namespace
Net::LastFMAPI
WWW::iTunesConnect
Archie
Pg
App::pmcheck
Pod::Lyx
re::engine::LPEG
re::engine::Lua
Config::Sofu
Devel::TraceFuncs
Win32::Guidgen
Win32::Snarl
