#!/usr/bin/perl

=pod

remove everything from distmtimes that prevents mldistwatch from indexing.

=cut

use strict;
use warnings;

use lib "lib", "privatelib";
use PAUSE;

my $dbh = PAUSE::dbh;
my $sth = $dbh->prepare("delete from distmtimes where dist=?");
$| = 1;
while (<DATA>){
  chomp;
  my $rows = $sth->execute($_);
  print $rows;
}
print "\n";

__END__
M/MA/MARCEL/Getopt-Attribute-1.3.2.tar.gz
H/HL/HLHAMILT/Getopt-ExPar-0.01.tar.gz
C/CD/CDENT/PurpleWiki/PurpleWiki-0.94.tar.gz
W/WV/WVDB/Gnome-StockIcons-1.4.2.tar.gz
M/MA/MAKLER/Net-ESMTP-0.2.1.tar.gz
A/AH/AHICOX/DBIx-YAWM-2.2.5.tar.gz
A/AN/ANDREWC/Algorithm-Diff-Apply-0.2.3.tar.gz
M/MA/MADWOLF/OpenCA-Session-0.9.2.tar.gz
C/CR/CRAFFI/Bundle-BioPerl-2.1.5.tar.gz
H/HE/HERVEUS/Weaving-Tablet-0.8.2.tar.gz
S/SH/SHLOMIF/Bundle-QuadPres-0.8.3.tar.gz
M/MA/MADWOLF/OpenCA-REQ-0.9.52.tar.gz
M/MA/MADWOLF/OpenCA-DBI-0.9.95.tar.gz
M/MA/MADWOLF/OpenCA-AC-0.9.30.tar.gz
N/NP/NPEREZ/POE-Component-Cache-0.1.1.tar.gz
W/WA/WASX/Win32-Printer-0.9.0.zip
S/SH/SHLOMIF/Bundle-Zavitan-0.2.0.tar.gz
P/PH/PHCOTE/Devel-Monitor-0.9.0.7.tar.gz
J/JC/JCDUQUE/Crypt-Misty1-1.1.3.tar.gz
R/RE/RETOH/Template/Website-1.14.01.tar.gz
O/OP/OPIATE/HTML-ReportWriter-1.3.2.tar.gz
J/JR/JRED/Video-DVDRip-0.97.2.tar.gz
M/MA/MADWOLF/OpenCA-Crypto-0.9.6.tar.gz
M/MA/MADWOLF/OpenCA-RBAC-0.2.0.tar.gz
R/RE/RETOH/Crypt-Lite-0.82.06.tar.gz
P/PS/PSCHNELL/HTML-Processor-0.2.1.tar.gz
S/SH/SHLOMIF/HTML-Strip-Whitespace-0.1.5.tar.gz
B/BP/BPRUDENT/Markup-TreeNode-1.1.6.tar.gz
N/NP/NPEREZ/PXR-0.1.5.tar.gz
F/FE/FEN/XRI-0.2.4.tar.gz
G/GO/GOYALI/SMS_API_3.01.1.tar.gz
T/TU/TUCKERM/BZFlag-Info-1.9.2.tar.gz
M/MU/MUENALAN/Class-Protected-0.01.02.tar.gz
L/LO/LOGVINON/CORBA-MICO-0.6.6.tar.gz
B/BA/BARNINGER/WWW-Authenticate-0.6-1.tar.gz
J/JE/JETTERO/Net-SMTP-OneLiner-1.2.0.tar.gz
D/DS/DSPIZZ/Time-Tradedates-0.1.2.tar.gz
P/PA/PAJAS/XML-XUpdate-LibXML-0.6.0.tar.gz
G/GM/GMPASSOS/XML-Smart-1.6.9.tar.gz
S/ST/STSANDER/Device-Davis-1.2.1.tar.gz
K/KR/KRZAK/CGI-kSession-0.5.3.tar.gz
M/MG/MGRAHAM/Class-Constructor-1.1.4.tar.gz
S/SH/SHLOMIF/HTML-Links-Localize-0.2.4.tar.gz
S/SH/SHLOMIF/HTML-Latemp-News-0.1.6.tar.gz
A/AE/AELFAKIH/Apache-Centipaid-1.3.1.tar.gz
S/SH/SHLOMIF/SVN-RaWeb-Light-0.6.0.tar.gz
G/GS/GSM/SNMP-4.2.0.tar.gz
A/AS/ASCOPE/XML-Filter-XML_Directory_2-Base-1.4.4.tar.gz
G/GL/GLOVER/Curses-Devkit-4.9.3.tar.gz
D/DL/DLUX/Parallel-ForkManager-0.7.5.tar.gz
R/RI/RICKM/DateTime-Format-Baby-1.0100.tar.gz
Z/ZE/ZENSPIDER/Apache-ContentHandler-1.3.3.tar.gz
M/MA/MATTIASH/HTTP-TransparentCache-0.3.1.tar.gz
D/DW/DWHEELER/Bundle-BricolagePlus-1.9.0.tar.gz
J/JA/JALDHAR/Acme-Brainfuck-1.1.1.tar.gz
P/PI/PIP/XML-Merge-1.2.565EgGd.tgz
M/MU/MUENALAN/Class-Listener-0.01.04.tar.gz
D/DC/DCANTRELL/Acme-Pony-1.1.2.tar.gz
J/JE/JENDA/Win32-Daemon-Simple-0.2.6.tar.gz
M/MI/MIGO/Games-Checkers-0.1.0.tar.gz
M/MI/MIGO/Arch-0.5.1.tar.gz
J/JE/JESUS/Spread-3.17.3-1.07.tar.gz
C/CS/CSOE/PDL-2.4.2.tar.gz
T/TO/TOMZO/Quota-1.5.1.tar.gz
M/MA/MADWOLF/OpenCA-X509-0.9.47.tar.gz
D/DA/DAPATRICK/Apache-ParseControl-0.1.2.tar.gz
H/HT/HTCHAPMAN/RTx-RightsMatrix-0.02.05.tgz
M/MG/MGRABNAR/File-Tail-0.99.3.tar.gz
T/TH/THEDEVIL/Mail-Sort-2003.03.18.tar.gz
P/PI/PIP/Time-DayOfWeek-1.2.4CCMRd5.tgz
R/RE/REFLOG/Lyrics-Fetcher-0.3.1.tar.gz
J/JA/JANPAZ/RayApp-1.165.tar.gz
S/SH/SHLOMIF/HTML-Latemp-GenMakeHelpers-0.1.4.tar.gz
R/RS/RSD/Event-File-0.1.1.tar.gz
J/JR/JRED/MPEG-MP3Play-0.15.tar.gz
S/SH/SHLOMIF/WWW-OpenSVN-0.1.2.tar.gz
J/JE/JETTERO/Statistics-Basic-0.41.3.tar.gz
J/JA/JALDHAR/WebService-Advogato-1.1.0.tar.gz
J/JF/JFRIEDL/Yahoo-Search-1.4.7.tar.gz
J/JH/JHINKLE/vsDB-1.4.3.tar.gz
K/KI/KILINRAX/Search-Xapian-0.9.2.2.tar.gz
I/IX/IX/Apache-Wombat-0.5.1.tar.gz
S/ST/STIG/Games-AlphaBeta-0.4.6.tar.gz
G/GR/GRICHTER/HTML-Embperl-1.3.6.tar.gz
S/SJ/SJQUINNEY/Astro-IRAF-CL-0.2.0.tar.gz
R/RE/REATMON/Net-HTTPServer-1.1.1.tar.gz
S/SH/SHLOMIF/Catalyst-Plugin-SanitizeUrl-0.2.0.tar.gz
J/JC/JCDUQUE/Digest-DMAC-1.1.4.tar.gz
N/NJ/NJH/Audio-MPD-0.12.1.tar.gz
A/AT/ATOURBIN/rpm-build-perl-0.5.2.tar.gz
M/MA/MAHEX/Image-Grab-1.4.2.tar.gz
I/IX/IX/Bundle-Wombat-0.7.1.tar.gz
A/AS/ASCOPE/XML-Filter-XML_Directory_2XHTML-1.3.1.tar.gz
G/GR/GROUSSE/WWW-Orphea-0.3.2.tar.gz
J/JE/JESUS/Mcrypt-2.4.8.2.tar.gz
G/GR/GROUSSE/WWW-Google-Images-0.6.2.tar.gz
M/MA/MARCEL/Tie-Scalar-Timeout-1.3.2.tar.gz
J/JB/JBUHACOFF/CGP-CLI-2.6.7.tar.gz
T/TI/TIMBRODY/URI-OpenURL-0.4.4.tar.gz
H/HA/HANJE/Tk-CodeText-0.3.4.tar.gz
P/PJ/PJONES/PML-0.4.1.tar.gz
B/BS/BSMITH/Hoobot-0.5.0.tar.gz
L/LE/LEMBARK/NEXT-init-1.04.1.tar.gz
R/RS/RSMITH/vuser/vuser-0.2.0.tar.gz
S/SP/SPARSONS/tools/Net-Dev-MIBLoadOrder-1.1.0.tar.gz
S/SH/SHLOMIF/Devel-LineTrace-0.1.5.tar.gz
C/CD/CDAWSON/Smil-0.898.tar.gz
D/DA/DAVIDNICO/callback/callback-hook-0.1.0.tar.gz
J/JE/JETTERO/Wharf-JDockApp-1.2.1.tar.gz
S/SH/SHLOMIF/Net-SeedServe-0.2.0.tar.gz
M/MA/MADWOLF/OpenCA-DBIS-0.2.0.tar.gz
D/DL/DLUX/Tie-Table-1.1.2.tar.gz
W/WV/WVDB/Verilog-CodeGen-0.9.4.tar.gz
B/BJ/BJR/Chess-0.6.0.tar.gz
G/GR/GROUSSE/Dict-Lexed-0.2.1.tar.gz
A/AS/ASCOPE/Image-Shoehorn-1.42.tar.gz
N/NA/NATTIS/Ananke-SqlLink-1.1.2.tgz
Y/YO/YOSEFM/Tree-Numbered-DB-1.02.2.tar.gz
A/AS/ASKSH/Devel-PiMPx-0.7.1.tar.gz
J/JE/JENDA/Win32-FileOp-0.14.1.tar.gz
D/DJ/DJKERNEN/Mail-IMAPClient-2.2.9.tar.gz
B/BO/BOBG/Blatte-0.9.4.tar.gz
J/JL/JLAPEYRE/libplot-perl-2.1.6.2b.tar.gz
P/PI/PIP/Time-PT-1.2.565EHOV.tgz
J/JE/JETTERO/Unix-Process-1.1.1.tar.gz
D/DY/DYACOB/Aw-0.16.7.tar.gz
M/ME/MERGL/pgsql_perl5-1.9.0.tar.gz
O/OT/OTAYLOR/GNOME-GNORBA-0.1.0.tar.gz
M/MU/MUENALAN/Class-MVC-0.01.06.tar.gz
K/KA/KAILI/Workflow-Wfmc-0.01e.tar.gz
R/RH/RHOOPER/HTTP-Lite-2.1.6.tar.gz
H/HO/HOWARS/Application-Pipeline-0.1.1.tar.gz
S/SH/SHLOMIF/Mail-LMLM-0.6.2.tar.gz
M/MU/MUENALAN/Winamp-Control-0.2.1.tar.gz
M/MA/MADWOLF/OpenCA-PKCS7-0.9.13.tar.gz
M/MP/MPECK/Games-Mines-0.02.tar.gz
O/OT/OTAYLOR/CORBA-ORBit-0.4.3.tar.gz
C/CZ/CZBSD/Myco-0.01.tar.gz
M/MA/MATTMK/GoXML-XQI-1.1.4.tar.gz
I/IX/IX/Bundle-Apache-Wombat-0.5.1.tar.gz
E/ED/EDAVIS/Lingua-Preferred-0.2.4.tar.gz
K/KH/KHOERLING/Mail-POPRelay-2.1.1.tar.gz
J/JA/JALDHAR/DateTime-Calendar-Discordian-0.9.2.tar.gz
A/AK/AKOLB/Solaris-Lgrp-0.1.2.tar.gz
J/JA/JANNINO/Tk-RadiobuttonGroup-0.2.2.tar.gz
A/AS/ASKSH/glist-0.9.17a10.tar.gz
M/MA/MADWOLF/OpenCA-TRIStateCGI-1.5.5.tar.gz
S/SH/SHLOMIF/Bundle-Latemp-0.2.3.tar.gz
T/TB/TBONE/Apache-File-Resumable-1.1.1.1.tar.gz
M/MA/MADWOLF/OpenCA-XML-Cache-0.9.3.tar.gz
S/SH/SHLOMIF/HTML-Latemp-NavLinks-GenHtml-0.1.5.tar.gz
J/JE/JETTERO/Business-CSI-0.81.1.tar.gz
I/IX/IX/Wombat-0.7.1.tar.gz
D/DA/DANBERR/Authen-PAAS-1.1.0.tar.gz
G/GR/GREGFAST/POE-Component-Server-HTTPServer-0.9.2.tar.gz
L/LR/LREEVES/DBI-ResultPager-0.9.1.tar.gz
M/MA/MADWOLF/OpenCA-Configuration-1.5.3.tar.gz
R/RO/ROBF/GedNav-0.02.tar.gz
S/SC/SCOP/Bundle-W3C-Validator-0.7.0.tar.gz
M/MU/MUENALAN/Hook-Heckle-0.01.01.tar.gz
J/JW/JWIED/Mail-IspMailGate-1.1013.tar.gz
D/DG/DGOEHRIG/SDL_Perl-2.1.3.tar.gz
J/JK/JKEISER/PatchReader-0.9.5.tar.gz
M/MA/MARTIJN/POE-Session-GladeXML2-0.3.1.tar.gz
D/DL/DLUX/Class-Date-1.1.8.tar.gz
M/MA/MADWOLF/OpenCA-CRL-0.9.17.tar.gz
S/SH/SHIBLON/HTML-CMTemplate-0.4.0.tar.gz
M/MO/MORNI/XML-ParseDTD-0.1.4.tar.gz
S/SI/SIMONP/chronos-1.1.6.1.tar.gz
R/RO/ROTH/Config-Objective-0.9.1.tar.gz
M/MA/MADWOLF/OpenCA-OpenSSL-0.9.91.tar.gz
J/JC/JCRISTY/PerlMagick-6.24.tar.gz
M/MU/MUENALAN/Data-Iter-0.01.05.tar.gz
N/NO/NOG/AFS-2.2.3.tar.gz
G/GO/GOSSAMER/HyperWave-CSP-0.03.1.tar.gz
S/SH/SHLOMIF/XML-CompareML-0.2.0.tar.gz
A/AL/ALFW/AFS-Monitor-0.2.2.tar.gz
S/SH/SHLOMIF/Bundle-Sites-BetterScm-0.2.0.tar.gz
G/GR/GRICHTER/HTTP-Webdav-0.1.18-0.17.1.tar.gz
R/RS/RSMITH/vuser/VUser-Install-0.1.0.tar.gz
M/MA/MADWOLF/OpenCA-Log-0.9.4.tar.gz
S/SA/SAMSK/Text-Tokenizer-0.2.6.tar.gz
J/JR/JRED/CIPP-2.99.23_beta.tar.gz
P/PI/PIP/XML-Tidy-1.2.54HJnFa.tgz
M/MA/MAXICO/ZM-Template-0.5.2.tar.gz
E/EE/EESTABROO/IMAP-Admin-1.6.4.tar.gz
S/SH/SHLOMIF/Games-LMSolve-0.8.1.tar.gz
B/BR/BRUMLEVE/ddb-1.3.1.tar.gz
I/IX/IX/libservlet-0.9.2.tar.gz
P/PH/PHISH/CGI-XMLApplication-1.1.3.tar.gz
I/IX/IX/Bundle-libservlet-0.9.3.tar.gz
J/JA/JANL/w3mir-1.0.10.tar.gz
S/ST/STARKY/Net-Peep-0.4.5.1.tar.gz
A/AS/ASCOPE/XML-Filter-XML_Directory_2RSS-0.9.1.tar.gz
M/MU/MUENALAN/Data-Type-0.01.15.tar.gz
G/GR/GRICHTER/Embperl-2.1.0.tar.gz
D/DW/DWHEELER/Bundle-Bricolage-1.9.0.tar.gz
Y/YE/YEWEI/Jvm-0.9.2.tar.gz
S/SK/SKROVAN/Tk-WorldCanvas-1.2.7.tar.gz
D/DL/DLECONTE/Parallel-Pvm-1.3.0.tgz
Z/ZO/ZOCCAV/Net-FreeDB2-0.8.2.6.tar.gz
D/DO/DOPACKI/File-List-0.3.1.tar.gz
C/CA/CAFFIEND/font_ft2_0.1.0.tgz
N/NE/NEVES/HTML-FormWizard-0.1.09.tar.gz
M/MU/MUENALAN/Class-Proxy-0.01.04.tar.gz
G/GR/GROUSSE/Dict-FSA-0.1.1.tar.gz
S/SE/SEGAN/POE-Component-LaDBI-1.2.1.tar.gz
J/JB/JBUHACOFF/CGI-Session-Driver-flexmysql-0.2.04.tar.gz
A/AA/AALLAN/Astro-ADS-1.20.7.tar.gz
P/PI/PIP/Games-Cards-Poker-1.2.565CHh5.tgz
B/BP/BPRUDENT/Markup-Tree-1.2.2.tar.gz
L/LA/LARSNYG/Text-Identify-BoilerPlate-0.3.1.tar.gz
A/AL/ALEXMASS/bioinfo/InSilicoSpectro-1.2.5.tar.gz
D/DA/DANBERR/Config-Record-1.1.0.tar.gz
J/JE/JENDA/CGI-Authent-0.2.1.tar.gz
V/VE/VESELOSKY/CGI-Builder-Auth-0.06.tar.gz
P/PI/PIP/Math-BaseCnv-1.2.59M7mRX.tgz
M/MA/MAXICO/ZM-Session-0.2.0.tar.gz
S/SH/SHLOMIF/Acme-Gosub-0.1.2.tar.gz
A/AN/ANDREWC/Piffle-Template-0.3.1.tar.gz
J/JE/JETTERO/Games-Go-SGF2misc-0.9.3.tar.gz
P/PI/PICZ/Image-ButtonMaker-0.1.4.tar.gz
J/JE/JENDA/Mail-Sender-0.8.10.tar.gz
D/DA/DAIBA/Finance-NikkeiQuote-0.5.1.tar.gz
P/PA/PAJAS/XML-XSH-1.8.2.tar.gz
N/NP/NPEREZ/POE-Component-PXR-0.1.1.tar.gz
A/AL/ALEXIOB/Tk-Text-SuperText-0.9.4.tar.gz
R/RS/RSD/Authen-SimplePam-0.1.24.tar.gz
H/HA/HARDAKER/QWizard-2.2.1.tar.gz
P/PH/PHOTO/Getopt-Casual-0.13.1.tar.gz
J/JA/JANNINO/Tk-CheckbuttonGroup-0.2.2.tar.gz
M/MA/MADWOLF/OpenCA-Tools-0.4.3.tar.gz
C/CF/CFRETER/Rcs-1.05.tar.gz
