#!/bin/bash
#
# Startup script for the Apache Web Server
#
# chkconfig: 345 85 15
# description: pause httpd on port 81
# processname: httpd
# pidfile: /opt/apache/current/logs/httpd.pid
# config: /opt/apache/current/conf/httpd.conf

# Source function library.
. /etc/rc.d/init.d/functions

INITLOG_ARGS=""
apachectl=/opt/apache/current/bin/apachectl
httpd=/opt/apache/current/bin/httpd
prog=PAUSE-httpd
pidfile=/opt/apache/current/logs/httpd.pid
lockfile=/var/lock/subsys/PAUSE-httpd
configfile=/opt/apache/current/conf/httpd.conf
RETVAL=0

start() {
        echo -n $"Starting $prog: "
        $httpd -f ${configfile}
        RETVAL=$?
        [ $[$RETVAL] -eq 0 ] && echo "[OK]" || echo "[FAILED]"
        [ $RETVAL = 0 ] && touch ${lockfile}
        return $RETVAL
}
stop() {
        echo -n $"Stopping $prog: "
        if [ -f "${pidfile}" ]; then
                ps $(cat "${pidfile}" | head -n 1 | sed -r -e 's/^([\d]+)/\1/g') >& /dev/null
                if [ $[$?] -eq 0 ]; then
                        kill -TERM $(cat "${pidfile}" | head -n 1 | sed -r -e 's/^([\d]+)/\1/g')
                        RETVAL=$?
                else
                        RETVAL=1;
                        echo "No process with pid "$(cat "${pidfile}" | head -n 1 | sed -r -e 's/^([\d]+)/\1/g')" was found.   "
                fi
        else
                RETVAL=1;
                echo -n "No pid file '${pidfile}' was found.   "
        fi
        if [ $[$RETVAL] -eq 0 ]; then
                echo "[OK]" || echo "[FAILED]"
                rm -f ${lockfile} ${pidfile}
                echo "Waiting 5 seconds to let ${prog} free all resources."
                sleep 5s
        fi
}
# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
	status -p ${pidfile} PAUSE-httpd
        RETVAL=$?
        ;;
  restart)
        stop
        start
        ;;
  condrestart)
        if [ -f ${pidfile} ] ; then
                stop
                start
        fi
        ;;
  *)
        echo $"Usage: $prog {start|stop|restart|condrestart|help}"
        exit 1
esac

exit $RETVAL
