#! /bin/sh
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/bin/rsync
# given that this filename is PAUSE-rsyncd and the conf file is rsyncd.conf
# I plead for rsyncd.pid
PIDFILE=/var/run/rsyncd.pid

ARGS="--daemon"

test -x $DAEMON || exit 0

case "$1" in
  start)
    echo -n "Starting rsync"
    start-stop-daemon --verbose --start --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $ARGS &
    echo "."
    ;;
  stop)
    echo -n "Stopping rsync"
    start-stop-daemon --verbose --stop --pidfile $PIDFILE --exec $DAEMON -- $ARGS
    echo "."
    ;;
  reload)
    echo "Not implemented."
    ;;
  force-reload|restart)
    sh $0 stop
    sh $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/PAUSE-rsyncd {start|stop|restart|force-reload|reload}"
    exit 1
    ;;
esac

exit 0
